wso2/product-microgateway

- integration/test-integration/pom.xml
- pom.xml
- release-note.html
Remove dependency versions from test pom to root pom
Fixes Task
Not Tested
---
> Add dependencies to root pom

- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Updating image names etc for next dev iteration.
Fixes #
Not Tested
---
> Prep for next dev iteration.

- pom.xml
- resources/docker-compose/apim/conf/deployment.toml
- resources/docker-compose/apim/docker-compose.yaml
- resources/k8s-artifacts/apim/apim-config.yaml
- resources/k8s-artifacts/apim/apim-deployment.yaml
> Updating control plane artifacts to be compatible with APIM RC.

- adapter/internal/oasparser/model/mgw_swagger.go
Fixes https://github.com/wso2/product-microgateway/issues/1956
Not Tested
---
> Add backend endpoint port validation

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/APIMLifecycleBaseTest.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/APIMWithMgwBaseTest.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/APIManagerWithMgwServerInstance.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCaseBefore/APIManagerInitializeTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apim/VhostAPIMTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
- integration/test-integration/src/test/resources/apim/vhost-deployment.toml
- integration/test-integration/src/test/resources/testng.xml
- Add vhost integration test for APIM
Fixes https://github.com/wso2/product-microgateway/issues/1960
---
> Add vhost integration test for APIM

- adapter/internal/api/apis_impl.go
Fixes #1966
- Integration tests added: YNo
Tested
---
> Fix sandbox endpoint security auth header

- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/UnsecuredAPIAuthenticator.java
Fix issue of allowing to invoke blocked APIs if the API is unsecured.
Fixes #1963 
Not Tested
---
> Fix #1963 - API LC state block does not work for unsecured APIs

- enforcer/LICENSE.txt
- pom.xml
- release-note.html
> Updating license and release note

- pom.xml
Update APIM version to 4.0.0
Fixes Task
Not Tested
---
> Update APIM version

- pom.xml
- resources/docker-compose/apim/docker-compose.yaml
- resources/k8s-artifacts/apim/apim-deployment.yaml
> Updating apictl + APIM docker images.

- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
$subject
Fixes #1958
Not Tested
---
> analytics fix: errors for tenant are not shown properly

- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
$subject
Fixes #1977 
Not Tested
---
> bug fix: denied policies and analytics does not work together

- release-note.html
- remove-containers.sh
- resources/docker-compose/apim/conf/deployment.toml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/apim/apim-config.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
- resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
- resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
> Prepping RC release.

- adapter/internal/adapter/adapter.go
- adapter/internal/synchronizer/apis_fetcher.go
> Improve debug logs

- adapter/internal/adapter/adapter.go
- adapter/internal/discovery/xds/enforcer_callbacks.go
- adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
- adapter/internal/messaging/connection.go
- adapter/internal/messaging/km_listener.go
- adapter/internal/messaging/notification_listener.go
- adapter/internal/messaging/revoked_token_listener.go
- adapter/internal/synchronizer/keymanagers_fetcher.go
- adapter/loggers/logger.go
- adapter/src/main/resources/Dockerfile
- pom.xml
This PR add improvements for logging:
- Improve enforcer xds logging
- Add notification error logs
- Update dependency versions of packages
Fixes https://github.com/wso2/product-microgateway/issues/1994
Not Tested
---
> Add logging improvements

- adapter/pom.xml
- distribution/pom.xml
- enforcer/pom.xml
- enforcer/src/main/resources/Dockerfile
- integration/mock-backend-server/pom.xml
- integration/pom.xml
- integration/test-integration/pom.xml
- pom.xml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
- router/pom.xml
Bump versions for the patch release
Fixes #
Not Tested
---
> Bump version for 0.9.0.1 patch release

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/APIMWithMgwBaseTest.java
The following info log flooding the integration test log with a HTML response as follows. 
Fixes #
Tested
---
> Remove unnecessary info log in test

- adapter/internal/adapter/adapter.go
- adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
- adapter/internal/messaging/connection.go
- adapter/internal/messaging/event_types.go
- adapter/internal/messaging/km_listener.go
- adapter/internal/messaging/notification_listener.go
- adapter/internal/messaging/revoked_token_listener.go
- adapter/internal/synchronizer/keymanagers_fetcher.go
- adapter/loggers/logger.go
- enforcer/src/main/resources/Dockerfile
- pom.xml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
This PR add improvements for logging:
- Improve enforcer xds logging
- Add notification error logs
- Update dependency versions of packages
Fixes https://github.com/wso2/product-microgateway/issues/1994
Not Tested
---
> [main] Add Logging improvements

- adapter/pom.xml
- distribution/pom.xml
- enforcer/pom.xml
- integration/mock-backend-server/pom.xml
- integration/pom.xml
- integration/test-integration/pom.xml
- pom.xml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
- router/pom.xml
Bump version for the tag 0.9.0.2
Fixes #
Not Tested
---
> Bump version for the patch tag (0.9.0.2)

- adapter/pom.xml
- distribution/pom.xml
- enforcer/pom.xml
- integration/mock-backend-server/pom.xml
- integration/pom.xml
- integration/test-integration/pom.xml
- pom.xml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
- router/pom.xml
Prepare for the next development version 0.9.1-SNAPSHOT
Fixes #
Not Tested
---
> Prepare for the next development iteration

- adapter/pom.xml
- distribution/pom.xml
- enforcer/pom.xml
- integration/mock-backend-server/pom.xml
- integration/pom.xml
- integration/test-integration/pom.xml
- pom.xml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
- router/pom.xml
> Prepare for release 0.9.0.3

- resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
- resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Fixes https://github.com/wso2/product-microgateway/issues/2014
Not Tested
---
> Update k8s config maps with the new enforcer configuration

- pom.xml
> Update nimbus.jose.jwt version

- adapter/internal/api/apis_impl.go
- adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
- adapter/internal/discovery/xds/server.go
$subject as a quick fix to the #2025. The parent issue needs to be addressed properly later. 
This reverts the #1908  Hence it opens #1907.
Fixes #2025
Kubernetes with apim 
---
> Revert XDS Cache fallback on enforcer NACK message.

- enforcer/pom.xml
- pom.xml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
log4j2 properties file is not correctly applied for the components from https://github.com/wso2/apim-analytics-publisher. The reason is that slf4j binding is not done properly.
Fixes #2020
Docker 
---
> Fix the slf4j binding issue

- pom.xml
Fixes https://github.com/wso2/product-microgateway/issues/2029
Tested
---
> Update json-smart version

- adapter/internal/synchronizer/apis_fetcher.go
Fixes https://github.com/wso2/product-microgateway/issues/2048
Not Tested
---
> Add info log for api project zip file read

- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/config_generator.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
This PR add the organization id to the cluster name
`<organizationID>_cluster-sand/prod_<vhost>_<api_name>_<version>`
Fixes https://github.com/wso2/product-microgateway/issues/2041
Not Tested
---
> Add organization ID to the cluster name

- enforcer/pom.xml
- pom.xml
Fixes https://github.com/wso2/product-microgateway/issues/2058
Not Tested
---
> Update the snakeyaml version

- adapter/internal/api/apis_impl.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/open_api.go
- adapter/internal/oasparser/model/open_api_internal_test.go
- adapter/internal/oasparser/model/swagger.go
- adapter/internal/oasparser/model/swagger_internal_test.go
- adapter/internal/oasparser/model/swagger_test.go
- adapter/internal/oasparser/operator/operator.go
- adapter/internal/oasparser/operator/operator_test.go
Handle malformed endpoints
Fixes #2083 
Not Tested
---
> Handle malformed endpoints

- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiListDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/KeyManagerDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/RevokedTokenDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ThrottleDataDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
Fixes #2093 
Fixes #2094
Not Tested
---
> Fix #2092 - Improve enforcer logs

- adapter/internal/adapter/adapter.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/synchronizer/apis_fetcher.go
- adapter/pkg/messaging/connection.go
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Fixes https://github.com/wso2/product-microgateway/issues/2102
Not Tested
---
> Add readiness probe for router

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APICorsConfigurationDTO.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
- components/micro-gateway-cli/src/main/resources/templates/caching.mustache
- components/micro-gateway-cli/src/main/resources/templates/service.mustache
- components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
- tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/cors/CorsTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/util/HttpResponse.java
- tests/src/test/resources/openAPIs/cors/cors_sample.yaml
- tests/src/test/resources/testng.xml
Fixes https://github.com/wso2/product-microgateway/issues/1684, https://github.com/wso2/product-microgateway/issues/1691
Not Tested
---
> Adding Access-Control-Expose-Headers support to microgateway and fixing MGToolkit build failure when importing response cache enabled API from APIM.

- components/micro-gateway-cli/src/main/resources/templates/pathParameters.mustache
> Fix for the MGToolkit build failure when having ballerina keywords in API resource paths.

- components/micro-gateway-core/src/main/ballerina/Ballerina.toml
- pom.xml
This PR will upgrade the jackson-databind version to 2.12.3.
Fixes #
Not Tested
---
> Update jackson package version.

- adapter/internal/adapter/adapter.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/synchronizer/apis_fetcher.go
- adapter/pkg/messaging/connection.go
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
> Merging main to feature branch

- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
Fix $subject by populating API UUID to authentication Context when InternalKey Authentication handler and Unsecured Authentication handler is involved in the request flow.
Fixes #2114 
Not Tested
---
> Bug Fix: APIUUID is not published to Analytics when Internal-Key is used.

- enforcer/src/main/resources/Dockerfile
Fixes  https://github.com/wso2/product-microgateway/issues/2119
locally tested on microk8s..
---
> Fix #2119 Change enforcer base image to jdk based image

- components/micro-gateway-core/src/main/ballerina/Ballerina.toml
Fixes below error while building
```
error: invalid Ballerina.toml file: 'version' under [project] is not semver
```
Fixes #
Not Tested
---
> Fix version in ballerinaToml

- adapter/internal/api/apis_impl.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/discovery/xds/server_test.go
- adapter/internal/discovery/xds/server_utils.go
- adapter/internal/discovery/xds/server_utils_test.go
This PR adds map changes required to support the API Renaming feature in the APIM flow and API Ctl flow.
Adds the fix for https://github.com/wso2/product-microgateway/issues/2049
Not Tested
---
> Support API UUID for Internal Maps

- adapter/internal/messaging/messaging_test.go
- adapter/internal/messaging/notification_listener.go
$subject.
Fixes #2125 
- Unit tests added: yes
Not Tested
---
> Bug Fix: if duplicate remove events are received, xds cache gets cleared

- adapter/internal/api/apis_impl.go
- adapter/internal/oasparser/model/constants.go
Introduce a new WEBSUB API type.
Fixes wso2-enterprise/choreo/issues/5411
Linux
---
> Introduce private AsyncAPIs to MicroGateway.

- adapter/pkg/messaging/connection.go
Bug fix: pass object to the channel rather than the reference, to avoid the issue of having duplicate events
Fixes #2129
Not Tested
---
> Bug fix: Event duplication

- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Add missing checks for the AsyncAPI.
Fixes wso2-enterprise/choreo/issues/5411
Linux
---
> Add missing checks for AsyncAPI.

- adapter/internal/discovery/xds/server_test.go
This PR adds a unit test case for https://github.com/wso2/product-microgateway/issues/2049
Fixes #
Not Tested
---
> Add unit test case

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaParameter.java
- components/micro-gateway-cli/src/main/resources/templates/pathParameters.mustache
- components/micro-gateway-cli/src/main/resources/templates/resourceFunction.mustache
- components/micro-gateway-cli/src/main/resources/templates/service.mustache
- components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
Fixes wso2/product-microgateway#2045 & wso2/product-microgateway#2043
Fixes wso2/product-microgateway#2066
& fixed same issue in userinfo, authorize and api key endpoints
> Fixes for #2045 #2043 #2066 & other improvements 

- adapter/internal/synchronizer/apis_fetcher.go
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsUtils.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
This fix sets the correct api uuid and api creator for the fault analytics event. (auth failure)
Fixes https://github.com/wso2/product-microgateway/issues/2140
Not Tested
---
> Set correct api uuid and publisher for analytics event

- adapter/internal/api/apis_impl.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/discovery/xds/server_test.go
- adapter/internal/discovery/xds/server_utils.go
- adapter/internal/discovery/xds/server_utils_test.go
- adapter/internal/messaging/messaging_test.go
- adapter/internal/messaging/notification_listener.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/model/constants.go
- adapter/internal/synchronizer/apis_fetcher.go
- adapter/pkg/messaging/connection.go
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsUtils.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/dto/JWTTokenPayloadInfo.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/InternalKeyTestCase.java
$subject
Fixes #
Not Tested
---
> Merge Feature branch with Main

- adapter/internal/ga/client.go
The Initial set of APIs should be fetched as a whole rather than having events one by one. 
Fixes #2106
Fixes part of wso2-enterprise/choreo#4332
Not Tested
---
> Implement Fetch APIs Functionality for Global adapter configuration for startup

- enforcer/src/main/resources/Dockerfile
Reverts wso2/product-microgateway#2120
> Revert "Fix #2119 Change enforcer base image to jdk based image"

- adapter/internal/api/apis_impl.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/model/constants.go
Rename WEBSUB type to WEBHOOK type done in these PRs https://github.com/wso2/product-microgateway/pulls?q=is%3Apr+author%3AGDLMadushanka+
https://github.com/wso2-enterprise/choreo/issues/5411
https://github.com/wso2/product-microgateway/issues/2153
Not Tested
---
> Rename Websub to webhook

- distribution/resources/bin/gateway
- distribution/resources/bin/gateway.bat
This PR fixes the issue [1].
[1]. https://github.com/wso2/product-microgateway/issues/2145
Fixes # https://github.com/wso2/product-microgateway/issues/2145
Not Tested
---
> fixed #2145

- components/micro-gateway-core/src/main/ballerina/Ballerina.toml
added missing .jar to ballerina.toml file
Not Tested
---
> fixed by adding .jar extension

- adapter/go.sum
- adapter/internal/adapter/adapter.go
- adapter/internal/eventhub/subscription.go
- adapter/internal/ga/api_event_listener.go
- adapter/internal/ga/client.go
- adapter/internal/ga/client_test.go
- adapter/internal/messaging/notification_listener.go
- adapter/internal/synchronizer/apis_fetcher.go
- adapter/pkg/adapter/adapter.go
- adapter/pkg/health/controlplane.go
- adapter/pkg/synchronizer/apis_fetcher.go
This PR includes:
1. Local Adapter startup and fetching the APIs from the control plane with API UUID list
2. Handling API events received from the GA (Deploying and removing APIs)
Fixes #2132
Fixes https://github.com/wso2-enterprise/choreo/issues/4333
Main Task: https://github.com/wso2-enterprise/choreo/issues/3930
---
> Local Adapter Related Implementation

- adapter/internal/notifier/deployment_notifier.go
Improve logs
Fixes #
Not Tested
---
> [predev] Improve logs

- adapter/internal/notifier/deployment_notifier.go
> [Predev] Fix deployment status retries

- distribution/src/main/assembly/assembly.xml
This PR adds the template configuration file, `config.toml.template` to the built pack.
Fixes #2178 
Not Tested
---
> Add template config file to the distribution pack

- components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
> Cert header validation fix

- adapter/internal/notifier/deployment_notifier.go
Fixes #2181
Related to changes introduced in https://github.com/wso2/carbon-apimgt/pull/10698
Not Tested
---
> Fix deployment status retries

- adapter/internal/adapter/adapter.go
- adapter/internal/messaging/azure_listener.go
- adapter/pkg/messaging/azure_connection.go
This is the initial code segment which reads environment feature flag ('FEAURE_FLAG_REPLACE_EVENT_HUB') and starts going through that flow. This PR is to test that initial flow. See sub task https://github.com/wso2/product-microgateway/issues/2186
Fixes: https://github.com/wso2/product-microgateway/issues/2186
Not Tested
---
> Initial skeleton to test azure event subscription flow

- pom.xml
- Need to add on-prem token hash to the analytics event payload
Fixes https://github.com/wso2/product-microgateway/issues/2189
- Tested
---
Related PRs
- https://github.com/wso2/apim-analytics-publisher/pull/61
> Upgrade analytics publisher version to v1.0.2

- components/micro-gateway-cli/pom.xml
- components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
- distribution/LICENSE-TOOLKIT.txt
- distribution/src/main/assembly/linux_bin.xml
- distribution/src/main/assembly/macos_bin.xml
- distribution/src/main/assembly/windows_bin.xml
- pom.xml
- tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
As $subject, this will fix the cors header issue in token service and OOM issue.
Fixes #2169
Fixes #2165
Not Tested
---
> Ballerina upgrade to 1.2.17

- pom.xml
- Need to handle and re-initialize data publisher if an AMQP authentication exception occurs. 
Fixes https://github.com/wso2/product-microgateway/issues/2197
Tested locally
---
- https://github.com/wso2/apim-analytics-publisher/pull/63
- https://github.com/wso2/apim-analytics-publisher/pull/64
> Upgrade analytics publisher version to v1.0.4

- adapter/internal/ga/client.go
bug fix: avoid panic when the first received xdsResponse is nacked, log improvement such that grpc error code and error message is visible
In addition to that, added a log improvement such that the grpc error code and error message is visible.
Fixes #2201
Not Tested
---
> Avoid possible null pointer exception if grpc resource is not available.

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/messaging/azure_listener.go
- adapter/pkg/messaging/azure_connection.go
- adapter/pkg/messaging/azure_listener.go
- resources/conf/config.toml.template
This PR will improve the subscription logic to handle any connection errors and retry according to the policy
Fixes https://github.com/wso2/product-microgateway/issues/2195
Not Tested
---
> Add connection retry logic for service bus subscription

- components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
Fix error logs when multiple issuers are configured.
Fix https://github.com/wso2/product-microgateway/issues/2191
> Fix error logs when multiple jwt issuers are configured

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/messaging/azure_listener.go
- adapter/pkg/messaging/azure_connection.go
- adapter/pkg/messaging/azure_listener.go
- resources/conf/config.toml.template
$subject
Fixes #
Not Tested
---
> Merge Main branch

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/adapter/adapter.go
- adapter/internal/messaging/azure_listener.go
- adapter/internal/messaging/listener.go
- adapter/internal/messaging/messaging_test.go
- adapter/internal/messaging/notification_listener.go
- adapter/internal/messaging/revoked_token_listener.go
- adapter/pkg/messaging/azure_connection.go
- adapter/pkg/messaging/azure_listener.go
Inject data to correct pipeline and config changes
Fixes https://github.com/wso2/product-microgateway/issues/2217
Not Tested
---
> Add logic to inject data to correct pipeline once consumed from azure service bus

- README.md
- developer-guide.md
Updates for readme files with supported versions.
Below changes are applying with this PR.
---
> Readme file changes for supported versions

- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
- pom.xml
Add `sub` claim to the backend JWT
sample generated backend JWT contains following details:
```
{
"sub": "admin",
"http://wso2.org/claims/apiname": "Test",
"http://wso2.org/claims/applicationtier": "Unlimited",
"http://wso2.org/claims/version": "1.0.0",
"http://wso2.org/claims/keytype": "PRODUCTION",
"iss": "wso2.org/products/am",
"http://wso2.org/claims/applicationname": "DefaultApplication",
"http://wso2.org/claims/enduserTenantId": "0",
"http://wso2.org/claims/applicationUUId": "b94f6c3d-f11b-4390-a9b9-6c7637aabaf7",
"http://wso2.org/claims/subscriber": "admin",
"azp": "4lIYZ4fU3tlUpJT26Q_kZ7RbkmAa",
"http://wso2.org/claims/tier": "Unlimited",
"scope": "default",
"exp": 1632223,
"http://wso2.org/claims/applicationid": "b94f6c3d-f11b-4390-a9b9-6c7637aabaf7", …
```
> Add sub claim to the backend JWT.

- adapter/config/types.go
- adapter/go.sum
- adapter/internal/api/apis_impl.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/interceptor/interceptor.go
- adapter/internal/loggers/logger.go
- adapter/internal/oasparser/config_generator.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/http_filters.go
- adapter/internal/oasparser/envoyconf/internal_dtos.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
- adapter/internal/oasparser/model/constants.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/resource.go
Following interceptor extension is supported
```
x-wso2-request-interceptor:
host: docker.for.mac.localhost 
port: 9040 
urlType: http #optional #http or https
path: /hello #optional
clusterTimeout: 10000 #optional
requestTimeout: 5000 #optional
includes: #optional #can have values "request_headers", "request_body", "request_trailer", "invocation_context"
- "request_body"
- "request_trailers"
x-wso2-response-interceptor:
host: mock.com
port: 9041
includes: #optional #can have values "request_headers", "request_body", "request_trailer", "response_headers", "response_body", "response_trailer", "invocation_context"
- "request_body"
- "request_trailers"
```
Fixes https://github.com/wso2/product-microgateway/issues/2232
Tested locally
---
> Init lua interceptors

- enforcer/pom.xml
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigDefaults.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracerFactory.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracingConstants.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/AzureExporter.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/JaegerExporter.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/ZipkinExporter.java
- enforcer/src/test/java/org/wso2/choreo/connect/enforcer/tracing/exporters/JaegerExporterTest.java
- enforcer/src/test/java/org/wso2/choreo/connect/enforcer/tracing/exporters/ZipkinExporterTest.java
- integration/test-integration/pom.xml
- pom.xml
Add zipkin trace exporter to support tracing through zipkin
Fixes #2234 
Mac docker-compose-with-apim
---
> Add zipkin tracing support

- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
$subject
Fixes #
Not Tested
---
> Prepare for 1.0.0-m1 release

- pom.xml
Make APIM docker-compose docker image version replace with maven project version.
Fixes #
- Unit tests added:No
Local, Mac
---
> Set build version in APIM docker-compose

- enforcer/pom.xml
- pom.xml
azure reactor-core versions conflicts between azure tracer and apim analytics dependencies. temporarily upgrading analytics dependency forcefully here to find a working version.
Fixes #
docker compose setup
---
> Fix app-insights dependency conflits

- adapter/config/default_config.go
- adapter/config/parser.go
- adapter/config/types.go
- adapter/internal/discovery/xds/marshaller.go
- adapter/internal/svcdiscovery/watcher.go
- adapter/pkg/config/parser_test.go
- adapter/scripts/build.sh
- resources/conf/config-for-eventhub.toml
- resources/conf/config.toml
- resources/conf/config.toml.template
- resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
- resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Following set of configurations are updated.
```
enforcer.restServer.enable -> enforcer.restServer.enabled
adapter.consul.enable -> adapter.consul.enabled
enforcer.jwtGenerator.enable -> enforcer.jwtGenerator.enabled
controlPlane.serviceUrl -> controlPlane.serviceURL
globalAdapter.serviceUrl -> globalAdapter.serviceURL
enforcer.throttling.JmsConnectionProviderURL -> enforcer.throttling.JmsConnectionProviderURL
globalAdapter.OverwriteHostName -> globalAdapter.OverrideHostName
enforcer.throttling.publisher.urlGroup -> enforcer.throttling.publisher.URLGroup
```
Fixes #2300 
Not Tested
---
> Refactor configurations with support for old properties

- adapter/internal/eventhub/subscription.go
- adapter/internal/messaging/notification_listener.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracerFactory.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/StoreUtils.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
- integration/test-integration/src/test/resources/apimApisAppsSubs/apis.json
- integration/test-integration/src/test/resources/apimApisAppsSubs/applications.json
- integration/test-integration/src/test/resources/apimApisAppsSubs/subscriptions.json
- integration/test-integration/src/test/resources/testng-cc-with-apim.xml
- Fixes https://github.com/wso2/product-microgateway/issues/2355
- Adds a testcase by updating a testcase that was written to check whether an API exists even after apim restart
- Fixes https://github.com/wso2/product-microgateway/issues/2372
OS name: "linux", arch: "amd64", family: "unix"
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
---
> Fix sandbox endpoint invocation failure with apim

- integration/test-integration/src/main/java/org/wso2/choreo/connect/tests/CustomFilter.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/filter/CustomFilterTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/interceptor/InterceptorRequestFlowTestcase.java
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- integration/test-integration/src/test/resources/openAPIs/intercept_request_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/openAPI.yaml
- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Test dynamic endpoints with custom filters
Fixes https://github.com/wso2/product-microgateway/issues/2378
Docker Compose
---
> Test dynamic endpoints with custom filters

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/StoreUtils.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
- samples/interceptors/.gitignore
- samples/interceptors/README.md
- samples/interceptors/cc-sample-legacy-xml-backend/.gitignore
- samples/interceptors/cc-sample-xml-interceptor/.gitignore
- samples/interceptors/cc-sample-xml-interceptor/interceptor-service-open-api_service.bal
- samples/interceptors/create-interceptor-certs.sh
Fixes #2369 
Fixes #2385 
Not Tested
---
> Update getToken method in tests and Update interceptor sample readme, crt location

- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Updating minimum cpu and memory in cc
Update xms/x in enforcer
Fixed https://github.com/wso2/product-microgateway/issues/2380
Not Tested
---
> Updating minimum cpu and memory in cc

- adapter/internal/api/apis_impl.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/types.go
- adapter/internal/synchronizer/apis_fetcher.go
- adapter/pkg/synchronizer/apis_fetcher.go
- adapter/pkg/synchronizer/types.go
To test the PR https://github.com/wso2/product-microgateway/pull/2375 in predev
Fixes #
Not Tested
---
> [predev] support env labels properties

- adapter/internal/ga/client.go
$subject
Fixes #2414 
Not Tested
---
> bug fix: GA connection fails as overwritehostname property is not replaced.

- adapter/internal/discovery/xds/consul.go
- adapter/internal/svcdiscovery/client.go
- adapter/internal/svcdiscovery/watcher.go
- resources/conf/config.toml.template
Fixed the following issues identified in Consul service discovery.
1. ACL token not used properly
2. Certs are missing when working with Consul service mesh
Fixes https://github.com/wso2/product-microgateway/issues/2409
Not Tested
---
> Fixing consul service mesh issues

- adapter/internal/ga/client.go
$subject. 
Fixes #2414 
Not Tested
---
> bug fix: Override hostname is not properly replaced. Hence GA connection fails

- adapter/pkg/synchronizer/types.go
Update alias name from production_endpoint to productionEndpoint and sandbox_endpoint to sandboxEndpoint in environment label specific variable support.
Fixes https://github.com/wso2/product-microgateway/issues/2420
Tested
---
> update alias name

- adapter/internal/oasparser/model/constants.go
- adapter/internal/oasparser/model/mgw_swagger.go
- integration/test-integration/src/test/resources/openAPIs/intercept_request_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/intercept_response_openAPI.yaml
- samples/interceptors/bookstore-api.yaml
support `serviceURL` option and remove host, port, scheme
```
x-wso2-request-interceptor:
serviceURL: https://xml-interceptor:9081
includes:
- request_body
```
Fixes https://github.com/wso2/product-microgateway/issues/2417
- Integration tests added: Yes (existing tests covers the changes)
Tested
---
> Improve interceptor extension

- samples/filters/sample-filter/README.md
- samples/filters/sample-filter/pom.xml
- samples/filters/sample-filter/src/main/java/sample/filter/CustomFilter.java
- samples/filters/sample-filter/src/main/resources/META-INF/services/org.wso2.choreo.connect.enforcer.commons.Filter
$subject
Fixes #2260  
Fixes #2428
Not Tested
---
> Add samples for custom filters

- integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- resources/docker-compose/apim/docker-compose.yaml
Fixes https://github.com/wso2/product-microgateway/issues/2269
Fixes #
Not Tested
---
> Updating docker compose version from v2 to v3

- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
- adapter/internal/oasparser/model/constants.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/mgw_swagger_internal_test.go
- adapter/internal/oasparser/model/open_api.go
- adapter/internal/oasparser/model/resource.go
- adapter/internal/oasparser/model/swagger.go
- adapter/test-resources/envoycodegen/openapi_with_endpoint_ref.yaml
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/ProductionSandboxTestCase.java
- integration/test-integration/src/test/resources/openAPIs/endpoint_ref_openAPI.yaml
Fixes https://github.com/wso2/product-microgateway/issues/2344
- Integration tests added: Yes - but cannot enable due to this issue https://github.com/wso2/product-apim-tooling/issues/821
Tested on catalina
---
> Add support for referenced endpoints object

- adapter/go.sum
- adapter/internal/discovery/xds/marshaller.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/eventhub/subscription.go
- adapter/internal/ga/api_event_listener.go
- adapter/internal/messaging/notification_listener.go
Prevent memory usage spikes when an event is received from message broker. 
See the issue for more details.
Fixes #2401 
- Integration tests added: No (Already covered with available set of tests)
Not Tested
---
> Improve memory utilization for Applications

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/Utils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketMetaDataFilter.java
$subject.
The Async API support is not there in the Choreo Connect now. In addition, having several topics under a single websocketAPI is also not supported at the moment. 
Fixes #2411 
Not Tested
---
> Bug-Fix: [Websocket] Fix Null pointer issues popped during websocket APIs Invocation

- adapter/internal/oasparser/config_generator.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/listener.go
- enforcer-parent/enforcer/pom.xml
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/interceptors/OpenTelemetryInterceptor.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/AuthServer.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracerFactory.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracingConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracingContextHolder.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/Utils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/AzureExporter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/JaegerExporter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/ZipkinExporter.java
- enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/tracing/exporters/JaegerExporterTest.java
- enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/tracing/exporters/ZipkinExporterTest.java
- pom.xml
This will enable router and enforcer both publish traces under same parent span.
Fixes #2426
Not Tested
---
> Enable tracing for router

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/EndpointSecurityUtils.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/dto/Api.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BackendSecurityTestCase.java
- integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Fixes https://github.com/wso2/product-microgateway/issues/2350
Tested
---
> Fix backend basic auth security

- resources/conf/config.toml
- resources/conf/config.toml.template
Fixes https://github.com/wso2/product-microgateway/issues/2426
Not Tested
---
> Updating config.toml template for tracing

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/EndpointSecurityUtils.java
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BackendSecurityTestCase.java
Fixes https://github.com/wso2/product-microgateway/issues/2454
- Integration tests added: yes
ubuntu
---
> Fix no security basic auth backend

- enforcer-parent/enforcer/src/main/resources/Dockerfile
Update enforcer JDK 11 docker image
Task
Not Tested
---
> Update enforcer JDK 11 docker image

- adapter/src/main/resources/Dockerfile
Adapter base image update
Task
Not Tested
---
> Adapter base image update

- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- release-note.html
- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
> Prepare for 1.0.0-beta release

- adapter/internal/discovery/xds/server.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithMultipleEnv.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
- integration/test-integration/src/test/resources/configs/multiple-env-config.toml
- integration/test-integration/src/test/resources/deploymentEnvironments/apictl_test_deploy_multiple_env.yaml
- integration/test-integration/src/test/resources/testng-cc-standalone.xml
$subject happens when the following conditions are met.
API is deployed in multiple gateway environments.
API deployment within one gateway environment has two vhosts.
When the API is deployed from specific host under specific gateway environment, the issue occurs.
refer to the issue for more information.
Fixes #2451
FIxes #2448
Not Tested
---
> Bug-fix [Vhost] Resolve issue where APIs are not properly undeployed from specific host under specific environment.

- adapter/go.sum
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/mgw_swagger_internal_test.go
$subject
Fixes #2400
Not Tested
---
> Add basepath validation

- adapter/go.sum
- adapter/internal/adapter/adapter.go
- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Fixes https://github.com/wso2/product-microgateway/issues/2475
Not Tested
---
> Fixing Channel issue

- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
- adapter/internal/oasparser/model/api_env.go
- adapter/internal/oasparser/model/api_yaml.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/types.go
This will fix the issue when endpoint is quoted in env variable.
It will remove the constraint of having to override both production and sandbox together using the environment variables
This will change the priority of selected endpoints as the following order; environment variable will have the highest priority.
1. endpoints given using environment variable
2. endpoints in gw label specific variables
3. endpoints given in swagger vendor extension
4. endpoints given in swagger servers
Fixes https://github.com/wso2/product-microgateway/issues/2446
ubuntu
---
> Override endpoints using environment variables

- adapter/internal/api/apis_impl.go
To address the review comments that are added to [1].
1. https://github.com/wso2/product-microgateway/pull/2103
Fixes #
Not Tested
---
> Fix minor formatting issues

- adapter/internal/oasparser/operator/operator.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/PublisherUtils.java
- Use provided method to directly access resource config and remove loop when adding retry and timeout configs
- Remove additional pointer
- Improve integration test util methods
Fixes https://github.com/wso2/product-microgateway/issues/2480
Not Tested
---
> Use provided method to directly access resource config and remove loop

- README.md
> Updating root readme

- .trivyignore
- adapter/internal/oasparser/envoyconf/listener.go
- enforcer-parent/enforcer/pom.xml
- pom.xml
- resources/conf/config.toml.template
Fixes https://github.com/wso2/product-microgateway/issues/2262
Verified Jaeger, Azure tracing
Verified Analytics.
Fixes #
Not Tested
---
> Updating azure tracing for beta 5

- adapter/internal/discovery/xds/server.go
Fixes error when un-deploying an API deployed to multiple labels through APICTL.
Fixes https://github.com/wso2/product-microgateway/issues/2363
---
> [bug-fix] Fixes un-deploying an API deployed to multiple labels form APICTL

- adapter/internal/oasparser/model/open_api.go
- adapter/internal/oasparser/model/resource.go
- adapter/internal/oasparser/model/swagger.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- integration/test-integration/src/test/resources/openAPIs/cors_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/deploy_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/global_cors_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/mtls_from_router_to_backend_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/security_openAPI.yaml
Fixes https://github.com/wso2/product-microgateway/issues/2498
Not Tested
---
> Fix apictl jwt disabling

- adapter/scripts/build.sh
- adapter/src/main/assembly/assembly.xml
- adapter/src/main/resources/Dockerfile
- adapter/src/main/resources/Dockerfile.ubuntu
- build-ubuntu-multi-platform-images.sh
- enforcer-parent/enforcer/src/main/resources/Dockerfile
- enforcer-parent/enforcer/src/main/resources/Dockerfile.ubuntu
- router/src/main/resources/Dockerfile
- router/src/main/resources/Dockerfile.ubuntu
Build adapter arm64 binary for and update Dockerfiles with the maintainer
Related to #2412
Tested QSG in Mac M1 (ARM based) for ubuntu ARM64 images
Run integration tests for Ubuntu AMD64 images
---
> Build adapter arm64 binary and update Dockerfiles

- adapter/internal/oasparser/model/api_env.go
Fixes https://github.com/wso2/product-microgateway/issues/2446
Fixes #
Not Tested
---
> Fixing envs for credentials

- adapter/internal/discovery/xds/marshaller.go
- adapter/internal/eventhub/subscription.go
> Bug fix: APIList is not updated after the startup

- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/config_generator.go
- adapter/internal/oasparser/model/api_env.go
- adapter/internal/oasparser/model/constants.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/types.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendSandbox.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/circuitBreakers/CircuitBreakersTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/BackendSecurityTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BackendSecurityTestCase.java
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- integration/test-integration/src/test/resources/openAPIs/backend_security_openAPI.yaml
- integration/test-integration/src/test/resources/testng-cc-standalone.xml
1. added extension support for endpoint security config. 
2. added test cases covering scenarios related to endpoint basic auth security.
Fixes https://github.com/wso2/product-microgateway/issues/1945
Tested
---
> Read securityconfig from extension

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
$subject
Fixes #2520 
Not Tested
---
> bug fix: Websocket APIs cannot be invoked due to null pointer exception

- enforcer-parent/enforcer/src/main/assembly/assembly.xml
- enforcer-parent/enforcer/src/main/resources/Dockerfile
- enforcer-parent/enforcer/src/main/resources/Dockerfile.ubuntu
Enforcer was packaing some unwanted files into it's docker image and this PR will remove those files.
Task
standalone docker-compose
---
> Remove unwanted files from enforcer

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/databridge/agent/DataPublisher.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/databridge/agent/endpoint/DataEndpointGroup.java
- integration/test-integration/src/test/resources/configs/cc-special-scenarios-with-apim.toml
Implement the same changes introduced to ballerina microgateway from https://github.com/wso2/product-microgateway/pull/2216
Fixes #2521 
Not Tested
---
> improvement: allow throttling data publishing via SSL connection

- enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/AuthenticationContext.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/MetadataConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/dto/APIKeyValidationInfoDTO.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/WebSocketHandler.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleDataHolder.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/MetadataConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketMetaDataFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketThrottleFilter.java
> Bug fix: Use API-ID instead of APIUUID for throttle data publishing

- adapter/internal/api/apis_impl.go
There can be api projects which doesn't specify the env to deploy the API. We deploy these APIs to default env.
Fixes #2522
docker-compose
---
> Deploy to default env when env not specified

- samples/istio/sidecar-mode/README.md
> Updating Istio sample readme

- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- release-note.html
- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Prepare for 1.0.0-rc1 release
Task
Not Tested
---
> Prepare for 1.0.0-rc1 release

- build-ubuntu-multi-platform-images.sh
> Set MVN_PROJECT_VERSION as second param for ubuntu image build

- enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/APIConfig.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/APIFactory.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/JwtTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/ScopeTest.java
- integration/test-integration/src/test/resources/openAPIs/scopes_openAPI.yaml
Fixes https://github.com/wso2/product-microgateway/issues/2534
ubuntu
---
> Fix api level scope validation

- build-ubuntu-multi-platform-images.sh
Ubuntu image build - Add QEMU user mode emulation binaries for ARM64 image build in AMD64
Dockerhub: https://hub.docker.com/r/multiarch/qemu-user-static/tags
Github: https://github.com/multiarch/qemu-user-static
Task
Not Tested
---
> Ubuntu image build - Add QEMU user mode emulation binaries for ARM64 image build in AMD64

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/ApimResourceProcessor.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/PublisherUtils.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BasicEventsTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
Refactor test utils and add the following tests for APIM mode
- undeploy
- redeploy
- add new resource
- delete new resource
and add autogen test file changes.
Fixes https://github.com/wso2/product-microgateway/issues/2547
Not Tested
---
> int-tests: Test apim mode undeploy, new resource, and delete resource

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/ScopeTest.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/jwtValidator/JwtAndScopeTestCase.java
- integration/test-integration/src/test/resources/openAPIs/scopes_openAPI.yaml
- integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Adding integration tests for jwt and scopes for apim super tenant
Fixes #
Ubuntu
---
> Add scope integration tests

- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/open_api.go
Fixes https://github.com/wso2/product-microgateway/issues/2546
Not Tested
---
> Fix consul

- adapter/internal/oasparser/model/mgw_swagger.go
- integration/test-integration/src/test/resources/openAPIs/sand_openAPI.yaml
Fixes https://github.com/wso2/product-microgateway/issues/2542
- Integration tests added: Yes. modified existing test case to catch this issue
Not Tested
---
> Fix sandbox only API

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendSandbox.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/ProductionSandboxTestCase.java
- integration/test-integration/src/test/resources/openAPIs/prod_and_sand_openAPI.yaml
Fixes https://github.com/wso2/product-microgateway/issues/2553
Ubuntu
---
> Setting resource specific basepath

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/AuthenticatorUtils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
> Bug fix: API-Key subscription throttling does not work

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/model/open_api.go
- adapter/internal/oasparser/model/swagger.go
Fixes https://github.com/wso2/product-microgateway/issues/2558
Not Tested
---
> Swagger servers should set only as production endpoints

- router/src/main/resources/interceptor/lib/interceptor.lua
- router/src/main/resources/interceptor/lib/utils.lua
$subject
Fixes https://github.com/wso2/product-microgateway/issues/2566
Not Tested
---
> Fix issue setting body from interceptor when body is empty from client or backend

- release-note.html
> Prepare for 1.0.0-rc2 release

- release-note.html
- resources/license/LICENSE-ENFORCER.txt
related to #2565 and #2568
Task
Not Tested
---
> Update dependency versions of LICENSE-ENFORCER.txt

- samples/openAPI-definitions/cors_sample.yaml
- samples/openAPI-definitions/endpoint_by_reference_sample.yaml
- samples/openAPI-definitions/interceptors_sample.yaml
- samples/openAPI-definitions/petstore_basic.yaml
- samples/openAPI-definitions/policies_sample.yaml
- samples/openAPI-definitions/security_sample.yaml
Adds sample yaml files to the main branch. These files will be referred from APIM-docs repo.
N/A
Fixes #
Not Tested
---
> Sample yaml files in main branch

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithMultipleEnv.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/QSGAndSwaggerTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/filter/CustomFilterTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/CustomJwtTransformerTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/JwtGeneratorTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/JwtTransformerTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/InternalKeyTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/JwtTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/ScopeTest.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/mtls/MtlsFromRouterToBackendTestcase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/CorsTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TokenUtil.java
- integration/test-integration/src/test/resources/openAPIs/mtls_from_router_to_backend_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/openAPI.yaml
> Fix Integration test failure in Qsgtestcase due to basepath conflict

- adapter/pom.xml
- distribution/pom.xml
- enforcer-parent/commons/pom.xml
- enforcer-parent/enforcer/pom.xml
- enforcer-parent/pom.xml
- integration/mock-backend-server/pom.xml
- integration/pom.xml
- integration/test-integration/pom.xml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- pom.xml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
- router/pom.xml
> Set next development iteration as 1.1.0-m1-SNAPSHOT

- pom.xml
Reverts wso2/product-microgateway#2585
> Revert "Bump log4j-core from 2.15.0 to 2.16.0"

- adapter/pom.xml
- distribution/pom.xml
- enforcer-parent/commons/pom.xml
- enforcer-parent/enforcer/pom.xml
- enforcer-parent/pom.xml
- integration/mock-backend-server/pom.xml
- integration/pom.xml
- integration/test-integration/pom.xml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- pom.xml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
- router/pom.xml
Reverts wso2/product-microgateway#2586
> Revert "Set next development iteration as 1.1.0-m1-SNAPSHOT"

- adapter/pom.xml
- distribution/pom.xml
- enforcer-parent/commons/pom.xml
- enforcer-parent/enforcer/pom.xml
- enforcer-parent/pom.xml
- integration/mock-backend-server/pom.xml
- integration/pom.xml
- integration/test-integration/pom.xml
- pom.xml
- router/pom.xml
$subject
Task
TODO: choreo branch is not fast forward now, it should be delete and re created form main later (after release 1.0.0)
Made PR to track history
Not Tested
---
> Update choreo after 1.0.0 RC2

- adapter/pom.xml
- distribution/pom.xml
- enforcer-parent/commons/pom.xml
- enforcer-parent/enforcer/pom.xml
- enforcer-parent/pom.xml
- integration/mock-backend-server/pom.xml
- integration/pom.xml
- integration/test-integration/pom.xml
- pom.xml
- router/pom.xml
- samples/filters/sample-filter/pom.xml
Change group id to `org.wso2.choreo.connect` (from `org.wso2.am.choreo.connect`)
Fixes #
Not Tested
---
> Refactor group ID for choreo-connect artifacts

- components/micro-gateway-core/src/main/ballerina/Ballerina.toml
- pom.xml
Upgrade log4j version to 2.16.0.
Log4j security vulnarability
> Upgrade log4j version

- adapter/internal/ga/client.go
Fixes: https://github.com/wso2/product-microgateway/issues/2576
Not Tested
---
> Fixing a goroutine creation for handling API events from GA .

- components/micro-gateway-core/src/main/ballerina/Ballerina.toml
- pom.xml
Upgrade log4j version to 2.17.0
> Upgrade log4j version to 2.17.0

- pom.xml
Bump log4j-api from 2.16.0 to 2.17.1
Task
Not Tested
---
> Bump log4j-api from 2.16.0 to 2.17.1

- integration/mock-backend-server/pom.xml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- release-note.html
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Prepare for 1.0.0-rc3 release
Task
Not Tested
---
> Prepare for 1.0.0-rc3 release

- adapter/pom.xml
- distribution/pom.xml
- enforcer-parent/commons/pom.xml
- enforcer-parent/enforcer/pom.xml
- enforcer-parent/pom.xml
- integration/mock-backend-server/pom.xml
- integration/pom.xml
- integration/test-integration/pom.xml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- pom.xml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
- router/pom.xml
Prepare for next development iteration - 1.1.0-m1-SNAPSHOT
Task
Not Tested
---
> Prepare for next development iteration - 1.1.0-m1-SNAPSHOT

- adapter/internal/interceptor/interceptor.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/internal_dtos.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/model/api_operation.go
- adapter/internal/oasparser/model/constants.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/open_api_internal_test.go
- adapter/internal/oasparser/model/swagger_internal_test.go
- integration/test-integration/src/test/resources/openAPIs/intercept_request_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/intercept_response_openAPI.yaml
- router/src/main/resources/interceptor/lib/interceptor.lua
Fixes https://github.com/wso2/product-microgateway/issues/2606
Tested
---
> Add operation level interceptor support

- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/endpoint/DataEndpointGroup.java
This PR fixes the issue of SSL binary throttle events stop publishing to traffic manager sometime after MGW is started.
Fixes https://github.com/wso2/product-microgateway/issues/2573
Not Tested
---
> Resolve issue with SSL Binary Throttle Data Publishing

- .maven/settings.xml
$subject
Fixes #
Not Tested
---
> Update maven settings.xml

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/MediationPolicyFilter.java
rename header should rename the header which is not equal to modifying the header.
Fixes https://github.com/wso2/product-microgateway/issues/2638
Not Tested
---
> Fix rename header policy

- pom.xml
This PR upgrades ballerina version to 1.2.24.
Fixes https://github.com/wso2/product-microgateway/issues/2617
---
> [3.2.x] Upgrade ballerina version to 1.2.24

- pom.xml
> Upgrade grpc.protobuf.version

- adapter/internal/api/apis_impl.go
- adapter/internal/discovery/xds/server.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/APiDeployViaApictlTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
$subject
Fixes https://github.com/wso2/product-microgateway/issues/2583
Not Tested
---
> Fix being able to override an API without the override flag via apictl

- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
$subject
N/A
Fixes #
Not Tested
---
> Preparations for 1.1.0-m1 release

- adapter/internal/api/apis_process.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/constants/constants.go
- adapter/internal/oasparser/model/api_yaml.go
- adapter/internal/oasparser/model/async_api.go
- adapter/internal/oasparser/model/async_api_test.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/project_structs.go
- adapter/internal/oasparser/operator/operator.go
- adapter/internal/oasparser/operator/operator_test.go
- adapter/internal/oasparser/utills/open_api_utills_test.go
- adapter/internal/oasparser/utills/open_api_utils.go
- adapter/test-resources/envoycodegen/asyncapi_websocket.yaml
$subject
Fixes https://github.com/wso2/product-microgateway/issues/2609
Not Tested
---
> Add adapter side AsyncAPI implementation

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/RetryAndTimeoutTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/apikey/APIKeyAppLevelThrottleTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/apikey/APIKeyBlockedAPITestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/apikey/APIKeyTestCase.java
- integration/test-integration/src/test/resources/apim/1/apiToOpenAPI.json
- integration/test-integration/src/test/resources/apim/1/apis/APIKeyAppLevelThrottleAPI.json
- integration/test-integration/src/test/resources/apim/1/apis/APIKeyBlockedAPI.json
- integration/test-integration/src/test/resources/apim/1/apis/APIKeyTestAPI.json
- integration/test-integration/src/test/resources/apim/1/apis/RetryAPI.json
- integration/test-integration/src/test/resources/apim/1/apis/TimeoutAPI.json
- integration/test-integration/src/test/resources/apim/1/apps/applications.json
- integration/test-integration/src/test/resources/apim/1/subscriptions/subscriptions.json
- integration/test-integration/src/test/resources/openAPIs/api_key_blocked_openAPI.yaml
$subject
Fixes https://github.com/wso2/product-microgateway/issues/2622
Related to https://github.com/wso2/product-microgateway/issues/2623
Not Tested
---
> int-tests: withapim: Update API Key, retry and timout tests to deploy APIs via JSON

- adapter/pkg/messaging/azure_listener.go
- adapter/scripts/build.sh
- adapter/src/main/resources/Dockerfile
- adapter/src/main/resources/Dockerfile.ubuntu
Adds some debug tags and log fixes to debug go-amqp.
Fixes #2657 
Not Tested
---
> Adapter changes for debugging go-amqp library

- adapter/config/logger.go
- adapter/config/parser.go
- adapter/internal/adapter/adapter.go
- adapter/internal/api/apis_impl.go
- adapter/internal/api/apis_process.go
- adapter/internal/api/restserver/config_restapi.go
- adapter/internal/auth/auth.go
- adapter/internal/discovery/xds/consul.go
- adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
- adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/eventhub/subscription.go
- adapter/internal/ga/client.go
- adapter/internal/interceptor/interceptor.go
- adapter/internal/messaging/km_listener.go
- adapter/internal/messaging/notification_listener.go
- adapter/internal/notifier/deployment_notifier.go
- adapter/internal/oasparser/envoyconf/access_loggers.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/pkg/logging/log_format.go
- adapter/pkg/logging/logging_internal_test.go
- adapter/pkg/logging/package_logs.go
This PR will refactor some error log statements in adapter, according to the formal logging introduced in https://github.com/wso2/product-microgateway/issues/2422
Fixes #
Not Tested
---
> Refactor error logs in adapter

- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
$subject
N/A
Fixes #
Not Tested
---
> Preparations for 1.1.0-m2 release

- adapter/internal/api/apis_process.go
- adapter/internal/oasparser/model/api_yaml.go
- adapter/internal/oasparser/model/policy_container.go
$subject
related to https://github.com/wso2/product-microgateway/pull/2656
Task
Not Tested
---
> Fix review comments - Operational Policies

- enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/logging/ErrorDetails.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AccessLoggingService.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/keymgt/KeyManagerHolder.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyHandler.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/AuthServer.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleEventListener.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/databridge/publisher/ThrottleDataPublisher.java
This PR will refactor some error log statements in enforcer, according to the formal logging introduced in https://github.com/wso2/product-microgateway/issues/2422
Fixes #2669 
Not Tested
---
> Refactor error logs in enforcer

- enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/logging/CustomJsonLayout.java
- enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/logging/LoggingConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/HttpRequestHandler.java
- resources/conf/log4j2.properties
This PR adds the following information to related logs in the request path of the enforcer.
- API Name
- Organization Id
- API base path
Fixes #2680 
Tested locally with docker-compose 
OS : Ubuntu 20.04
JDK 11
---
> Add correlation logs to enforcer

- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
$subject
N/A
Fixes #
Not Tested
---
> Preparations for 1.1.0-m3 release

- integration/test-integration/src/test/resources/dockerCompose/git-service.yaml
Updating gitlab docker image from enterprise edition to community edition used in integration tests for the sourcewatcher.
Not Tested
---
> Update gitlab docker image

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- resources/conf/config.toml.template
Fixes https://github.com/wso2/product-microgateway/issues/2699
Not Tested
---
> Improve DNS resolving rate

- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- pom.xml
- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
$subject
N/A
Fixes #
Not Tested
---
> Preparations for 1.1.0-m4 release 

- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/utills/open_api_utils.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
$subject
Fixes #
Not Tested
---
> Update log messages to include their severity levels.

- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
$subject
N/A
Fixes #
Not Tested
---
> Preparations for 1.1.0-alpha release

- adapter/internal/oasparser/model/policy_container.go
- enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/opa/OPAConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/opa/OPADefaultRequestGenerator.java
$subject
send additional properties to OPA server
Related to https://github.com/wso2/product-microgateway/issues/2710
Not Tested
---
> OPA - Send token only if "sendAccessToken" is configured

- adapter/pom.xml
- distribution/pom.xml
- enforcer-parent/commons/pom.xml
- enforcer-parent/enforcer/pom.xml
- enforcer-parent/pom.xml
- integration/mock-backend-server/pom.xml
- integration/pom.xml
- integration/test-integration/pom.xml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- pom.xml
- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
- router/pom.xml
$subject
Fixes #
Not Tested
---
> Change dev version from beta to alpha2

- adapter/go.mod
- adapter/go.sum
> Update azure-sdk-for-go asb client to 0.3.6

- adapter/pkg/messaging/azure_listener.go
> [debug/choreo-ga] Improve ASB logs

- adapter/internal/oasparser/model/async_api.go
- adapter/internal/oasparser/model/mgw_swagger.go
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/async/MockAsyncServer.java
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/async/websocket/WsServerFrameHandler.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/WebSocketBasicTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/WebSocketSecurityDisabledTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/websocket/WsClient.java
- integration/test-integration/src/test/resources/apim/1/apiToAsyncAPI.json
- integration/test-integration/src/test/resources/apim/1/apis/WebSocketSecurityDisabledAPI.json
- integration/test-integration/src/test/resources/asyncAPIs/websocket_security_disabled_asyncAPI.yaml
- integration/test-integration/src/test/resources/testng-cc-with-apim.xml
$subject
Fixes https://github.com/wso2/product-microgateway/issues/2708
Not Tested
---
> Fix disable security for AsyncAPI and add a testcase

- router/src/main/resources/Dockerfile
- router/src/main/resources/Dockerfile.ubuntu
$subject
Fixes https://github.com/wso2/product-microgateway/issues/2738
Not Tested
---
> Update router envoyproxy version to v1.20.2

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Fixes wso2/product-microgateway#2734
- Integration tests added: No (will be added)
Tested with integration test mock backend interceptor service
---
> Fix interceptor cluster name issue when apply with API Policies

- adapter/internal/messaging/notification_listener.go
There will be a new event for health check of GA ( based of event receiving count). No need any processes for health check event, so added another block for filtering POLICY events for ignore the health check events.
Fixes https://github.com/wso2/product-microgateway/issues/2747
---
> Add condition for filter policy events

- adapter/src/main/resources/Dockerfile
- enforcer-parent/enforcer/src/main/resources/Dockerfile
This PR upgrades base image versions in adapter and enforcer.
Fixes # N/A
Not Tested
---
> Base image version upgrade

- adapter/internal/oasparser/model/policy_container.go
$subject
Fix https://github.com/wso2/product-microgateway/pull/2754#discussion_r830868621
Not Tested
---
> Fix abbreviated variable name - policyFullName

- adapter/pkg/messaging/azure_listener.go
Improve ASB notification related logs
Fixes #
Not Tested
---
> Improve ASB logs

- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- remove-containers.sh
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
$subject
Fixes #
Not Tested
---
> Preparations for 1.1.0-beta release

- integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
- pom.xml
- resources/docker-compose/apim/docker-compose.yaml
- resources/k8s-artifacts/apim/apim-deployment.yaml
$subject
Fixes #
Not Tested
---
> Addition of control plane profile to the docker compose

- pom.xml
Subject
* https://github.com/wso2/product-microgateway/issues/2726
> Bumping ballerina version to 1.2.26

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/InterceptorWithMtlsTestCase.java
- integration/test-integration/src/test/resources/openAPIs/intercept_request_path_level_openAPI.yaml
Update InterceptorWithMtlsTestCase to include both header and reqBody update
Fixes #
Not Tested
---
> [int-tests] Update Interceptor test to include both header and reqBody update

- adapter/src/main/resources/Dockerfile
$subject
Fixes #
Not Tested
---
> Upgrade alpine image version in adapter

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/interceptor/InterceptorRequestFlowTestcase.java
Test for empty requests from clients and interceptor service update (add) a new body.
Fixes https://github.com/wso2/product-microgateway/issues/2571
- Unit tests added:No
From integration tests
---
> Add integration test for empty client request and update body from interceptor service

- resources/k8s-artifacts/apim/apim-config.yaml
- resources/k8s-artifacts/apim/apim-service.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-with-apim-ingress.yaml
- resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
- resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
- samples/istio/mtls-mode/README.md
- samples/istio/mtls-mode/gw_vs.yaml
- samples/istio/sidecar-mode/README.md
- samples/istio/sidecar-mode/gw_vs.yaml
Fixes https://github.com/wso2/product-microgateway/issues/2795
Not Tested
---
> Updating APIM hostname

- .trivyignore
Fixes https://github.com/wso2/product-microgateway/issues/2773
Not Tested
---
> Updated jackson version. Hence deleting trivy entry

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/CcStartupExecutorTwo.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/WebSocketScopeTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/websocket/WebSocketTimeoutTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/websocket/WsClient.java
- integration/test-integration/src/test/resources/apim/2/apiToAsyncAPI.json
- integration/test-integration/src/test/resources/apim/2/apis/WebSocketScopeAPI.json
- integration/test-integration/src/test/resources/apim/2/apis/WebSocketTimeoutAPI.json
- integration/test-integration/src/test/resources/apim/2/apps/applications.json
- integration/test-integration/src/test/resources/apim/2/subscriptions/subscriptions.json
- integration/test-integration/src/test/resources/asyncAPIs/websocket_scope_asyncAPI.yaml
- integration/test-integration/src/test/resources/configs/cc-special-scenarios-with-apim.toml
- integration/test-integration/src/test/resources/testng-cc-with-apim.xml
$subject
Fixes https://github.com/wso2/product-microgateway/issues/2695
Not Tested
---
> [int-tests] Add websocket topic oauth scope test and idle timeout test

- README.md
- integration/test-integration/src/test/resources/configs/vhost-deployment.toml
- resources/docker-compose/apim/conf/deployment.toml
- resources/k8s-artifacts/apim/apim-config.yaml
$subject
Fixes https://github.com/wso2/product-microgateway/issues/2803
Not Tested
---
> Readme Update and APIM server role change to CP

- pom.xml
$subject
Fixes #
Not Tested
---
> Updating apictl version to 4.1.0-rc1

- integration/test-integration/src/test/resources/openAPIs/api_policy_intercept_request_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/api_policy_intercept_response_openAPI.yaml
$subject
Fix wso2/product-microgateway#2755
Tested with config dump
---
> Test when interceptor service applied from both vendor extension and from API policy

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/FaultCodeClassifier.java
$subject
Fixes https://github.com/wso2/product-microgateway/issues/2771
Tested with APICTL
---
> Handle analytics when OPA forbidden and when internal server with OPA

- resources/conf/config-for-eventhub.toml
- resources/docker-compose/apim/conf/deployment.toml
- resources/docker-compose/apim/docker-compose.yaml
Fixes https://github.com/wso2/product-microgateway/issues/2812
Not Tested
---
> Changing APIM port from 9443 to 9444

- .github/workflows/main.yml
Check any proto gen related changes when checking PRs.
Task
Tested in GitHub Action of folk repo
---
> Check proto-gen changes in PR Check pipeline

- resources/license/LICENSE-ENFORCER.txt
This PR updates enforcer license text to match with CC 1.1.0 release
N/A
Fixes #
Not Tested
---
> [1.1.0] Updated enforcer license text 

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/WebSocketFrameService.java
- envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.cc
$subject
Fixes https://github.com/wso2/product-microgateway/issues/2797
Not Tested
---
> Fix StatusRuntimeException cancelled before receiving half close

- adapter/internal/oasparser/model/api_yaml.go
$subject
Related to https://github.com/wso2/product-microgateway/issues/2677
Not Tested
---
> Remove webhook and SSE from supported API types

- adapter/internal/api/apis_impl.go
- adapter/internal/api/restserver/config_restapi.go
$subject
Fixes #2244 
Not Tested
---
> Return error right at the beginning for apictl deploy/undeploy commands when control plane is enabled

- integration/test-integration/src/main/java/org/wso2/choreo/connect/tests/CustomOPARequestGenerator.java
- integration/test-integration/src/main/resources/META-INF/services/org.wso2.choreo.connect.enforcer.commons.opa.OPARequestGenerator
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/ChoreoConnectImpl.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithBackendTlsAndCorsDisabledWithOPA.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
- integration/test-integration/src/test/resources/apiYaml/api_policies.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls-with-opa-server.yaml
- integration/test-integration/src/test/resources/dockerVolumeMounts/opa-volume/policies/custom-policy.rego
- integration/test-integration/src/test/resources/openAPIs/api_policy_openAPI.yaml
- integration/test-integration/src/test/resources/policies/customOpaPolicy_v1.gotmpl
- integration/test-integration/src/test/resources/policies/customOpaPolicy_v1.yaml
- integration/test-integration/src/test/resources/policies/customOpaPolicy_v2.gotmpl
- integration/test-integration/src/test/resources/policies/customOpaPolicy_v2.yaml
> Add integration tests for custom OPA request generator

- adapter/internal/discovery/xds/server.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
Fixes https://github.com/wso2/product-microgateway/issues/2847
Not Tested
---
> Fixing API delete issue in standalone mode

- adapter/internal/sourcewatcher/sourcewatcher.go
$subject
Fix https://github.com/wso2/product-microgateway/issues/2845
Not Tested
---
> Handle error when pulling from remote and format code

- samples/filters/sample-filter/pom.xml
$subject is added as wso2_public maven repository's 1.1.0 enforcer artifacts are not synced with maven central repository.
Fixes #
Not Tested
---
> Update Sample Filter to add wso2_public maven repository.

- samples/filters/sample-filter/pom.xml
> Revert "Update Sample Filter to add wso2_public maven repository."

- adapter/pom.xml
- distribution/pom.xml
- enforcer-parent/commons/pom.xml
- enforcer-parent/enforcer/pom.xml
- enforcer-parent/pom.xml
- integration/mock-backend-server/pom.xml
- integration/pom.xml
- integration/test-integration/pom.xml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls-with-opa-server.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- pom.xml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
- router/pom.xml
$subject
Fixes #
Not Tested
---
> Version name changes relevant to the 1.2.0 m1 release

- resources/k8s-artifacts/choreo-connect/log4j2-configmap.yaml
- resources/k8s-artifacts/choreo-connect/logconfig-toml-configmap.yaml
$subject Related to wso2/product-microgateway#2633
Task
Not Tested
---
> Update k8s config changes for log configs

- adapter/internal/oasparser/model/resource.go
- integration/test-integration/src/test/resources/apiYaml/api_policies.yaml
- samples/filters/sample-filter/pom.xml
$subject
Fix https://github.com/wso2/product-microgateway/issues/2850
- Unit tests added:No
Not Tested
---
> Fix order issue in change HTTP method API Policy

- integration/mock-backend-server/src/main/resources/Dockerfile
- pom.xml
$subject
Also this PR upgrades the `adoptopenjdk/openjdk11` version used in mock-backend server and APICTL version to the latest.
Fixes https://github.com/wso2/product-microgateway/issues/2867
---
> TestContainers version upgrade

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
- integration/test-integration/src/test/resources/apim/1/apis/ExistingAPI.json
Fixes https://github.com/wso2/product-microgateway/issues/2870
Not Tested
---
> Remove cluster header name from request to backend

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/SubscriptionThrottlingTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TokenUtil.java
- integration/test-integration/src/test/resources/automation.xml
- integration/test-integration/src/test/resources/configs/cc-special-scenarios-with-apim.toml
- integration/test-integration/src/test/resources/configs/controlplane-enabled-config.toml
- integration/test-integration/src/test/resources/configs/vhost-deployment.toml
- integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
Fixes https://github.com/wso2/product-microgateway/issues/2811
Related to https://github.com/wso2/product-microgateway/issues/2812
Not Tested
---
> [int-tests] Update tests to use API-M with a port offset of 1 same as cc dist

- components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/upload_files_timer.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/usagedata_uploader.bal
$Subject
* https://github.com/wso2/product-microgateway/issues/2822
> Fixing increased memory Consumption on connectivity issues

- pom.xml
Increasing ballerina version
* https://github.com/wso2/product-microgateway/issues/2740
> Increasing ballerina version

- samples/openAPI-definitions/mock-impl-sample.yaml
$subject
Fixes #
Not Tested
---
> [samples] Add mock impl openapi

- .github/ISSUE_TEMPLATE/config.yaml
- pom.xml
1. product-microgateway cannot be built in latest maven versions as it is unable to connect to http nexus repos. Adding repos fixes the issue.
2. Update the issue template.
Fixes https://github.com/wso2/product-microgateway/issues/2893
Not Tested
---
> Adding Repos 

- resources/interceptor-service-open-api.yaml
- samples/interceptors/ballerina/cc-sample-xml-interceptor/types.bal
- samples/interceptors/golang/go-interceptor-server-generated/api/swagger.yaml
- samples/interceptors/golang/go-interceptor-server-generated/go/model_request_handler_request_body.go
- samples/interceptors/java/spring-server-generated/src/main/java/io/swagger/model/RequestHandlerRequestBody.java
- samples/interceptors/nodejs/nodejs-interceptor-server-generated/api/openapi.yaml
$subject
Docs should be updated with the new open API spec
Fixes https://github.com/wso2/product-microgateway/issues/2901
Tested samples Java, NodeJS
---
> Fix invocationContext field in interceptor OpenAPI

- adapter/internal/adapter/adapter.go
- adapter/internal/common/constants.go
- adapter/internal/eventhub/subscription.go
- adapter/internal/synchronizer/apis_fetcher.go
- adapter/internal/synchronizer/keymanagers_fetcher.go
- adapter/internal/synchronizer/revoked_tokens_fetcher.go
- adapter/internal/synchronizer/throttle_data_fetcher.go
- adapter/pkg/adapter/adapter.go
- adapter/pkg/synchronizer/apis_fetcher.go
$subject.
Fixes #
Not Tested
---
> Add organizationID=ALL query parameter to all the control plane requests

- pom.xml
$subject 
Also this PR updates,
> GSON version
> Analytics common version
Fixes #
Not Tested
---
> Apache Tomcat dependency version upgrades

- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/open_api.go
- adapter/internal/oasparser/model/swagger.go
Fixes https://github.com/wso2/product-microgateway/issues/2872
Not Tested
---
> Refactor error logs

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/notifier/deployment_notifier.go
- adapter/internal/synchronizer/apis_fetcher.go
- resources/conf/config.toml.template
Fixes https://github.com/wso2/product-microgateway/issues/2922
Not Tested
---
> [choreo] Add config for revision update success call

- adapter/internal/synchronizer/apis_fetcher.go
Fix missing condition check from https://github.com/wso2/product-microgateway/pull/2923
Fixes #
Tested
---
> [choreo] Fix revision call

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/notifier/deployment_notifier.go
- adapter/internal/synchronizer/apis_fetcher.go
- resources/conf/config.toml.template
Fixes https://github.com/wso2/product-microgateway/issues/2922
Tested
---
> Add config for revision update success call

- pom.xml
$subject
N/A
Fixes #
Not Tested
---
> gRPC health probe version upgrade

- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Constants.java
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackend2.java
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockServices.java
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/ResponseConstants.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/interceptor/InterceptorRequestFlowTestcase.java
- integration/test-integration/src/test/resources/openAPIs/api_policy_intercept_request_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/intercept_request_openAPI.yaml
- router/src/main/assembly/assembly.xml
- router/src/main/resources/interceptor/README.md
- router/src/main/resources/interceptor/lib/consts.lua
- router/src/main/resources/interceptor/lib/interceptor.lua
- router/src/main/resources/interceptor/lib/utils.lua
$subject
Add a developer guide for interceptors
Fixes https://github.com/wso2/product-microgateway/issues/2939
- Unit tests added: Not possible
Tested in Docker Compose setup
---
> Fix subsequent dynamic endpoint calls fail after the first one

- enforcer-parent/pom.xml
- integration/pom.xml
- pom.xml
$subject
Fixes https://github.com/wso2/product-microgateway/issues/2944
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
---
> Fixes for oss index usage in dependency scan plugin

- .github/workflows/nightly-integration-test.yml
Related to wso2/product-microgateway#2885
$subject
Task
Not Tested
---
> Bump ubuntu nighly build workflow go version

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
- integration/mock-backend-server/pom.xml
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Constants.java
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/EchoResponse.java
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Utils.java
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/dto/EchoResponse.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/AllHttpMethodsForWildcardTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/TrailingSlashTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
- integration/test-integration/src/test/resources/openAPIs/all_http_methods_for_wildcard_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/trailing_slash_openAPI.yaml
- integration/test-integration/src/test/resources/testng-cc-standalone.xml
Integration tests for https://github.com/wso2/product-microgateway/pull/2865
For choreo branch
Fixes https://github.com/wso2/product-microgateway/issues/2864
Not Tested
---
> [int-tests] Add path trailing slash test

- components/micro-gateway-core/src/main/ballerina/Ballerina.toml
- pom.xml
As $subject, this will upgrade ballerina and Jackson dependencies.
Fixes #2866
> Upgrade ballerina and Jackson dependencies

- envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/BUILD
- envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/WORKSPACE
- envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.cc
- envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/handler.h
- envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/handler_impl.cc
- envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/handler_impl.h
Update [proxy-wasm-cpp-sdk](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk) to latest commit (c32d380ca6c9b1afac38a3841be99c37af2698bf)
Fixes #2950
WASM build with docker on linux using `envoyproxy/envoy-build-ubuntu:3f6b1b096f2c0652ed270c5564b292bdd9a520f6`
---
> Update proxy-wasm-sdk version to `c32d380ca6c9b1afac38a3841be99c37af2698bf`

- components/micro-gateway-cli/pom.xml
- components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
- distribution/pom.xml
- distribution/resources/bin/gateway
- distribution/resources/bin/gateway.bat
- distribution/resources/bin/micro-gw
- distribution/src/main/assembly/linux_bin.xml
- distribution/src/main/assembly/macos_bin.xml
- distribution/src/main/assembly/windows_bin.xml
Fixing
* https://github.com/wso2/product-microgateway/issues/2752
Adding JDK 11 Support to MGW 3.2
> Adding JDK 11 related changes

- developer-guide.md
$subject
Fixes #
Not Tested
---
> Include Error Logging in developer guide

- adapter/src/main/resources/check_health.sh
- enforcer-parent/enforcer/src/main/resources/check_health.sh
$subject
Fixes https://github.com/wso2/product-microgateway/issues/2973
Not Tested
---
> Using loopback IP address instead of localhost in gRPC health probe

- router/src/main/resources/interceptor/README.md
> Update docs on create Router docker image with interceptor lua changes

- adapter/internal/discovery/xds/common/utils.go
- adapter/internal/discovery/xds/common/utils_test.go
- adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
- adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
Bring the same set of improvements done for picking connected routers,enforcers for a selected adapter
Add missing improvements for the PR https://github.com/wso2/product-microgateway/pull/2889 compared to https://github.com/wso2/product-microgateway/pull/2876
Fixes #2880
Not Tested
---
> Find connected adapters enforcers to a given adapter

- pom.xml
…tomcat.embed
$subject
Fixes #
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
---
> Dependency version upgrades for apache tomcat embed core

- adapter/internal/ga/client.go
- adapter/pkg/synchronizer/types.go
> Add temporary if condition to prevent redeploying of APIs due to new revision id with timestamp

- .trivyignore
- adapter/go.mod
- adapter/go.sum
go.mod updated for revision id related changes
Related to:  https://github.com/wso2/product-microgateway/pull/3026
Fixes #
---
> go.mod updated for revision id related changes

- pom.xml
$subject
Fixes https://github.com/wso2/product-microgateway/issues/2989
Not Tested
---
> Update apache.tomcat.embed.version used for jaeger tracing

- adapter/internal/ga/client.go
Update `preprocessRevisionID` timestamp check to `2022/09/22 23:59:59 IST`. Revision IDs with timestamps will be ignored until that timestamp. 
Not Tested
---
> Update revision timestamp check

- pom.xml
Upgrades dependency versions to the latest
Fixes #
Not Tested
---
> Dependency version upgrades

- adapter/internal/ga/client.go
Revert temporary changes added in #3026 
Fixes #
Not Tested
---
> Revert temporary changes added in #3026

- pom.xml
Bump : slf4j-ext, gson, netty
Fixes #
Not Tested
---
> Bump : slf4j-ext, gson, netty

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/QSGAndSwaggerTestCase.java
$subject
Fixes https://github.com/wso2/product-microgateway/issues/3051
Not Tested
---
> int-tests: Invoke mockbackend in QSG

- samples/apiProjects/SampleWebsocketApi/Definitions/asyncapi.yaml
- samples/apiProjects/SampleWebsocketApi/README.md
- samples/apiProjects/SampleWebsocketApi/api.yaml
$subject
Adds sample WebSocket API project. This will be used in the DOCs to explain WebSocket API deployment in stand-alone mode.
Fixes https://github.com/wso2/product-microgateway/issues/3042
Not Tested
---
> Addition of sample WebSocket API project

- adapter/internal/ga/client.go
> Add timestamp check for revision ids

- adapter/go.mod
- adapter/go.sum
> upgrade azure sdk

- adapter/src/main/resources/Dockerfile
- enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/EndpointCluster.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/Utils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
- enforcer-parent/enforcer/src/main/resources/Dockerfile
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/NoBasepathEndpointTestCase.java
- integration/test-integration/src/test/resources/openAPIs/no_basepath_openAPI.yaml
- integration/test-integration/src/test/resources/testng-cc-standalone.xml
- router/src/main/resources/Dockerfile
Fixes https://github.com/wso2/product-microgateway/issues/2984
Fixes https://github.com/wso2/product-microgateway/issues/3085
Tested
---
> Fix :path when endpoint with no basepath

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyHandler.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
> Update frequent user operations related error logs to debug log level

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyHandler.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
> Update frequent user operations related error logs to debug log level 

- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java
$Subject
- https://github.com/wso2/product-microgateway/issues/3068
> Handle schemas which locate inside the resources

- integration/test-integration/src/test/resources/dockerCompose/cc-cacert-mounted-mtls.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
$subject
TODO: Update the helm chart with removing this unused Env var
Task
Related issue: https://github.com/wso2/kubernetes-microgateway/issues/87
Not Tested
---
> Remove unused env var `apim_admin_pwd`

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/JWTUtils.java
$subject
Fixes https://github.com/wso2/product-microgateway/issues/3089
Not Tested
---
> Fix new line issue when certs are created in a Windows platform

- pom.xml
- Upgrade analytics.event.publisher.client.version to 1.0.10
> Upgrade analytics.event.publisher.client.version to 1.0.10

- pom.xml
upgrade grpc-health-probe dependency to 0.4.13
Fixes #
Not Tested
---
> upgrade dependency versions

- pom.xml
Update dependencies to non-vulnerable versions
Fixes #
Not Tested
---
> Update enforcer dependencies

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/oasparser/envoyconf/access_loggers.go
- codecov.yml
- dev-scripts/code-coverage/prepare-files-before-int-tests.sh
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsUtils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AnalyticsConstants.java
- pom.xml
- resources/conf/config.toml.template
- samples/analytics-custom-data-provider/README.md
- samples/analytics-custom-data-provider/pom.xml
- samples/analytics-custom-data-provider/src/main/java/org/wso2/carbon/apimgt/gateway/sample/publisher/CustomDataProvider.java
$subject
Users can send required request headers, response headers, response trailers with analytics event.
Docs PR:
https://github.com/wso2/docs-apim/pull/6395
Fixes  https://github.com/wso2/product-microgateway/issues/3124
Not Tested
---
> Custom Analytics Data Provider Support

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
- tests/src/test/java/org/wso2/micro/gateway/tests/validation/BuildWithSpecialCharsTestCase.java
- tests/src/test/resources/openAPIs/validation/specialCharacterAPI.json
- tests/src/test/resources/testng.xml
> WUM fix for the patch https://github.com/wso2/product-microgateway/issues/3116
> Fixes for build failure when definition file having index numbers and special characters in path params

- pom.xml
To update the version of woodstox-core.
Not Tested
---
> Added woodstox-core as a direct dependency

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/ThrottlePolicyGenerator.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
- components/micro-gateway-core/src/main/ballerina/Ballerina.toml
- pom.xml
Update the Jackson databind version and ballerina version
> Jackson databind version update

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/extensions/DisableSecurityTestCase.java
- integration/test-integration/src/test/resources/openAPIs/disable_security_openAPI.yaml
Related to #3139 
Tested on docker
---
> Forward the authorization header to backend if the authentication is disabled at the gateway level

- .github/ISSUE_TEMPLATE/config.yml
> Moving from slack to Discord

- .gitmodules
- distribution/src/main/assembly/assembly.xml
- pom.xml
- rate-limiter/pom.xml
- rate-limiter/scripts/build.sh
- rate-limiter/src/main/assembly/assembly.xml
- rate-limiter/src/main/resources/Dockerfile
- resources/conf/rate-limiter-config.yaml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/license/LICENSE-RATE-LIMITER.txt
Include choreo connect rate limiter component, with patching envoy rate limiter service with xDS config update feature.
File config is used temporarily until xDS capability is implemented in Adapter.
Fixes #
Tested with the sample xDS server: https://github.com/renuka-fernando/ratelimit/tree/be6c1076fdce97718ac21c4eb3638f187674947a/examples/xds-sotw-config-server
Health check
```sh
$ curl http://localhost:8090/healthcheck
OK
```
Tested with File config and following curl.
```sh
curl http://localhost:8090/json -i -d '{
"domain": "default",
"descriptors": [
{
"entries": [
{
"key": "org",
"value": "wso2"
},
{
"key": "vhost",
"value": "localhost"
},
{
"key": "path",
"value": "/foo"
},
{
"key": "method",
"value": "GET"
},
{
"key": …
```
> Add Choreo Connect Rate Limiter component

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APISecurityConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/GatewayEnvTokenTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TokenUtil.java
- integration/test-integration/src/test/resources/testng-cc-standalone.xml
Fixes https://github.com/wso2-enterprise/choreo/issues/17132
Not Tested
---
> Environment based access token validation

- adapter/scripts/build.sh
error message
go: 'go install' requires a version when current directory is not in a module
Try 'go install golang.org/x/lint/golint@latest' to install the latest version
Signed-off-by: Renuka Fernando <renukapiyumal@gmail.com>
Fixes #
Not Tested
---
> Fix issue installing go lint

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/http_filters.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/JwtGeneratorTestCase.java
- integration/test-integration/src/test/resources/configs/jwt-generator-config.toml
- resources/conf/config.toml.template
With this PR, JWKS endpoint calls are rate limited based on local rate limit feature.
Fixes #
Not Tested
---
> Rate limit JWKS endpoint

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/FaultCodeClassifier.java
$subject
Related to https://github.com/wso2/product-microgateway/pull/3160
Not Tested
---
> [choreo] Add env related error code to FaultCodeClassifier

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
- pom.xml
Increment apim common gatway dependency.
Removed some redundant code
Removed padding from kid property value
Not Tested
---
> Remove padding from the KID value in backendJWT

- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
> Fixing test failures

- adapter/src/main/resources/Dockerfile
- enforcer-parent/enforcer/src/main/resources/Dockerfile
- resources/k8s-artifacts/choreo-connect/choreo-connect-service.yaml
Fixes https://github.com/wso2/product-microgateway/issues/3000 and https://github.com/wso2/product-microgateway/issues/3114
Fixes #
Not Tested
---
> Base Image Update for Adapter and Enforcer

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/ApimRestartExecutor.java
> Increasing waiting time for the restart

- pom.xml
Upgrades below dependency versions
- io.netty.version
- jackson.databind.version
- jackson.annotations.version
Fixes #
https://github.com/wso2/product-microgateway/issues/3106
https://github.com/wso2/product-microgateway/issues/3094
Not Tested
---
> [choreo] Dependency version upgrades

- adapter/internal/discovery/xds/common/utils.go
- adapter/internal/discovery/xds/common/utils_test.go
Signed-off-by: Lahiru De Silva <lahirude@wso2.com>
Log improvement to track request type in enforcer callbacks
Related to # https://github.com/wso2-enterprise/choreo/issues/17448
Not Tested
---
> [Choreo][xDS]: Log improvement to track request type in enforcer callbacks

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/synchronizer/api_fetcher_test.go
- adapter/internal/synchronizer/apis_fetcher.go
Merge the deployment details so that there will only be a single entry per revision with all deployed environments listed in `envInfo`
Fixes https://github.com/wso2-enterprise/choreo/issues/17948
Not Tested
---
> Merge envInfo by deployed revision

- adapter/go.mod
- adapter/go.sum
- pom.xml
Signed-off-by: Lahiru De Silva <lahirude@wso2.com>
update azsb and grpc health probe
Fixes #(https://github.com/wso2-enterprise/choreo/issues/17744)
Not Tested
---
> [Choreo] Adapter: update azsb and grpc health probe

- pom.xml
Upgrades dependency versions in the root pom file to the latest versions.
Fixes #
https://github.com/wso2/product-microgateway/issues/3195
https://github.com/wso2/product-microgateway/issues/3186
https://github.com/wso2/product-microgateway/issues/3190
Not Tested
---
> [main] Dependency version upgrades

- dev-scripts/remove-containers.sh
- enforcer-parent/enforcer/src/main/resources/Dockerfile
- integration/test-integration/src/test/resources/dockerCompose/cc-cacert-mounted-mtls.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
> Preparing for 1.2.0-alpha release

- dev-scripts/remove-containers.sh
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/extensions/DisableSecurityTestCase.java
- integration/test-integration/src/test/resources/dockerCompose/backend-service-gql.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls-with-opa-server.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-cacert-mounted-mtls.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- integration/test-integration/src/test/resources/openAPIs/disable_security_openAPI.yaml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Fixes https://github.com/wso2/product-microgateway/issues/3139
Not Tested
---
> Authentication Token should be passed to the backend if the security is disabled

- adapter/config/parser.go
- adapter/internal/discovery/xds/consul.go
- adapter/internal/ga/client_test.go
- adapter/internal/oasparser/envoyconf/access_loggers.go
- adapter/internal/oasparser/envoyconf/compression_filter.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/http_filters.go
- adapter/internal/oasparser/envoyconf/listener.go
- adapter/internal/oasparser/envoyconf/listener_test.go
- adapter/internal/oasparser/envoyconf/response_mapper.go
- adapter/internal/oasparser/envoyconf/routes_configs.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- dev-scripts/remove-containers.sh
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/interceptor/InterceptorRequestFlowTestCase.java
- integration/test-integration/src/test/resources/dockerCompose/backend-service-gql.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-tls-with-opa-server.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service-with-tls-and-network.yaml
- integration/test-integration/src/test/resources/dockerCompose/backend-service.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-cacert-mounted-mtls.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/envoy.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
Fixes https://github.com/wso2/product-microgateway/issues/3224
Not Tested
---
> Removing deprecated warnings in the Router

- adapter/src/main/resources/Dockerfile
Upgrades adapter base image to the latest version (`3.17.1`).
Fixes  https://github.com/wso2/product-microgateway/issues/3232
Not Tested
---
> [main] Adapter base image version upgrade

- components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/upload_files_timer.bal
This PR adds the change to remove a data usage file if it has already been uploaded to the analytics database.
Fixes https://github.com/wso2/product-microgateway/issues/3189
> [3.2.x] Add change to remove file if it is already uploaded

- adapter/src/main/resources/Dockerfile
- enforcer-parent/enforcer/pom.xml
- enforcer-parent/enforcer/src/main/resources/Dockerfile
- pom.xml
Upgrades base images in the Adapter and Enforcer and dependency versions to the latest versions.
Fixes #
https://github.com/wso2/product-microgateway/issues/3195
https://github.com/wso2/product-microgateway/issues/3186
https://github.com/wso2/product-microgateway/issues/3190
https://github.com/wso2/product-microgateway/issues/3232
Not Tested
---
> [choreo] Base images and dependency version upgrades

- enforcer-parent/enforcer/src/main/resources/Dockerfile
Fixes https://github.com/wso2/product-microgateway/issues/3213
Not Tested
---
> Move Enforcer docker image from Ubuntu to Alpine

- adapter/go.mod
- adapter/internal/synchronizer/api_fetcher_test.go
Fix intermittent test failure due to the order of elements were not guaranteed in the returned deploymentList. Fixes are introduced to the tests.
Not Tested
---
> Fix intermittent test failures in build pipeline

- adapter/go.mod
- adapter/go.sum
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyPerOperationTestCase.java
- pom.xml
Fix CORS failure when invoking APIs with API Policies.
Update route names which are added with Rewrite Method API Policies to easily catch what it is used for. Following is a sample.
Update go-control-plane as v0.11.0
Fixes https://github.com/wso2/product-microgateway/issues/3242
Docker Compose
---
> Fix CORS failure when invoking APIs with API Policies

- adapter/src/main/resources/Dockerfile
- enforcer-parent/enforcer/src/main/resources/Dockerfile
Fixes https://github.com/wso2/product-microgateway/issues/3250
Not Tested
---
> [main] Enforcer and Adapter base image update

- pom.xml
- tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
This PR upgrades the Ballerina version to 1.2.35 for some third party dependency upgrades.
> [3.2.x] Upgrade Ballerina version to 1.2.35

- adapter/internal/discovery/xds/server.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/GraphQLAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/graphql/GraphQLQueryAnalysisFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
$subject
Related commit: https://github.com/wso2/product-microgateway/commit/b2f187c73ecd71e4aac1cae09699f1e262317536
Fixes #3252
Fixes #3253
Tested with docker compose setup + APIM
---
> Support mTLS authentication for GraphQL APIs

- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/listener.go
- adapter/internal/oasparser/envoyconf/listener_test.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Fixes https://github.com/wso2/product-microgateway/issues/3260
Not Tested
---
> Adding otlp tracing support for Envoy

- adapter/src/main/resources/Dockerfile
- enforcer-parent/enforcer/src/main/resources/Dockerfile
- router/src/main/assembly/assembly.xml
- router/src/main/resources/Dockerfile
- router/src/main/resources/docker-entrypoint.sh
- router/src/main/resources/envoy.yaml.template
This will improve the readability of envoy.yaml file
Fixes https://github.com/wso2/product-microgateway/issues/3264
Not Tested
---
> Template envoy.yaml in Router Dockerfile

- adapter/src/main/resources/check_health.sh
- enforcer-parent/enforcer/src/main/resources/check_health.sh
Fixes https://github.com/wso2/product-microgateway/issues/3266
Not Tested
---
> Adding tls server name to check_health

- adapter/internal/discovery/xds/server.go
- Add missing changes for $subject related to https://github.com/wso2/product-microgateway/pull/3259
- Some refactoring
Fixes #
Not Tested
---
> [choreo] bug fix: API not deleted with event, when setting xds cache under a common label for dynamic environments

- dev-scripts/remove-containers.sh
- integration/test-integration/src/test/resources/dockerCompose/cc-cacert-mounted-mtls.yaml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-docker-compose.yaml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
> Preparing for 1.2.0-beta release

- adapter/pom.xml
- distribution/pom.xml
- enforcer-parent/commons/pom.xml
- enforcer-parent/enforcer/pom.xml
- enforcer-parent/pom.xml
- integration/mock-backend-server/pom.xml
- integration/pom.xml
- integration/test-integration/pom.xml
- pom.xml
- router/pom.xml
$subject
Fixes #
Not Tested
---
> Correct developer version as 1.2.0-beta2-SNAPSHOT

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
- samples/analytics-custom-data-provider/pom.xml
Fixes https://github.com/wso2/product-microgateway/issues/3272
Not Tested
---
> Fixing issues in custom data provider

- .fossa.yml
- enforcer-parent/enforcer/pom.xml
- pom.xml
- samples/interceptors/java/spring-server-generated/pom.xml
Fixes https://github.com/wso2/product-microgateway/issues/3280
Not Tested
---
> Adding .fossa.yml to skip samples 

- adapter/go.mod
- adapter/go.sum
Fixes https://github.com/wso2/product-microgateway/issues/3190
Not Tested
---
> Updating crypto version

- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/internal_dtos.go
- adapter/internal/oasparser/envoyconf/listener_test.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/QSGAndSwaggerTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/circuitBreakers/CircuitBreakersTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/BackendSecurityTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/ProductionSandboxTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/retry/RetryTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/timeouts/TimeoutTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/vhost/VhostAPICtlTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BackendSecurityTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
Remove sandbox cluster creation 
Fixes #
Not Tested
---
> Remove sandbox cluster creation 

- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/internal_dtos.go
- adapter/internal/oasparser/envoyconf/listener_test.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/QSGAndSwaggerTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/circuitBreakers/CircuitBreakersTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/BackendSecurityTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/ProductionSandboxTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/retry/RetryTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/timeouts/TimeoutTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/vhost/VhostAPICtlTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BackendSecurityTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
Reverts wso2/product-microgateway#3277
> Revert "Remove sandbox cluster creation "

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsForWSProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/metrics/MetricsUtils.java
Fixes https://github.com/wso2/product-microgateway/issues/3298
Not Tested
---
> Fixing websocket analytics

- pom.xml
- samples/analytics-custom-data-provider/pom.xml
Fixes https://github.com/wso2/product-microgateway/issues/3190
Not Tested
---
> Updating analytics publisher client version

- .fossa.yml
- adapter/go.mod
- adapter/go.sum
- enforcer-parent/enforcer/pom.xml
- pom.xml
- samples/interceptors/java/spring-server-generated/pom.xml
$Subject
Fixes # 
Not Tested
---
> Fix critical and high fossa scan issues

- components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
Fixes https://github.com/wso2/product-microgateway/issues/3292
> Add POST method to token call

- pom.xml
Bump version.
Fixes #
Not Tested
---
> [choreo] Upgrade grpc-health-probe version

- adapter/internal/oasparser/envoyconf/http_filters.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/ratelimit/ApiLevelRatelimitTestCase.java
remove x-envoy-ratelimited header.
Fixes #
Not Tested
---
> Remove unnecessary headers associated with rate limit filter

- dev-scripts/cc-router-debug-docker-image/README.md
- dev-scripts/directory-structure-maker/README.md
- dev-scripts/directory-structure-maker/directory-structure-maker.sh
- dev-scripts/directory-structure-maker/docker-image-builder.sh
- dev-scripts/private-registry-images/build-private-registry-images.sh
- integration/test-integration/pom.xml
> Update Dev Scripts for 1.2.0 U2 and Debug Images

- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/internal_dtos.go
- adapter/internal/oasparser/envoyconf/listener_test.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/QSGAndSwaggerTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/circuitBreakers/CircuitBreakersTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/BackendSecurityTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/endpoints/ProductionSandboxTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/retry/RetryTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/timeouts/TimeoutTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/vhost/VhostAPICtlTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BackendSecurityTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
Reverts wso2/product-microgateway#3291
> Remove sandbox cluster creation

- adapter/internal/oasparser/model/api_yaml.go
- adapter/internal/oasparser/model/api_yaml_test.go
- adapter/internal/oasparser/model/types.go
- integration/test-integration/src/test/resources/apiYaml/operation_level_ratelimit_api.yaml
> Bug fix: Old API deployment fails due to not having the throttlingLimit Property

- pom.xml
Fixes https://github.com/wso2/product-microgateway/issues/3321
> Upgrade Ballerina platform version to 1.2.37

- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/types.go
- integration/test-integration/src/test/resources/openAPIs/operation_level_ratelimit_openAPI.yaml
Fixes rate-limit level undefined scenario that happens with the old APIs.
Fixes #
Not Tested
---
> [Choreo] Fix for rate-limit undefined scenario

- adapter/src/main/resources/Dockerfile
- enforcer-parent/enforcer/src/main/resources/Dockerfile
- pom.xml
$subject
Fixes https://github.com/wso2/product-microgateway/issues/3329 
https://github.com/wso2/product-microgateway/issues/3317
Not Tested
---
> [main] Base image version update

- pom.xml
Fixes related to https://github.com/wso2-enterprise/wso2-apim-internal/issues/2433
> Upgrade Ballerina platform version to 1.2.38

- adapter/src/main/resources/Dockerfile
- enforcer-parent/enforcer/src/main/resources/Dockerfile
- pom.xml
$subject
Fixes https://github.com/wso2/product-microgateway/issues/3333
Related issues: 
https://github.com/wso2/product-microgateway/issues/3329
Not Tested
---
> [Choreo] Dependency and base image updates

- adapter/pkg/config/log_types.go
- resources/conf/log_config.toml
$subject
Fixes #
Not Tested
---
> Document default ReservedLogFormat in log_config.toml

- adapter/config/default_config.go
- adapter/config/parser.go
- adapter/config/types.go
- adapter/internal/adapter/adapter.go
- adapter/internal/common/constants.go
- adapter/internal/ga/api_event_listener.go
- adapter/internal/messaging/notification_listener.go
- adapter/internal/synchronizer/apis_fetcher.go
- adapter/pkg/messaging/event_types.go
- resources/conf/config.toml.template
- These changes will bring the gateway accessibility type(internal/external) defined in APIM, along with the gateway environments and pull API artifacts based on that, when dynamic environment support is enabled
Fixes #
Not Tested
---
> [choreo] add gateway accessibility type to configs

- adapter/pkg/messaging/event_types.go
$subject
Related PR : https://github.com/wso2/product-microgateway/pull/3349
Not Tested
---
> [choreo] fix: rename gateway accessibility type map json tag name

- pom.xml
$subject
Fixes #
Not Tested
---
> Upgrade Apache Tomcat version

- enforcer-parent/enforcer/src/main/resources/Dockerfile
$subject
Fixes #
Not Tested
---
> Upgrade Alpine version of Enforcer

- adapter/internal/adapter/adapter.go
- adapter/internal/ga/client.go
Add dynamic environment support with global adapter
- change the partitioning logic to a dataplane based approach
Fixes #
Not Tested
---
> [choreo] Add dynamic environment support with global adapter

- adapter/internal/synchronizer/apis_fetcher.go
Adapter will no longer retry the runtime-artifacts endpoint endlessly for responses received with status 500. Instead of that it should stop after 10 retries. And there is log statement to indicate that the retry is stopped for the particular API.
Fixes #
Not Tested
---
> Limit retries to fetch the runtime artifacts. 

- router/src/main/resources/Dockerfile
Upgrading envoy version
Fixes #
Not Tested
---
> [choreo] upgrade envoy version to 1.24.7

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APISecurityConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyHandler.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
Adding aud claim verification for internal api key.
Fixes
* https://github.com/wso2-enterprise/choreo/issues/20799
Not Tested
---
> Adding aud claim verification for internal api key.

- adapter/internal/adapter/adapter.go
$subject
Fixes #
Not Tested
---
> [choreo] bug fix: call StartConsumeGAAPIChannel when the startup APIs list is completed

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/mtls/MTLSAuthenticator.java
$subject
Fixes https://github.com/wso2/product-microgateway/issues/3372
Not Tested
---
> Set the key type in Auth Context for mTLS

- adapter/internal/ga/client.go
$subject
Fixes #
Not Tested
---
> [choreo] log fix: print discovery response size for ga discovery response

- adapter/internal/discovery/xds/rate_limiter_cache.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/eventhub/subscription.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/listener.go
- adapter/internal/oasparser/envoyconf/listener_test.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/pkg/eventhub/types/types.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- integration/mock-backend-server/src/main/resources/Dockerfile
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/CcStartupExecutorWithRatelimit.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/SubscriptionThrottling2TestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/ThrottlingBaseTestCase.java
- integration/test-integration/src/test/resources/apimApisAppsSubs/applications.json
- integration/test-integration/src/test/resources/configs/controlplane-enabled-config-with-ratelimit.toml
- integration/test-integration/src/test/resources/dockerCompose/cc-in-common-network-with-ratelimit-docker-compose.yaml
- integration/test-integration/src/test/resources/testng-cc-with-apim.xml
$subject. It would be the same subscription based ratelimiting feature as in current choreo connect product. Only difference is that it would use the rate limiter service instead of the traffic manager.
Fixes #
Not Tested
---
> [Task]: Add subscription rate limiting with new rate limiter service.

- adapter/internal/oasparser/envoyconf/access_loggers.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/listener.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AnalyticsConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/MetadataConstants.java
- pom.xml
Related with: https://github.com/wso2-enterprise/choreo/issues/21887
> Add support to publish Gateway URL to Moesif

- adapter/pkg/messaging/event_types.go
> Adding envDetails to API event

- pom.xml
Fixes https://github.com/wso2/product-microgateway/issues/3374
> Fix issue when curly brackets are used in query parameter

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AnalyticsConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/MetadataConstants.java
- pom.xml
https://github.com/wso2-enterprise/choreo/issues/22229
> Enable environment support for Choreo - Moesif integration

- adapter/internal/oasparser/envoyconf/access_loggers.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/pkg/config/log_types.go
- resources/conf/log_config.toml
$subject
```json
{"du":143,"usrAgt":"curl/7.79.1","proto":"HTTP/1.1","fwdFor":null,"reqTxDu":93,"reqPath":"/testkey","host":"enforcer","reqId":"74ffe478-52e2-4a61-bb84-bce35cf0aeee","resDu":143,"resTxDu":0,"bytRec":15,"gwPath":null,"resCd":200,"upsHost":"172.20.0.4:9001","upsSvcTime":null,"t":"2023-07-07T10:12:56.078Z","resFlg":"-","reqDu":2,"rtName":"system#/testkey","gwHost":null,"m":"POST","bytSnt":762,"resCdInf":"via_upstream"}
{"resDu":4294,"fwdFor":null,"reqId":"168a1cf4-af51-44b7-aea8-5b4c035f87b0","upsHost":"54.204.94.184:443","upsSvcTime":null,"m":"GET","reqDu":0,"bytSnt":460,"resFlg":"-","reqPath":"/anything/pet/findByStatus?status=pending","resCdInf":"via_upstream","du":4295,"bytRec":0,"reqTxDu":1418,"rtName":"648957e7a675c35145393369","resCd":200,"t":"2023-07-07T10:13:09.413Z", …
```
> Support JSON Access Log format

- pom.xml
Related with: https://github.com/wso2-enterprise/choreo/issues/22456
> Update analytics publisher client version

- adapter/internal/ga/client.go
$subject. 
Fixes #
Not Tested
---
> [Improvement] Improve Logs to Include the Local adapter label assigned.

- pom.xml
Fixes https://github.com/wso2/product-microgateway/issues/3403
> Upgrade Ballerina version to 1.2.41

- pom.xml
Upgrade Ballerina version to 1.2.42 to fix https://github.com/wso2-enterprise/wso2-apim-internal/issues/3895
> Upgrade Ballerina version to 1.2.42

- adapter/internal/discovery/xds/server.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/APIFactory.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnvVarConfig.java
> [choreo] Temporary changes for migrating to new vhost format

- adapter/pkg/messaging/azure_connection.go
$subject as processing a large batch of organization purge events could result in OOM issues
Fixes #
Not Tested
---
> Temporarily disable organization Purge ASB topic subscription 

- adapter/internal/discovery/xds/semantic_versioning.go
- adapter/pkg/semanticversion/semantic_version.go
Reverts wso2/product-microgateway#3407
> Revert "Move semantic version comparison to package"

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/discovery/xds/semantic_versioning.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/pkg/loggers/logger.go
- adapter/pkg/semanticversion/semantic_version.go
This PR adds the reverted changes from: https://github.com/wso2/product-microgateway/pull/3376 and https://github.com/wso2/product-microgateway/pull/3407 to the product.
Also this PR fixes the issue where the resource path substitution string gets converted to a regex
---
> Implement semantic version based intelligent routing for APIs

- adapter/pkg/tlsutils/tls_utils.go
$subject as it is need not to add trusted CA certificates explicitly as system Cert Pool has it.
Fixes #
Not Tested
---
> Load Adapter Certificates from the System Certificates

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
> Update path regex for rate limit configs

- adapter/internal/discovery/xds/server.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/APIFactory.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnvVarConfig.java
Related to : #3401
$subject
Fixes #
Not Tested
---
> [choreo] Temporarily add env variable to duplicate vhost with organization ID

- components/micro-gateway-core/src/main/ballerina/Ballerina.toml
- pom.xml
Upgrade okio, mime4j, woodstox, json-path, json-smart, json and jackson dependencies.
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/3982 and https://github.com/wso2-enterprise/wso2-apim-internal/issues/4012
> Upgrade third party dependencies

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/ApimResourceProcessor.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/dto/Subscription.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/utils/PublisherUtils.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BlockedApiTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/SubscriptionValidationTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/VersionRangeInvocationTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/VhostApimTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/AdvanceThrottlingTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/ApplicationThrottlingTestCase.java
- integration/test-integration/src/test/resources/apimApisAppsSubs/apis.json
- integration/test-integration/src/test/resources/apimApisAppsSubs/subscriptions.json
- integration/test-integration/src/test/resources/configs/controlplane-enabled-config.toml
- integration/test-integration/src/test/resources/testng-cc-with-apim.xml
$subject
Ubuntu 20.04 with docker
---
> Add intelligent routing based version range invocation tests 

- enforcer-parent/enforcer/pom.xml
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/ExtendedJWKSResourceRetriever.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/JWTUtils.java
- enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/util/JWTUtilsTest.java
- pom.xml
> Use remoteJWKSet library instead of http client to fetch jwkset

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/JWTUtils.java
- enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/util/JWTUtilsTest.java
> Bug fix: Microsoft jwks payload is not pulled due to inavailablility of algorithm

- .github/workflows/main.yml
- integration/test-integration/pom.xml
- pom.xml
> Integration test pom file change to display the test logs

- adapter/internal/oasparser/envoyconf/access_loggers.go
$subject
Related PR: https://github.com/wso2/product-microgateway/pull/3430
Not Tested
---
> Update host regex to filter kube probe logs

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/keymgt/KeyManagerHolder.java
> Bug fix: NPE when a user manually sends the key manager registration without apim property inside environment

- adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
> Add a log to understand organizations which use production token for lower environment deployments

- enforcer-parent/enforcer/src/main/resources/Dockerfile
> Xds discovery client's  max inbound message size is increased

- adapter/internal/adapter/adapter.go
- adapter/internal/synchronizer/apis_fetcher.go
- adapter/pkg/synchronizer/apis_fetcher.go
$Subject
Fixes
* https://github.com/wso2-enterprise/choreo/issues/24460
---
> Adding apiUUID List to API ReFetching

- pom.xml
$Subject
* https://github.com/wso2-enterprise/choreo/issues/24623
> Increasing netty version to 4.1.100.Final

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AnalyticsConstants.java
$Subject
* https://github.com/wso2-enterprise/choreo/issues/24711
Not Tested
---
> Adding necessary data populations for Moesif Integration

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
- pom.xml
$Subject
* https://github.com/wso2-enterprise/choreo/issues/24711
> Changing API Context Setting Mechanism in ChoreoFaultAnalyticsProvider

- pom.xml
Upgrade Ballerina version to 1.2.46
> Upgrade Ballerina version to 1.2.46

- pom.xml
$Subject
* https://github.com/wso2-enterprise/choreo/issues/25069
> Incrementing analytics publisher version to 1.2.16

- components/micro-gateway-core/src/main/ballerina/Ballerina.toml
- distribution/LICENSE-TOOLKIT.txt
- pom.xml
Upgrade Ballerina version to fix https://github.com/wso2/product-microgateway/issues/3457 and upgrade guava and json versions
> Upgrade json, guava and ballerina versions

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/oasparser/model/open_api.go
- adapter/internal/oasparser/model/swagger.go
- adapter/internal/oasparser/model/swagger_internal_test.go
- adapter/internal/oasparser/model/types.go
- resources/conf/config.toml.template
$subject
Fixes https://github.com/wso2-enterprise/choreo/issues/25870
Not Tested
---
> Resource path content length validation

- distribution/resources/bin/gateway
- distribution/resources/bin/gateway.bat
- distribution/resources/bin/micro-gw
Add JDK17 support for Microgateway
Fixes #3464
Not Tested
---
> Add JDK17 support for Microgateway

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/oasparser/envoyconf/listener.go
- resources/conf/config.toml.template
Fixes https://github.com/wso2/product-microgateway/issues/3468
Not Tested
---
> Add downstream tls configs

- distribution/LICENSE-RUNTIME.txt
- distribution/resources/bin/gateway
- distribution/resources/bin/gateway.bat
This will fix the prometheus version issue.
- https://github.com/wso2/product-microgateway/issues/3356
Not Tested
---
> Fix prometheus version issue

- pom.xml
> Upgrade the ballerina version

- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
This PR will validate the request timestamp in the event DTO which is published to analytics
- https://github.com/wso2/product-microgateway/issues/3451
> Validate the request timestamp in the event DTO which is published to analytics

- components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/basic_auth_handler.bal
Security related fixes
Adding the missing fixes in support branch to the public repo.
> Fix security related issues with basic auth flow

- pom.xml
$subject
Fixes #
Not Tested
---
> [choreo] Bump grpc health probe version

- adapter/internal/discovery/xds/rate_limiter_cache.go
- adapter/internal/oasparser/model/mgw_swagger.go
$subject
https://github.com/wso2-enterprise/choreo/issues/26517
Not Tested
---
> [Choreo] Addition of info log to recognise the rate-limit level

- adapter/cmd/adapter/main.go
- adapter/internal/adapter/adapter.go
- adapter/internal/discovery/xds/rate_limiter_cache.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/messaging/listener.go
- adapter/src/main/resources/Dockerfile
- api/proto/wso2/discovery/subscription/subscription_policy.proto
- enforcer-parent/enforcer/src/main/resources/Dockerfile
- integration/mock-backend-server/src/main/resources/Dockerfile
$subject
Fixes #https://github.com/wso2-enterprise/choreo/issues/26980
Not Tested
---
> [Choreo] Code refactoring and base image version upgrades

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
> Set backend JWT enduser from sub claim

- pom.xml
> Update Guava version

- rate-limiter/src/main/resources/Dockerfile
$subject
Fixes #
Relates to: https://github.com/wso2-enterprise/choreo/issues/26811
Not Tested
---
> [Choreo] Update rate-limiter to the latest version

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/router/EnvoyHttpFilterTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/EnvoyHttpFilterTestCase.java
https://github.com/wso2-enterprise/choreo/issues/27771
Tested in Local Docker Compose
---
> Send API UUID to the backend as a header

- pom.xml
> Update carbon.apimgt version - Add AUT cliam for backend JWT

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketThrottleFilter.java
Setting carbon.super as the default tenant for Choreo and removing unnecessary code segments.
Fixes
* https://github.com/wso2-enterprise/choreo/issues/27976
Not Tested
---
> [Choreo] Fixing carbon.super as the default tenant for Choreo

- adapter/internal/discovery/xds/marshaller.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
$subject
Relates with:
https://github.com/wso2-enterprise/choreo/issues/27601
https://github.com/wso2-enterprise/choreo/issues/26811
Fixes #
Not Tested
---
> Minor imprvements considering the logs relevant to the subscription rate-limiting

- adapter/internal/discovery/xds/semantic_versioning.go
- adapter/pkg/semanticversion/semantic_version.go
Reverts wso2/product-microgateway#3506
> Revert "[Choreo] Fix intelligent routing availability after deleting and re-creating an API"

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/subscription/SubscriptionDataStoreImpl.java
$subject
Fixes #
Not Tested
---
> [Choreo] Minor correction for org ID assignment

- adapter/internal/oasparser/model/swagger.go
> Fix swagger2 related issue

- adapter/internal/discovery/xds/rate_limiter_cache.go
$subject
Related issue:  https://github.com/wso2-enterprise/choreo/issues/27601
Fixes #
Not Tested
---
> [choreo] Minor improvement considering the rate-limit count zero

- adapter/internal/api/apis_impl.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/model/api_env.go
- adapter/internal/oasparser/model/async_api.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/open_api.go
- adapter/internal/oasparser/model/swagger.go
- adapter/internal/oasparser/model/types.go
- adapter/internal/oasparser/operator/operator.go
- adapter/internal/oasparser/utills/open_api_utills_test.go
- adapter/internal/oasparser/utills/open_api_utils.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/Utils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/HttpRequestHandler.java
https://github.com/wso2-enterprise/choreo/issues/28561
https://github.com/wso2-enterprise/choreo/issues/26743
Fixes https://github.com/wso2-enterprise/choreo/issues/28561
Not Tested
---
> Enable security disabling for websocket APIs

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/common/constants.go
- resources/conf/config.toml.template
> Populate Organization ID for all the REST calls to the API Manager

- rate-limiter/src/main/assembly/assembly.xml
- rate-limiter/src/main/resources/Dockerfile
- rate-limiter/src/main/resources/docker-entrypoint.sh
- resources/conf/log_config.toml
- router/src/main/resources/docker-entrypoint.sh
> Update Docker entrypoint with proper terminating signaling

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/BackendJwtUtils.java
Makes backend JWT conform to the JWT specification. [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519)
Fixes 
- https://github.com/wso2-enterprise/choreo/issues/29085
Tested with Ballerina,Java and jwt.io
---
> [Choreo] Remove Padding from BackendJWT

- .trivyignore
- pom.xml
$subject
Fixes #
Not Tested
---
> [Choreo] gRPC health probe version update

- adapter/internal/ga/client.go
This will configure the Local adapter to check its grpc connection to the global adapter every 2 minutes.
Fixes #
Not Tested
---
> Add keep alive pings for adapter client

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/GRPCUtils.java
$subject
Fixes #
Not Tested
---
> Reduces frequency of keepalive pings to once every 6 minutes

- adapter/internal/ga/client.go
$subject
Fixes #
Not Tested
---
> Decrease keepalive ping frequency to global adapter to once every 6 minutes

- adapter/internal/oasparser/envoyconf/http_filters.go
> Remove wasm module from http filters

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/listener.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- resources/conf/config.toml.template
> Enable Retries on connection level failures for cluster local services

- adapter/internal/discovery/xds/rate_limiter_cache.go
- adapter/internal/discovery/xds/rate_limiter_cache_test.go
- adapter/internal/eventhub/subscription.go
- adapter/internal/messaging/notification_listener.go
$subject
Relevant issue: https://github.com/wso2-enterprise/choreo/issues/29382
Fixes #
Not Tested
---
> [Choreo] Support for subscription policy notification event handling capability with rate-limiter

- adapter/internal/adapter/adapter.go
Default is a maximum of one keep alive ping per connection every 5 minutes.
Fixes #
Not Tested
---
> Returns enforcement policy to default

- adapter/internal/discovery/xds/rate_limiter_cache_test.go
$subject
Relevant issue: https://github.com/wso2-enterprise/choreo/issues/29451
Fixes #
Not Tested
---
> [Choreo] Test case addition to cover subscription policy notification events

- router/src/main/resources/docker-entrypoint.sh
$subject
Fixes 
Not Tested
---
> Remove feature flag - ROUTER_GRACEFUL_SHUTDOWN_ENABLED

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/listener.go
- resources/conf/config.toml.template
Via this we can switch the conditions for which router would retry the requests. 
Not Tested
---
> Make retry condition configurable in Choreo Connect Router.

- adapter/internal/oasparser/envoyconf/access_loggers.go
- adapter/internal/oasparser/envoyconf/dns_resolver.go
- adapter/internal/oasparser/envoyconf/http_filters.go
- adapter/internal/oasparser/envoyconf/listener.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Add go control plane validation for routes, clusters and endpoints
https://github.com/wso2-enterprise/choreo/issues/28819
Not Tested
---
> Add go control plane validation for routes, clusters and endpoints

- .github/workflows/main.yml
> Add docker-compose alias in GitHub Action workflow

- adapter/internal/ga/client.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/features/FeatureFlags.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/GRPCUtils.java
> Remove GRPC Keepalive Featureflag

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/Utils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/UnsecuredAPIAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/InternalAPIKeyUtils.java
Fixes https://github.com/wso2-enterprise/choreo/issues/30190
Relates to https://github.com/wso2-enterprise/choreo/issues/26321
Not Tested
---
> [Chore] Fix issue when security is disabled and testing from WS Console

- adapter/scripts/build.sh
- adapter/src/main/resources/Dockerfile
- adapter/src/main/resources/Dockerfile.ubuntu
> Remove go-amqp debug logs

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
$subject
Relevant issue: https://github.com/wso2-enterprise/choreo/issues/26811
Fixes #
Not Tested
---
> [Choreo] Remove unused constants from the routes_with_clusters file

- adapter/config/default_config.go
- adapter/config/parser.go
- adapter/config/types.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/utills/mgw_swagger_utils.go
- resources/conf/config.toml.template
Edit cloudflare 503 error - https://community.cloudflare.com/t/the-503-error-is-returned-from-cloudflare/451259/4
When invoked in postman as an http request we get the following response body
```
{
"code": "102505",
"message": "Upstream overflow",
"description": "upstream connect error or disconnect/reset before headers. reset reason: overflow"
}
```
**max_connections**
The maximum number of connections that Envoy will establish to all hosts in an upstream cluster. All connections, whether active or draining, count against this limit. Even if this circuit breaker has overflowed, Envoy will ensure that a host selected by cluster load balancing has at least one connection allocated.
**max_pending_requests**
The maximum number of requests that will be queued while waiting for a ready …
> Add circuit breaking configs for websocket rate limiting

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
> [Choreo] Add analytics for websocket APIs

- components/micro-gateway-core/src/main/ballerina/Ballerina.toml
- components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/AbstractMGWJWTGenerator.java
- pom.xml
$subject
com.nimbusds.nimbus-jose-jwt : 8.8 -> 9.40
ballerina.platform.version : 1.2.51 -> 1.2.54
> Upgrade ballerina.platform.version and nimbusds

- adapter/go.mod
- pom.xml
$subject to fix security vulnarabilities
Fixes #
Not Tested
---
> Upgrade go version & grpc_health_probe version

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/UnsecuredAPIAuthenticator.java
$subject
Fixes #
Not Tested
---
> Handle scenarios where sec-ws-protocol header is null when security is disabled

- adapter/internal/oasparser/model/async_api.go
> Add fix for channels that will not have a / as prefix

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
relates to https://github.com/wso2/product-microgateway/pull/3587
Fixes #
Not Tested
---
> [choreo] set the value for auth header from sec-protocol header

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyUtils.java
$subject
Fixes #
Not Tested
---
> Append PAT exchange endpoint to patExchangeURL

- pom.xml
$subject
Fixes #
Not Tested
---
> Bump commons.io version to 2.14.0

- adapter/internal/oasparser/envoyconf/access_loggers.go
- adapter/internal/oasparser/envoyconf/constants.go
- Filter insights access logs if org id it not present
Fixes #
Not Tested
---
> Filter insights access logs if org id it not present

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
$subject
Fix for authenticator introduced with https://github.com/wso2/product-microgateway/pull/3603
Fixes #
Not Tested
---
> Enable Choreo API Key Authenticator for apiKey scheme

- adapter/config/types.go
- adapter/internal/messaging/azure_listener.go
- adapter/pkg/messaging/azure_connection.go
- adapter/pkg/messaging/azure_listener.go
- resources/conf/config.toml.template
$subject
Fixes #
Not Tested
---
> [choreo] multi-tenanting ASB: Add topic wise ASB event listeners

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/Constants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
> [Choreo] Add support to use test key keyword at WS Handshake Authentication

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/UnsecuredAPIAuthenticator.java
> Add additional change to support test key

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Fixed cluster creation issue with connection pooling disabled
Fixes https://github.com/wso2-enterprise/choreo/issues/30689
Not Tested
---
> Fixed cluster creation issue with connection pooling disabled

- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- enforcer-parent/enforcer/src/main/resources/Dockerfile
- rate-limiter/src/main/resources/Dockerfile
Related Issue
https://github.com/wso2-enterprise/choreo/issues/32763
https://github.com/wso2-enterprise/choreo/issues/32777
Tested in Docker Compose
---
> Update Rate Limiter Image to Configure XDS_CLIENT_MAX_MSG_SIZE_IN_BYTES

- pom.xml
- Update analytics publisher version to 1.2.17
- Fixes for https://github.com/wso2-enterprise/choreo/issues/33016
> Update analytics publisher version to 1.2.17

- pom.xml
Reverts wso2/product-microgateway#3637
> Revert "Update analytics publisher version to 1.2.17"

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyUtils.java
Add traceId header to oauth-agent requests.
> Add traceId header to oauth-agent requests.

- pom.xml
$subject
Relates with: https://github.com/wso2/product-microgateway/pull/3639
Fixes #
Not Tested
---
> [Choreo] Change to update netty.io version to the latest

- resources/docker-compose/apim/conf/deployment.toml
$subject
Relates with: https://github.com/wso2-enterprise/choreo/issues/29162
Fixes #
Not Tested
---
> [Choreo] Addition of default subscription policies to the deployment.toml file

- enforcer-parent/enforcer/src/main/assembly/assembly.xml
- enforcer-parent/enforcer/src/main/resources/Dockerfile
- enforcer-parent/enforcer/src/main/resources/docker-entrypoint.sh
Debug K8s signals and print Enforcer exit code for debug purpose.
Related Issue https://github.com/wso2-enterprise/choreo/issues/34107
Not Tested
---
> Add Enforcer docker-entrypoint.sh

- enforcer-parent/enforcer/src/main/resources/docker-entrypoint.sh
https://github.com/wso2-enterprise/choreo/issues/34107
Not Tested
---
> Remove DEBUG logs in docker-entrypoint.sh

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
Block test key of devportal to access scoped APIs
Fixes #
Not Tested
---
> Block test key of devportal to access scoped APIs

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/AuthServer.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/RestServer.java
- enforcer-parent/enforcer/src/main/resources/docker-entrypoint.sh
- router/pom.xml
- router/src/main/assembly/assembly.xml
- router/src/main/resources/Dockerfile
Fixes https://github.com/wso2-enterprise/choreo/issues/28995
Not Tested
---
> Gracefully shutdown the Enforcer

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiListDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/DiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/KeyManagerDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/RevokedTokenDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ThrottleDataDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/HealthService.java
I've ignored some discovery clients as they are not in use.
Fixes https://github.com/wso2-enterprise/choreo/issues/34099
- Integration tests added:No
Tested in Docker Compose setup
---
> Set Enforcer Health based on initial Discovery Client responses

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/AuthServer.java
- enforcer-parent/enforcer/src/main/resources/docker-entrypoint.sh
$subject
Fixes https://github.com/wso2-enterprise/choreo/issues/28995
Not Tested
---
> Move Rest server shutdown to finally block

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
This PR updates the lbEndpoints of the Cluster with hostname for incluster endpoints. This configured hostname will be used for the auto host rewrite of the routes. Currently as no hostname is configured, it will use the address which doesn't contain the port information. This is done related to the multiple endpoint routing issue in keda. 
Related to https://github.com/wso2-enterprise/choreo/issues/34484#issuecomment-2753193082
Not Tested
---
> Add hostname to lbEndpoint for within cluster endpoints

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
$subject
Fixes #
Not Tested
---
> [Choreo] Log improvement to detect the deployment type when validating the token

- .github/pull_request_template.md
$subject
Fixes #
Not Tested
---
> Adding new Choreo PR template

- .github/PULL_REQUEST_TEMPLATE/feature_pr_template.md
$subject
Fixes #
Not Tested
---
> Add new Choreo PR template

- adapter/scripts/build.sh
> Update golint installer script

- adapter/internal/oasparser/model/mgw_swagger.go
Renaming override variable to corsOverrideEnabled.
Related other PR: https://github.com/wso2/product-microgateway/pull/3659/files
Related issue: https://github.com/wso2-enterprise/choreo/issues/33924
Fixes #
Not Tested
---
> Fix issues with applying cors configurations.

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
> Drop api-key headers except choreo-api-key header after authorization

- adapter/internal/ga/client.go
- adapter/internal/synchronizer/apis_fetcher.go
> Fix Undeploying API when a new revision is deployed.

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/go.mod
- adapter/internal/adapter/adapter.go
- adapter/internal/messaging/aws_connection.go
- adapter/internal/messaging/aws_listener.go
- adapter/internal/messaging/aws_notification_listener.go
$subject
Fixes #
Not Tested
---
> [Choreo] AWS active mq notification support

- router/src/main/resources/Dockerfile
Fixes the issue
Unable to build image [wso2/choreo-connect-router:1.1.0-m1-SNAPSHOT] : "The command '/bin/sh -c apt-get update && apt-get upgrade -y && apt-get install --no-install-recommends --no-install-suggests -y gettext-base && apt-get install --reinstall ca-certificates -y' returned a non-zero code: 100" ["The command '/bin/sh -c apt-get update && apt-get upgrade -y && apt-get install --no-install-recommends --no-install-suggests -y gettext-base && apt-get install --reinstall ca-certificates -y' returned a non-zero code: 100" ]
Not Tested
---
> Fix Choreo Router PR Check Failure

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/mcp/McpExceptionWithId.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/mcp/request/McpRequestHandler.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/mcp/request/McpRequestProcessor.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/mcp/response/PayloadGenerator.java
> Add minor improvements to the MCP flow

- adapter/internal/discovery/xds/ratelimitercallbacks/ratelimiter_callbacks.go
- rate-limiter/src/main/resources/docker-entrypoint.sh
$subject
More info: https://github.com/wso2-enterprise/choreo/issues/18164#issuecomment-2764629269
Fixes https://github.com/wso2-enterprise/choreo/issues/18164
Not Tested
---
> Include hostname as instanceIdentifier to track router callbacks

- adapter/pkg/config/parser.go
- adapter/pkg/config/parser_test.go
Fixes https://github.com/wso2-enterprise/choreo/issues/35730
Unit tests
---
> Fix parse configs with $env{key}

- .github/workflows/log-pr-reviewer.yml
This PR is to add a new pipeline to review each PR regarding log improvements. 
This will call AI Agent with the PR content and it will review the PR with Log improvements. 
Mail thread: [Architecture][Log Improvement] AI agent based log improvement effort
Fixes #
Not Tested
---
> Add log-pr-reviewer github action

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/AuthServer.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/GRPCUtils.java
- pom.xml
$Subject
Fixes #
Not Tested
---
> Update Netty and Netty GRPC

- .github/workflows/pr-reviewer-for-logs.yml
Refactor PR Reviewer for Logs Template name
This pull request includes a small change to the `.github/workflows/pr-reviewer-for-logs.yml` file. The file was renamed from `.github/workflows/log-pr-reviewer.yml`, and the workflow name was updated to "PR Reviewer for Logs."
> Refactor PR Reviewer for Logs Template name

- components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
- pom.xml
- Updates ballerina version from 1.2.58 to 1.2.59
- Updates libphonenumber version from 7.4.5 to 7.7.5
- Local build with tests succeeded.
> [3.2.x] Update ballerina and libphonenumber versions

- components/micro-gateway-cli/src/main/resources/templates/httpEndpoint.mustache
- components/micro-gateway-cli/src/main/resources/templates/httpEndpointReInit.mustache
- components/micro-gateway-cli/src/main/resources/templates/httpResourceEndpoint.mustache
- components/micro-gateway-cli/src/main/resources/templates/lbEndpointReInit.mustache
- components/micro-gateway-cli/src/main/resources/templates/secureSocket.mustache
- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Fixes https://github.com/wso2/api-manager/issues/3997
Local build with tests succeeded.
> [3.2.x] Add support for dynamic SSL profiles

- pom.xml
$subject
Fixes #
Not Tested
---
> io netty version update

- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/logging/MgwLog4j2ConfigurationFactory.java
Fixes https://github.com/wso2/api-manager/issues/4189
> [3.2.x] Remove warning logs from log4j
