- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/model/BallerinaService.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/service/APIServiceImpl.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/service/bean/APIDetailedDTO.java
- components/micro-gateway-cli/src/main/resources/templates/mock/service.mustache
- components/micro-gateway-core/src/main/ballerina/gateway/annotation.bal
- components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
- distribution/product/resources/conf/micro-gw.conf
- Added CORS annotations to generated ballerina services
- Get authorization header from API , if not from the config file
- Micro gateway apis should be able to restricted with CORS headers and , user should be able to specify any header to provide the access token
> Add cors annotations and auth header configurable

- components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
- distribution/product/resources/conf/micro-gw.conf
> Currently mg binds to localhost by default. This will not work in Docker and K8s environments. Should bind to 0.0.0.0 by default.
> Change Micro GW default bind address to 0.0.0.0

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/HashingConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/exception/HashingException.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/Hash.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/HashUtils.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIDetailedDTO.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIInfoDTO.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ext/ExtendedAPI.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/ApplicationThrottlePolicyDTO.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/SubscriptionThrottlePolicyDTO.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/policy/ThrottlePolicyDTO.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
First time running the setup command, the tool will run normally.
```
$ micro-gw setup -l internal --path /home/malintha/wso2apim/cur/c4mgw/malintha
BALLERINA_HOME environment variable is set to /home/malintha/wso2apim/cur/c4mgw/wso2am-micro-gw-2.5.0-SNAPSHOT/lib/platform
MICROGW_TOOLKIT_HOME environment variable is set to /home/malintha/wso2apim/cur/c4mgw/wso2am-micro-gw-2.5.0-SNAPSHOT
Enter Password: 
```
The exit code for this state will be 0.
```
$ echo $?
0
```
Second time running the command the tool will compare the hashes generated for the previous API/Policy requests. If the server gives the same response for the required attributes the tool notifies the user that there is no change from upstream.
```
$ micro-gw setup -l internal --path /home/malintha/wso2apim/cur/c4mgw/malintha …
```
> Adding hashing based change detection funtionality

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/exception/CLIInternalException.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
- distribution/resources/bin/micro-gw
- tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
Folders "microgw-resources/projects" are removed and the project will be created in the current location inside a folder that has the name of the project specified with -n.
```
$ micro-gw setup -a PizzaShackAPI -v 1.0.0 -n "pizzaproj"
BALLERINA_HOME environment variable is set to /home/malintha/wso2apim/cur/c4mgw/wso2am-micro-gw-toolkit-2.5.0-SNAPSHOT/lib/platform
MICROGW_TOOLKIT_HOME environment variable is set to /home/malintha/wso2apim/cur/c4mgw/wso2am-micro-gw-toolkit-2.5.0-SNAPSHOT
Enter Password for admin: 
Setting up project pizzaproj successful.
No changes received from the server. If you already have a built distribution, it can be reused.
$ tree -L 3
.
└── pizzaproj
├── conf
│   └── label-config.toml
├── src
│   ├── endpoints.bal
│   ├── extension_filter.bal
│   ├── …
```
>  Restructure project generation root location

- components/micro-gateway-cli/src/main/resources/templates/service.mustache
- components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
> In service level we had a annotation to check whether the authentication is enabled. But in gateway auth should be enabled  by default. If disable only we should add the annotation
> Make authorization enable by default in gateway

- components/micro-gateway-cli/src/main/resources/templates/service.mustache
- components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
Provide dynamic backend url setting capability. 
To override production endpoint for an API (Say TestAPI v1) provide following system variable during the startup
`-e TestAPI.v1.prodEndpoints.0="http://wso2.com"`
For sandbox endpoint
`-e TestAPI.v1.sandEndpoints.0="http://wso2.com"`
To set the endpoint using system properties, use following method (replace . with _ in linux environment)
`export TestAPI_v1_prodEndpoints_0="http://wso2.com"`
> Add BE endpoint override capability

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
> Fixed permission issue when clearing write protected files which are generated in first time.
> Add option to forcefully update the project 
ex:
$micro-gw setup -l apimTestLabel -n myProject -s https://localhost:9444/ -u admin -p admin
$[micro-gw: Project name `myProject` already exist. use -f or --force to forcefully update the project directory., Run 'micro-gw help' for usage.]
$micro-gw setup -l apimTestLabel -n myProject -s https://localhost:9444/ -u admin -p admin -f
$Setting up project myProject successful.
> Fixed bugs and improvements

- components/micro-gateway-cli/src/main/resources/templates/service.mustache
- components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
If the backend EP is protected with basic auth, you have to provide credentials related to that endpoint. Use following system variables to define them
`-e TestAPI.v1.basic.username="admin" -e TestAPI.v1.basic.password="admin" `
If username is not defined, username defined in the API (During the API implementation time) will be used.
To set the credentials using system properties, use following method (replace . with _ in linux environment)
`export TestAPI_v1_basic_username="admin"`
`export TestAPI_v1_basic_password="admin"`
> Add basic auth support for backend EP

- components/micro-gateway-cli/src/main/resources/distribution/bin/gateway
System properties can be passed during the gatway startup time. 
ex:
`sh gateway -e BasicAuth.1.0.prod.basic.username=chamila -e BasicAuth.1.0.prod.basic.password=adhi`
> Add capability to pass system variables from outside the startup script

- components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/gateway/uploade_files_timer.bal
- distribution/resources/conf/micro-gw.conf
- tests/src/test/resources/confs/base.conf
- tests/src/test/resources/confs/default-test-config.conf
- tests/src/test/resources/confs/startup.conf
To enable or disable file uploading tasks in a distributed environment with shared file system.
Adding a flag to define as true or false in conf.
Depending on the value, it will activate or deactivate the task.
By default it has been set to true.
> Adding a flag to enable/disable file uploading task.

- components/micro-gateway-cli/src/main/resources/distribution/bin/gateway
When a process is started in background (**sh gateway start**) and when a new process is started again in background (**sh gateway start**), no message is shown. Currently, a new process starts with errors. 
Fix displays "Process already running" message for this scenario
> Fix background process starting issue

- components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
With JWT token, following properties were having null values in authContext.
- consumerKey
- userId
- apiPublisher
- applicationOwner
This PR fixes this issue.
> Fixing null values in authContext for JWTtoken

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
Handle project creation with invalid label scenario. When a project is created with an invalid label, show valid error message on the CLI and delete the partially created project. Same goes to project creation with api name version combination.
> Handle project creation with invalid label scenario

- components/micro-gateway-core/src/main/ballerina/gateway/data_writer.bal
- components/micro-gateway-core/src/main/ballerina/gateway/executiontime_util.bal
- components/micro-gateway-core/src/main/ballerina/gateway/responsetime_util.bal
Avoid using string in JSON format for meta data
> Adding json.toString convertion to metaData.

- components/micro-gateway-cli/src/main/resources/distribution/bin/gateway
Existing sed command only works in gnu-sed. sed comes in MacOS does not support this. Modified to work on both linux and MacOS
> Fix startup memory allocation param issue for MacOS

- components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
- tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/APIInvokeTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/ThrottlingTestCase.java
> Remove JWT token expiry check from the subscription filter
> Refactor integration test util methods
> Add a test for API invocation with expired JWT
> Remove JWT expiry check in Subscription filter

- components/micro-gateway-cli/src/main/resources/templates/service.mustache
- components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/gateway/tokenServices/authorize_endpoint.bal
- components/micro-gateway-core/src/main/ballerina/gateway/tokenServices/revoke_endpoint.bal
- components/micro-gateway-core/src/main/ballerina/gateway/tokenServices/token_endpoint.bal
- components/micro-gateway-core/src/main/ballerina/gateway/tokenServices/user_info_endpoint.bal
- components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
> Ballerina 0.98.1 has a issue in handling requests with expect header. So in this PR we are removing Expect header from request once it reaches the micro gateway. The client will not be responded with 100 continue, only the main response will be sent.
We have created issue at ballerina to get this resolved in future [1]
[1] - https://github.com/ballerina-platform/ballerina-lang/issues/10389
> Workaround to handle expect header at micro-gw

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
> When APIs having names like "ABC-API" or "ABC.DEF", microgateway fails to build since "-,." is not allowed in compile time.
> The fix is to trim such special characters to an allowed character in compile time.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> N/A
> N/A
> N/A
> Fix microgateway building issue with API name having hyphon or dot

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
> microgateway build command output and setup command output successful messages are getting as error output streams. This code change is to fix the issue and get the output as a system out string instead of an error.
> Fixing following issue
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> N/A
> N/A
> N/A
> JDK 1.8
> N/A
> Fix setup and build command output stream issue

- components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
- components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_handler_chain.bal
- components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
This PR adds the support for configuring multiple JWT providers for validating.
To validate JWT tokens offered by multiple issuers.
Microgateway should be able to validate JWT tokens offered by different issuers.
The Microgateway can be configured to allow multiple JWT issuers as follows,
```
[jwtTokenConfig]
providers="provider1,provider2"
[jwtTokenConfig.provider1]
issuer=
audience=
certificateAlias=
trustStore.path=
trustStore.password=
[jwtTokenConfig.provider2]
issuer=
audience=
certificateAlias=
trustStore.path=
trustStore.password=
```
> Add support for multiple trusted JWT providers

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GRPCUtils.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/BalFileGenerationUtils.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/BalGenToolException.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/BalGenerationConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/DescriptorsGenerator.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/OSDetector.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/ProtocCommandBuilder.java
- components/micro-gateway-cli/src/main/resources/templates/clientStub.mustache
- components/micro-gateway-cli/src/main/resources/templates/sample.mustache
Existing micro-gateway does not provide support for gRPC protocol. To include above mentioned benefits to micro-gateway it is required to implement this support into micro-gateway.
Add gRPC support for API micro-gateway.
Approach is to Implement gRPC support for product micro-gateway as a service which supports HTTP requests into gRPC supported ones. In this scenario we have to implement a ballerina service which receives REST requests and convert them to requests that can be identified in endpoint which is a gRPC service. But in this case we don't need to implement new gRPC filers for process request since receiving requests will be treated as REST/HTTP requests. After the filter processing these requests will be converted into gRPC supported ones. Then that converted ones will be sent …
> Add gRPC support for API product micro-gateway 2.x 

- components/micro-gateway-cli/src/main/resources/templates/basicAuth.mustache
- components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
- components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache
> In the current design, when providing values to override endpoints and when defining backend auth credentials,  the config keys contains "." character. Also if the API name consists of characters from other languages such as Chinese, it will be difficult to provide this config keys. So changed the format of config keys to use API ID and replaced "." character with "_" character.
> Changed the relevant mustache files
basicAuth.mustache
lbEndpoint.mustache
failoverEndpoint.mustache
> For username: <API_ID>\_<ENDPOINT_TYPE>\_basic\_username
For password: <API_ID>\_<ENDPOINT_TYPE>\_basic\_username
For lbEndpoint : <API_ID>\_<ENDPOINT_TYPE>\_endpoint\_\<INDEX>
For failoverEndpoint : <API_ID>\_<ENDPOINT_TYPE>\_endpoint\_\<INDEX>
>  Doc has impact
> Change the format of config keys

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/APIConfig.java
Default API support was supported default label based MicroGW flow. However it wasn't available in developer first Approach. This PR introduces default API support for developer first multi swagger branch.
Introduce a modification to the flag -ms.
User must specify a path to json similar to below json.
```json
[
{
"swaggerPath":"/home/anjana/mg-test/swaggers/swag1.json",
"endpoint":"http://0.0.0.0:9091/ser1",
"isDefaultAPI":true
},
{
"swaggerPath":"/home/anjana/mg-test/swaggers/swag2.json",
"endpoint":"http://0.0.0.0:9092/ser2",
"isDefaultAPI":false
},
{
"swaggerPath":"/home/anjana/mg-test/swaggers/swag3.json",
"endpoint":"http://0.0.0.0:9093/ser3",
"isDefaultAPI":true
}
]
> Add default API support for developer first multi-swagger

- components/micro-gateway-cli/src/main/resources/templates/mutualSSL.mustache
- components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/gateway/endpoints/etcd_endpoint.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/mutualSSL_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
- components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_secure_listener.bal
- distribution/resources/conf/micro-gw.conf
> Now we can specify optional values as well configuring mutual ssl. When we specify value as optional if mutual ssl is passed then further authentication will not happen. If mutual ssl is failed then other authentications mechanisms like oauth2, jwt and etc will be checked.
`
sslVerifyClient="optional"
`
> Move the trustStore.path and trustStore.password configs from "[jwtTokenConfig]" to "[listenerConfig]" in micro-gw.conf file
`[listenerConfig]
host="0.0.0.0"
httpPort=9090
httpsPort=9095
keyStore.path="${ballerina.home}/bre/security/ballerinaKeystore.p12"
keyStore.password="ballerina"
trustStore.path="${ballerina.home}/bre/security/ballerinaTruststore.p12"
trustStore.password="ballerina"
tokenListenerPort=9096
`
> Add optional support for Mutual ssl

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
- components/micro-gateway-cli/src/main/resources/templates/main.mustache
- components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
- components/micro-gateway-core/src/main/ballerina/gateway/executiontime_util.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/validation_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/responsetime_util.bal
- components/micro-gateway-core/src/main/ballerina/gateway/utils/analytics_util.bal
- components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
> This is done to improve the performance
> This will read the annotations at service level and resource level during server startup and store them in a global map. Then it will read from the map per request. Earlier the annotations were read per request using reflect API.
> Improve performance of MGW
> Read annotation during start up only

- components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
- components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
- components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_secure_listener.bal
Fixing the following Kubernetes project build issues,
error: src:0.0.0::listeners.bal:69:1: Unable to parse port of the service: secureServiceEndpointConfiguration
error: src:0.0.0::listeners.bal:85:1: Unable to parse port of the service: serviceEndpointConfiguration
> Fixing Kubernetes project build issue.

- distribution/resources/updates/product.txt
- distribution/src/main/assembly/bin.xml
- distribution/src/main/assembly/filter.properties
Fixes: #243
Implement a feasible solution for identifying product version while distribution update. `filter.properties` file should be updated for every release.
> Add product version to filter properties

- components/micro-gateway-cli/pom.xml
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cipher/AESCipherTool.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cipher/AESCipherToolException.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/HashUtils.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/LibHashUtils.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/logging/LogLevelMapper.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/logging/formatters/DefaultLogFormatter.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ZipUtils.java
- distribution/pom.xml
- distribution/resources/bin/micro-gw
- distribution/resources/bin/micro-gw.bat
- distribution/resources/cli-conf/logging.properties
- distribution/src/main/assembly/bin.xml
- distribution/src/main/assembly/platform_zip.xml
- distribution/src/main/assembly/runtime_zip.xml
- pom.xml
- tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
> This will restructure the toolkit lib folder. The existing structure is as follows
wso2am-micro-gw
├── lib
│   ├── platform (b7a platform + Additionally contains toolkit jars and gateway related jars and balos)
│   |__ runtime (b7a runtime + Additionally contains gateway related jars and balos)
The restructured lib folder would be as follows
lib/
├── gateway 
│   ├── balo(Balo files needed to be copied to run time and platform)
│   │   └── wso2
│   │       └── gateway
│   │           └── 0.0.0
│   │               └── gateway.zip
│   ├── cli (Minimum set of jars required initially to run CLI tool)
│   │   ├── commons-lang3-3.5.jar
│   │   ├── slf4j-api-1.7.25.jar
│   │   └── slf4j-jdk14-1.7.25.jar
│   ├── platform (The JAR files which need to be copied into b7a unzipped platform)
│   │ …
> Restructure micro gateway toolkit distribution

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
> Remove hash check calculation before extracting platform and run time. 
> Platform and run time will only be extracted if there is no already extracted folder.
> remove hash check before extracting runtime and platform

- components/micro-gateway-core/src/main/ballerina/gateway/endpoints/throttle_endpoint.bal
- distribution/resources/conf/micro-gw.conf
> Add host name verification skip when publishing to global TM.
> Host name verification skip for throttle data publish for TM

- components/micro-gateway-core/src/main/ballerina/gateway/throttler/tests/emitOnStateChangeTest.bal
- components/micro-gateway-core/src/main/ballerina/gateway/throttler/tests/timeBatchTest.bal
The timeBatch and emitOnStateChange are used in throttling policy streams. Earlier those functions were written as siddhi extensions in java. Later, since the throttling streams are handled by ballerina, it was decided to implement those functions using ballerina. These ballerina unit tests are written to check those functions.
> Writing unit tests for timeBatch and emitOnStateChange

- tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
> Fixes the test failure in swagger based approach due to missing "siddhiruntime"  flag during the build process
> Fix test failures due to missing build time flag siddhi

- distribution/pom.xml
Currently during every release, product zip file is getting deployed to nexus. This is not required
Fix for #426
> Skip deploying product to nexus

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
- components/micro-gateway-cli/src/main/resources/templates/jwtRevocation.mustache
- components/micro-gateway-cli/src/main/resources/templates/main.mustache
- components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/gateway/endpoints/etcd_token_revocation_endpoint.bal
- components/micro-gateway-core/src/main/ballerina/gateway/jwt_authentication_handler.bal
- components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
- components/micro-gateway-core/src/main/ballerina/gateway/revoked_token_map.bal
- components/micro-gateway-core/src/main/ballerina/gateway/services/token_revocation_event_listener.bal
- components/micro-gateway-core/src/main/ballerina/gateway/utils/token_revocation_etcd_util.bal
- distribution/resources/conf/micro-gw.conf
- distribution/resources/filters/token_revocation_extension.bal
- tests/src/test/java/org/wso2/micro/gateway/tests/common/MockETCDServer.java
- tests/src/test/java/org/wso2/micro/gateway/tests/jwtRevocation/JWTRevocationSupportTestCase.java
- tests/src/test/resources/confs/default-test-config.conf
- tests/src/test/resources/testng.xml
Github issue #298 
- Integrating the logic for Microgateway to handle the revoked tokens and then verify each request with these revoked tokens.
- Providing Microgateway with the capability to check the revoked JWT tokens.
- Implementing realtime revoke token retrieval service using JMS listener.
- Implementing persistent revoke token retrieval service using ETCD.
- Adding a separate JWT handler by wrapping current ballerina JWT handler to implement the logic to check revoked tokens.
- Adding extension to handle any custom persistent revoke token retrieval service instead of using default ETCD.
- When an API request comes, first the revokedTokenMap map is read for the particular token, and if the token is found, user will be unauthorized to access the requested resource.
- When an API …
> Token Revocation Feature

- distribution/pom.xml
- docker/Dockerfile
- docker/README.md
> With new ballerina version update we need to maintain a separate base image for micro gateway in order to add siddhi extension related jars
> Create docker base image for micro-gw

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
> extension_filter.bal and token_revocation_extension.bal are given as extensions for API developers. So these files should be outside the generated sources and should be in the project root.
Hence created a new folder called extensions and copied both extension_filter.bal and token_revocation_extension.bal files and refer the extension folder to the generated source.
> moving extension filter and token_revocation_extension out of generated sources

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java
>Fixes #471 
> The interceptor availability is checked by reading the internals of interceptor file using regular expressions.
>It is not further required to have the same name for the interceptor file and the function. In addition, the user can include any number of functions inside an interceptor file.
> The ballerina compilation error occurs due to having two or more declarations of the same function is properly handled by the mircogateway.
> Check the interceptor availability by reading internals of the file. Fixes #471

- components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/gateway/services/throttle_event_listener.bal
- components/micro-gateway-core/src/main/ballerina/gateway/services/token_revocation_event_listener.bal
- distribution/resources/conf/micro-gw.conf
- Previously JMS topic was hardcoded as "jwtRevocation", this PR will add the functionality to read topic from the micro-gw.conf config file.
- JMS listener will be able read the token revocation topic from config
- User should be able to change the token revocation topic name from the config.
- doc has impact
- Token Revocation Feature #420
>  Feature to add token revocation JMS topic from config 

- README.md
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointListDTO.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointListRouteDTO.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
- components/micro-gateway-cli/src/main/resources/templates/basicAuth.mustache
- components/micro-gateway-cli/src/main/resources/templates/basicResourceAuth.mustache
- components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
- components/micro-gateway-cli/src/main/resources/templates/failoverResourceEndpoint.mustache
- components/micro-gateway-cli/src/main/resources/templates/httpEndpoint.mustache
- components/micro-gateway-cli/src/main/resources/templates/httpResourceEndpoint.mustache
- components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache
- components/micro-gateway-cli/src/main/resources/templates/lbResourceEndpoint.mustache
- samples/endpoint_by_reference_sample.yaml
> Support to provide endpoints by reference
`
x-mgw-endpoints:
- myEndpoint:
urls:
- https://petstore.swagger.io/v2
securityConfig:
type: basic
username: roshan
- myEndpoint3:
urls:
- https://petstore.swagger.io/v3
securityConfig:
type: basic
username: rajith
`
We can define endpoint like above and refer them in API level or resource level as below
`x-mgw-production-endpoints: "#/x-mgw-endpoints/myEndpoint"`
> Support for add endpoints by reference in the open API definitions

- distribution/resources/bin/gateway
Trailing `/` in `cp` command's source path behave differently in mac and linux
> runtime: Fix issue in gateway sh

- components/micro-gateway-core/src/main/ballerina/gateway/endpoints/api_gateway_endpoint.bal
- components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
- components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_secure_listener.bal
Add below logs to describe the usage of default gateway ports.
```
[micro-gateway] HTTPS listener started on port 9095
[micro-gateway] HTTP listener started on port 9090
```
> Add startup log for listening ports

- components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
- components/micro-gateway-cli/src/main/resources/templates/failoverEndpointReInit.mustache
- components/micro-gateway-cli/src/main/resources/templates/failoverResourceEndpoint.mustache
- components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache
- components/micro-gateway-cli/src/main/resources/templates/lbEndpointReInit.mustache
- components/micro-gateway-cli/src/main/resources/templates/lbResourceEndpoint.mustache
> Load balance and failover endpoints does not support http2 config during source generation. This PR fixes that issue
> Add http2 template to failover and load balance templates

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
> swagger parser related Jars are not updated with 0.9990.5 release [1]. Hence we have to remove the **swagger-to-ballerina-generator-0.990.5.jar** from code.
[1]. https://github.com/ballerina-platform/ballerina-lang/blob/v0.990.5/pom.xml#L2340
> removes swagger-to-ballerina-generator-0.990.5 jar

- components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
With this fix users can directly push the builded docker image using the k8s deployment config.
User have to specify the "push" value to true as below in the "kubernetes.kubernetesDeployment" config of deployment-config.toml
`    buildImage = true
push = true`
And the user name and password needed to be set as environment variables in order to push the docker image to private registry.
`
export DOCKER_USERNAME=<docker_username>
export DOCKER_PASSWORD=<docker_password>
`
Then users need to execute the build command .
`micro-gw build <project_name> -d <deployment-config.toml_file_path>`
Fix : https://github.com/wso2/product-microgateway/issues/652
mac os , with k8s
---
> Fix #652: K8s push docker image

- components/micro-gateway-core/assembly/balo.xml
- components/micro-gateway-core/assembly/bin.xml
- components/micro-gateway-tools/assembly/bin.xml
- distribution/src/main/assembly/ballerina_runtimes/runtime_zip.xml
- distribution/src/main/assembly/platform_zip.xml
To fix the assembly syntax issue (when running inside Windows) occurred due to starting output directory names with a forward slash.
Related to #665
Windows 10
---
> Fix assembly syntax issue in Windows

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
The interceptor(.bal) name wouldn't be the same as a function name and also they should be exactly mapped to functions in the swagger definition.
If a function name of the swagger definition doesn't map to the interceptor function name, It gives an error like
"The interceptor 'validateRequest' mentioned in openAPI definition:'/Users/hasunie/RD/MC/tst/intercept/api_definitions/openapi.yaml' under path:'/store/order/{orderId}' operation:'get' is not available in the interceptors directory"
Please find the artefacts:
Interceptors directory structure
Interceptors
validateRequest.bal
validateResponse.bal
Swagger difinition:
```yaml
paths:
"/pet/findByStatus":
get:
tags:
- pet
summary: Finds Pets by status
description: Multiple status values can be provided with comma separated strings …
```
> improves the interceptor error message

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
The interceptor(.bal) name wouldn't be the same as a function name and also they should be exactly mapped to functions in the swagger definition.
If a function name of the swagger definition doesn't map to the interceptor function name, It gives an error like
"The interceptor 'validateRequest' mentioned in openAPI definition:'/Users/hasunie/RD/MC/tst/intercept/api_definitions/openapi.yaml' under path:'/store/order/{orderId}' operation:'get' is not available in the interceptors directory"
Please find the artefacts:
Interceptors directory structure
Interceptors
validateRequest.bal
validateResponse.bal
Swagger difinition:
```yaml
paths:
"/pet/findByStatus":
get:
tags:
- pet
summary: Finds Pets by status
description: Multiple status values can be provided with comma separated strings …
```
> fixes for error message: #664

- distribution/resources/bin/micro-gw.bat
Fix the issue of running java command twice during the build command when executed in windows.
Fixes #660
Windows 10
---
> fix the issue of running java command twice during build command

- components/micro-gateway-core/assembly/balo.xml
- components/micro-gateway-core/assembly/bin.xml
- components/micro-gateway-tools/assembly/bin.xml
- distribution/src/main/assembly/ballerina_runtimes/runtime_zip.xml
- distribution/src/main/assembly/platform_zip.xml
To fix the assembly syntax issue (when running inside Windows) occurred due to starting output directory names with a forward slash.
Fixes #665
Windows 10
---
> Fix assembly in windows

- distribution/resources/bin/micro-gw.bat
Fix the issue of running java command twice during the build command when executed in windows.
Fixes #660
Windows 10
---
> avoid Java cmd being executed two times during build Cmd in windows

- components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/gateway/utils/token_revocation_etcd_util.bal
- tests/pom.xml
This PR addresses the following.
- JWT token revocation etcd URL doesn't work if changed from the default value.
- Some debug logs have the wrong key. This is confusing as the logs are printed from a different bal file, but the logs print a different name.
Fixes #680 
Tested
---
> Fix config value name for JWT token revocation with etcd 3.0.x

- components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/gateway/utils/token_revocation_etcd_util.bal
- tests/pom.xml
This PR addresses the following.
- JWT token revocation etcd URL doesn't work if changed from the default value.
- Some debug logs have the wrong key. This is confusing as the logs are printed from a different bal file, but the logs print a different name. 
Fixes #680 
Tested
---
> Fix config value name for JWT token revocation with etcd

- components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
When environement varibles are used in deployment config toml under the "[kubernetes.kubernetesDeployment]" config it gives a build error. This fixes that error and enabled to pass values as environment variables when deploying in k8s
Fixes #693 
K8s
---
> Fix #693 : Error when k8s environment variables used

- pom.xml
Temporary fix for build failure. We need to properly fix this. Disable spotbugs plugin for now.
Fixes #696 
Mac OS
---
> Temporary Fix for #696: Disable spotbugs

- components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/mutualSSL_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
There is an issue when analytics is enabled and http port is used. This is due to not setting the host name to filter context
Fixes #701 
Mac os
---
> Fix #701 : Analytics error when http port is used

- distribution/resources/bin/micro-gw
- distribution/resources/bin/micro-gw.bat
Fix the bug due to returning zero as the exit value when a runtime exception occured during the build process.
Fixes #699 
- Integration tests added:No
Mac OS
---
> Fix: returning 0 as exit code for runtime exceptions during build process

- pom.xml
Jenkins build is failing due to incompatible jenkins/spotbugs versions. This has to be fixed in the jenkins server by a jenkins upgrade. Util that is completed this temporary fix is added to support a jenkins prebuild script which will remove spotbugs plugin definition from pom file before the build.
Fixes #696
Not Tested
---
> Add ignore config for spotbugs in jenkins

- distribution/resources/bin/gateway
- distribution/resources/bin/gateway.bat
- distribution/resources/bin/micro-gw.bat
To resolve the issue when a parameter is provided using "-e" during the gateway start.
In addition, the executable path should be provided with double-quotes. 
>ex: gateway "pathToExecutable"
Fixes #721
Windows 10
---
> Fix the bug when there is an executable path including a space in windows

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Kubernetes.java
- components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
- components/micro-gateway-cli/src/main/resources/templates/kubernetesService.mustache
- components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttp.mustache
- components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttps.mustache
- components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceToken.mustache
- components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
With this PR, we can define k8s service names for the port 9090, 9095, and 9096 seperately. So it will not generate random names when building the project.
We can define the deployment-config.toml as below to specify three k8s services
```toml
[kubernetes.kubernetesServiceHttps]
enable = true
name = "mgw-https"
#labels = ''
#serviceType = ''
#port = ''
[kubernetes.kubernetesServiceHttp]
enable = true
name = "mgw-http"
#labels = ''
#serviceType = ''
#port = ''
[kubernetes.kubernetesServiceToken]
enable = true
name = "mgw-token"
#labels = ''
#serviceType = ''
#port = '
```
And this also supports the existing behaviour , where only one service is defined. Then k8s artifacts will be generated with random k8s service name for the ports 9090, 9095 and 9096
```toml
[kubernetes.kubernetesService] …
```
> Fix #743 : Define k8s service names in deployment toml file

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
- distribution/resources/grpc/wso2CustomOptions.proto
- distribution/src/main/assembly/bin.xml
Following changes are added to the folder structure.
- There is a directory called "grpc_definitions" at the root level of the project. This is the location where the developer should copy the grpc service definitions.
- The protobuf file containing the microgateway extensions is also saved inside the project under the location <project_dir>/grpc_definitions/gen/wso2CustomOptions.proto.
Fixes : #283
> Folder structure changes to execute at init cmd phase

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
1. Creating target directory on initializing a project causes issues in CICD integration. Therefore target directory will be created at the build time of a project.
1. By default Interceptor directory of e mgw project is an empty directory. If such a project is committed into a VCS (git, svn, etc...) other devs building the same project will get build errors since empty directories doesn't get committed to VCS.
Fixes #714 
FIxes #715 
- MacOS
---
> Fix project structure related issues

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
If any custom extensions are provided inside project's extensions directory, those will be copied to target directory as sources for building the project. This make it possible to add additional filters to a specific project. However to make this useful, user will have to update the listeners.bal in TOOLKIT resources.
Fixes #764
- MacOS
- 3.0.2-SNAPSHOT toolkit
- 3.0.1 runtime
---
> Include entire extensions directory in mgw build

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
If any custom extensions are provided inside project's extensions directory, those will be copied to target directory as sources for building the project. This make it possible to add additional filters to a specific project. However to make this useful, user will have to update the listeners.bal in TOOLKIT resources.
Fixes #764
- MacOS
- 3.0.2-SNAPSHOT toolkit
- 3.0.1 runtime
---
> Use all src in extensions dir for build

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
- components/micro-gateway-tools/src/main/go/tools/distribution.go
- distribution/resources/bin/gateway
- distribution/resources/bin/gateway.bat
First run of gateway and toolkit commands take some time due to dist initialization steps (ballerina installation). This can cause confusion in low performing hardwares. We can avoid this confusion by providing a message saying that distribution is initializing. This message will be shown only on first run.
Runtime:
Toolkit:
Fixes #645 
MacOS
---
> Add CLI message for distribution initialization

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
- components/micro-gateway-tools/src/main/go/tools/distribution.go
- distribution/resources/bin/gateway
- distribution/resources/bin/gateway.bat
First run of gateway and toolkit commands take some time due to dist initialization steps (ballerina installation). This can cause confusion in low performing hardwares. We can avoid this confusion by providing a log saying that distribution is initializing. This message will be shown only on first run.
Runtime:
Toolkit:
Fixes #645
MacOS
---
> Add distribution init log

- distribution/resources/bin/micro-gw
- distribution/resources/bin/micro-gw.bat
Default ballerina output of build command gives a confusing output about the generated build artifacts. This was changed by introducing new build status message after the build.
Fixes #687 
MacOS
---
> Change build command output

- distribution/resources/bin/gateway.bat
- distribution/resources/bin/micro-gw
- distribution/resources/bin/micro-gw.bat
If ballerina is already installed in host machine, that version of ballerina was used to execute ballerina commands ignoring the embedded ballerina version. This PR will fix it.
Fixes #810 
MacOs
Windows server 2012 R2
---
> Avoid use of extenal ballerina installation

- distribution/resources/bin/gateway.bat
- distribution/resources/bin/micro-gw
- distribution/resources/bin/micro-gw.bat
Embedded ballerina version was ignored if ballerina installation was found in the host machine. This causes compatibility issues with the micro-gw. This PR fix this issue by specifically using embedded ballerina version.
Fixes #810
MacOS
Windows Server 2012 R2
---
> Avoid use of host ballerina installation

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
This fixes the NPE when standard openAPI is used. This will give the error message to the user to inform to add minimum extensions to the swagger.
Fixes #827
Not Tested
---
> Fix #827 - NPE when open API used without wso2 extensions

- components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/gateway/utils/etcd_util.bal
ETCD base path is hardcoded in mgw. It will not work with lates etcd versions
Fixes #830 
Not Tested
---
> Fix #830: ETCD base path hard coded issue

- docker/Dockerfile
Creates the mgw base docker images using the mgw binary distribution , rather than using the b7a base image
Fixes #842 
Not Tested
---
> Update microgw docker file

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaPath.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
Standard open API without wso2 specific vendor extensions should be allow to create micro gateway projects.
From the PR we supports 
Open API v3 - servers object to get the production endpoints and base path
Open API v2 - scheme, host, base path objects to get the base path and production endpoints
Fixes #847
Not Tested
---
> Fix #847 - Support open API without extensions

- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
- distribution/resources/conf/micro-gw.conf
With this PR subscription validation can be made configurable for the jwt authentication.
We can use the following config of the micro-gw.conf
[jwtTokenConfig]
issuer="https://localhost:9443/oauth2/token"
audience="http://org.wso2.apimgt/gateway"
certificateAlias="wso2apim"
**validateSubscription=false**
Fixes #837 
Not Tested
---
> Fix #837 - Subscription validation configurable

- components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
When sending requests with "Authorization" header with empty value it gives an error without sending the proper error response. This fixes that issue
Fixes #871 
Not Tested
---
> Fix #871 - Error when empty authorization header is provided

- pom.xml
- tests/pom.xml
This PR contains a ballerina patch version upgrade. Basically the upgrade contains two fixes.
1. When rest resource is defined line /pet/{petId} and if the request petId=1/1 then micro gateway sends a 404. Even encoding the path parameter does not works.
2. When squid proxy is used to connect with back end , and ssl bump is enabled in the squid proxy, then micro gateway requests the certificate of the proxy during the ssl handshake. This is due to an issue in the netty transport which was fixed in lates netty version. So the ballerina upgrade contains the netty version update as well. 
Fixes #874 , #875
Not Tested
---
> Fix issue in proxying with ssl bump and path parameters containing special characters

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ResetCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
- components/micro-gateway-cli/src/main/resources/cli-help/cli-help.help
- components/micro-gateway-cli/src/main/resources/cli-help/cli-reset.help
- distribution/resources/cli-conf/toolkit-config.toml
Disable cors configuration enabled in toolkit-config.toml . By default the cors config will be disabled
Reset command completely resets the toolkit-config.toml. But it should only resets the user credentials only
Fixes #879 #880 
Not Tested
---
> Fix #879 #880 - Disbale cors by default and improve reset command

- components/micro-gateway-cli/src/main/resources/templates/main.mustache
- components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
- components/micro-gateway-core/src/main/ballerina/gateway/annotation.bal
- components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/authz_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/mutualSSL_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/filters/validation_filter.bal
- components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
/token, /revoke and etc endpoints are exposed via 9096 port in mgw. Which is different from 9095 port where the api requests are served. We need to expose token services also using 9095 port in scenarios like when the ssl termination happens at the gateway level, then routing to relevant port will be difficult from an load balancer
Fixes #896
MacOS
---
> Fix #896 - Expose token, revoke endpoints in 9095 port

- components/micro-gateway-cli/src/main/resources/templates/main.mustache
- components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
- components/micro-gateway-core/src/main/ballerina/src/gateway/annotation.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
/token, /revoke and etc endpoints are exposed via 9096 port in mgw. Which is different from 9095 port where the api requests are served. We need to expose token services also using 9095 port in scenarios like when the ssl termination happens at the gateway level, then routing to relevant port will be difficult from an load balancer
Fixes #896 
Not Tested
---
> Fix #896 jballerina - Expose token, revoke endpoints in 9095 port

- pom.xml
- tests/src/test/java/org/wso2/micro/gateway/tests/resource/GH884PathParamWithSuffixTestCase.java
- tests/src/test/resources/openAPIs/resource/884_path_param_suffix.yaml
- tests/src/test/resources/testng.xml
* Enable adding resources with suffixes starting with `.`. Ex: `/petstore/pet/{petId}.api`
* Fix issue when calling APIs from external network.
Fixes #884 
Fixes #891 
MacOS
---
> Fixes and tests for #884 and #891

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
Ballerina doesn't like it when ballerina.toml contains Windows path separator '\' in library paths. Therefore we need to convert widows path separator `\` to `/` to make ballerina work on windows
Fixes #930
MacOS
Windows Server 2016
---
> Build command fails on windows

- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
- distribution/resources/conf/default-micro-gw.conf.template
Removing authentication header when configuration removeAuthHeaderFromOutMessage is enabled.
Fixes #https://github.com/wso2/product-microgateway/issues/1025
catalina
---
> Remove authorization header

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
- components/micro-gateway-cli/src/main/resources/templates/service.mustache
Fix the compilation error, when the backend security is applied only in the resource level. This was due to a bug in ballerina code generation using mustache files.
Fixes #1040 
MacOS Mojave
---
> Fix the issue when the backend security is applied only for resources

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesDeployment.java
- components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
- distribution/resources/bin/gateway
When user specify the micro-gw.conf as a config map in the deployment.toml file when generating the k8s artifacts, gateway pods are not starting due to , conf is mounted as the /home/ballerina/conf/ballerina.conf. But gateway shell script try to find the conf file in /home/ballerina/conf/micro-gw.conf.
In this fix we are taking the /home/ballerina/conf/ballerina.conf as the conf file if it is present. Only wat this is going to present is , specify this as a config map[1] in the deployment.toml
```toml
[kubernetes.kubernetesConfigMap]
enable = true
ballerinaConf = 'Documents/MGW/jballerina/wso2am-micro-gw-toolkit-macos-3.1.0-beta-SNAPSHOT/resources/conf/micro-gw.conf'
```
Fixes #1059 
Not Tested
---
> Fix #1059 - Issues running in k8s

- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
- distribution/resources/cli-conf/toolkit-config.toml
- tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
- tests/src/test/resources/confs/default-cli-test-config.toml
This issue happens, due to ballerina authz filter getting called from ballerina authn filter. But when used opaque tokens the key validation service call to external KM does validates the scopes. So ballerina authz filter again trying to validate the scopes causing the issue. Here we are trusting the validation done by external key validation service and forcefully make the ballerina authz filter scope validation successful.
Once the issue https://github.com/ballerina-platform/ballerina-lang/issues/21376 is fixed, we can remove this logic.
> And also this PR update the default rest versions of the toolkit config to work with APIM 3.1.0
Fixes #1048 
Not Tested
---
> Fix #1048 - Scope issue with opaque tokens

- distribution/pom.xml
- distribution/src/main/assembly/linux_bin.xml
- distribution/src/main/assembly/macos_bin.xml
- distribution/src/main/assembly/windows_bin.xml
We no longer need to pack docker, k8s ballerina libs manually into toolkit. New ballerina distribution downloaded from b7a product dist contains both these libs.
Task
Not Tested
---
> Remove docker k8s libs from toolkit

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIDetailedDTO.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
- components/micro-gateway-cli/src/main/resources/templates/caching.mustache
Introduces the open API extension for response caching enable and disable. Explained in the issue #929 
Fixes #929 
Not Tested
---
> Fix #929 - Enbale response caching open API extension

- tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointOverrideTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointWithSecurityTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointsByReferenceTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/MultipleEndpointsTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/extensions/OASAPIInvokeTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/http2/HTTP2RequestsWithHTTP1BackEndTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/http2/HTTP2RequestsWithHTTP2BackEndTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithBasicAuthTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuth2andBasicAuthTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuthTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/security/AuthenticationFailureTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/security/DisableSecurityAndCustomAuthHeaderTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/security/MutualSSLTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/security/ScopesTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/throttling/OpenApiThrottlingTestCase.java
- tests/src/test/resources/openAPIs/endpoints/endpoint_override.yaml
- tests/src/test/resources/openAPIs/endpoints/endpoint_security.yaml
- tests/src/test/resources/openAPIs/endpoints/load_balance.yaml
- tests/src/test/resources/testng.xml
Reduce the integration test running time. This will reduce the total number of project builds from 23 to 13.
Fixes #1116 
Not Tested
---
> Fix #1116 - Reduce integration test running time

- distribution/pom.xml
change previous regex expression in order to replace the version.txt file in every build. previous regex replace the text only once. 
Fixes #839
Not Tested
---
> Fix #839 - Need a way find toolkit/runtime version - Update regex #1130 

- distribution/resources/bin/gateway
- distribution/resources/bin/micro-gw
Fix the issue if the toolkit extracted in a path where it contains spaces, or the project is created in a path where it contains the spaces.
Fixes #1056 
Not Tested
---
> Fix #1056 - Toolkit fails when toolkit path contains spaces

- components/micro-gateway-cli/pom.xml
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
- components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
- components/micro-gateway-cli/src/main/resources/templates/main.mustache
- components/micro-gateway-core/pom.xml
- components/micro-gateway-core/src/main/ballerina/src/gateway/native/callHome.bal
- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/callhome/Callhome.java
- distribution/pom.xml
- distribution/resources/updates/product_linux.txt
- distribution/resources/updates/product_macos.txt
- distribution/resources/updates/product_windows.txt
- distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
- distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
- distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
- distribution/src/main/assembly/linux_bin.xml
- distribution/src/main/assembly/macos_bin.xml
- distribution/src/main/assembly/windows_bin.xml
- pom.xml
$Subject as this will Introduce CallHome feature for micro-gw toolkit and runtime.
toollkit: invoke callhome  while building the project
runtime: invoke callhome  when starting the micro-gw
Fixes #
Not Tested
---
> Add callhome feature for micro-gw toolkit and runtime

- components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/responsetime_util.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
If there is an issue due to a filter failure, then that should be skipped in the analytics response path. We need to set the correct attribute to invocation context and read it in the analytics response path.
Fixes #1039 
Not Tested
---
> Fix #1039 - Analytics error when authentication fails

- distribution/resources/bin/gateway.bat
Windows runtime was failing to start when %GW_HOME% path contained spaces. This PR will fix it
Fixes #428 
Windows Server 2016
---
> Fix for windows runtime when path contains spaces

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
There can be test failures due to call home is running in separate thread and not returning the proper exit code. We need to make sure program exits with correct exit code
Fixes #
Not Tested
---
> Make call home function run asynchronously with time out

- components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
- components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Entity.java
- components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Request.java
- components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Response.java
- tests/src/main/java/org/wso2/micro/gateway/tests/interceptor/TestInterceptor.java
- tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
- tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/JavaInterceptorTestCase.java
This will fix the following issues
- add new method to set and get json array objects using java interceptors
- Fix the issue of subscription validation failure when apis are push to APIM using apictl
- Fix the caching issue when used oauth2 opaque tokens
Fixes #1150 
Fixes #1162 
Fixes #1164 
Not Tested
---
> Fix #1150 #1162 #1164 - Java interceptor json array, oauth2 context missmatch and caching issues

- components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
There was an issue when multiple JMS subcribers (two mgw nodes) trying to connect to same TM for distributed throttling. Changing the subscriber type fixes the issue.
Fixes #1227 
MacOS
---
> Fix multiple jms subscription

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/ContainerConfig.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Filter.java
- components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
With this fix specifying custom filters are supported. Developer can define custom filters and the position of that filter[1] in the filter chain in the deployment-config.toml, and then
add that filter inside the extension folder of the project.
[1]  - 
```toml
[[filters]]
name = "CustomFilter"
position = 5
[[filters]]
name = "CustomFilterNew"
position = 2
```
Fixes #1181 
Fixes #1184 
Not Tested
---
> Fix #1181 #1184 - Support adding custom filters

- components/micro-gateway-cli/src/main/resources/templates/service.mustache
- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
- tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
- tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
- tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointWithSecurityTestCase.java
- tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointsByReferenceTestCase.java
- tests/src/test/resources/openAPIs/endpoints/endpoint_security.yaml
Avoid MGW from sending its own auth failure responses when backends and interceptors respond with auth failures.
Fixes #1233
MacOS
---
> Avoid overriding backend auth responses

- components/micro-gateway-interceptor/pom.xml
- components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/ConfigUtils.java
- components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/InterceptorUtils.java
- pom.xml
- tests/src/main/java/org/wso2/micro/gateway/tests/interceptor/ConfigInterceptor.java
- tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/JavaInterceptorTestCase.java
- tests/src/test/resources/openAPIs/interceptor/interceptor.yaml
This PR will provide set of utility methods to read configurations from java interceptors.
Fixes #1261 
Not Tested
---
> Fix #1261 - Support reading configurations from interceptor library

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
- components/micro-gateway-cli/src/main/resources/templates/generateSwagger.mustache
If imported APIs are available in the project, api_definitions directory should not be mandatory for the micro-gw build.
Fixes #1194
MacOS
---
> Make api_definitions optional for build

- components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/AbstractMGWJWTGenerator.java
Removing padding created from base64 URL encoding in the generated token.
Fixes #1277 
---
> Fixed the Base64 encoding padding issue

- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/blocking_condition_retriever_task.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/key_template_retriever_task.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
- components/pom.xml
- distribution/resources/conf/default-micro-gw.conf.template
This is a temporary fix for oauth2 opaque token validation issue. Since there is additional parameters expected by the wso2 APIM key validation service.
This also fixes the API level throttling when global TM is used.
Fixes #1279 
Fixes #1280 
Not Tested
---
> Fix #1279 #1280 - opaque token validation issue and API level throttling

- components/micro-gateway-cli/src/main/resources/templates/main.mustache
- components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/api_data_store.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/key_mapping_store.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_data_provider.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_dtos.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/subscription_data_store.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/services/gateway_jms_listener.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
- distribution/resources/conf/default-micro-gw.conf.template
- distribution/resources/conf/micro-gw.conf
Add tenant wise data store configurations
Include the following pilot configrations
```toml
[apim.eventHub]
enable = false
service_url = "https://localhost:9443"
internalDataContext="/internal/data/v1/"
username="admin"
password="admin"
eventListeningEndpoints = "amqp://admin:admin@carbon/carbon?brokerlist='tcp://localhost:5672'"
listOfTenants = ["carbon.super"]
```
Fixes #1258 
Not Tested
---
> Fix #1258 - Add tenantwise data stores in mgw side

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Fixes the API name modification issue during the code generation process. '_' are being replaced by '-' and API names are split by '__'. This PR fixes that issue.
Fixes #1264
OS: Ubuntu  - 18.04
JDK: 1.8.0_251
---
> Fixes the api name replacement issue in microgateway.

- components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/api_data_store.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/key_mapping_store.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_data_provider.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/subscription_data_store.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
After checking the subscription dat in data stores if they are not available we need to a service call and check whether the subscription dat is updated in the database.
This service call is done due to following reasone
1. If the jms message is dropped upon new subscription addition.
2. If a request comes before subscription data is pulled during the startup.
Fixes #1258 
Not Tested
---
> Fix #1258 - Add individual service calls when validating subscriptions

- components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
When validating subscription, if the subscribedAPIs claim has the matching API name and the version as * in jwt/apikey; consider that subscription validation is successful.
Fixes #1323
Catalina
---
> Fix version * subscribed apis validation

- components/micro-gateway-core/src/main/ballerina/src/gateway/jwt_generator/jwt_gen_util.bal
- components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/MGWJWTGeneratorImpl.java
Fix the issue where the API name property and the API tier (when the tier is unlimited) is not populated in the backend JWT. 
Fixes #1196
MacOS Mojave
---
> populate api tier and api name in backend jwt header

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
Fix the swagger parsing issue when the api definition file has spaces in the file name.
Fixes https://github.com/wso2/product-microgateway/issues/1292
Not Tested
---
> Read the api definition content and pass in to the OpenAPIV3Parser.

- distribution/resources/conf/default-micro-gw.conf.template
- distribution/resources/conf/micro-gw.conf
The external key manager config is no longer being used. Hence removing it.
Fixes https://github.com/wso2/product-microgateway/issues/1351
Not Tested
---
> Remove the external key manager configuration.

- components/micro-gateway-cli/src/main/resources/policies/throttle_policy_initializer.bal
- components/micro-gateway-cli/src/main/resources/templates/main.mustache
- components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
- distribution/resources/conf/default-micro-gw.conf.template
The current future<()> usage does not provide true asynchronous functionality when the gateway starting up. This PR fixes this issue and introduces async jms connection initialization.
Fixes https://github.com/wso2/product-microgateway/issues/1348
Not Tested
---
> Make the jms and throttle publishers start asynchronously.

- components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
With this PR users can access the mgw internal cache objects as  below
```ballerina
gateway:APIGatewayCache apiGwCacheObject = gateway:getCacheObject();
//ex getting the introspect cache
cache:Cache introspectCache = apiGwCacheObject.getIntrospectCache();
```
Similarly other caches can be accessed using below method
```ballerina
getJWTCacheForProvider() // jwt cache
getApiKeyCache() // api key cache
getJwtGeneratorCache() // back end jwt generator cache
```
Fixes #1263 
Not Tested
---
> Fix #1263 - ballerina methods to acces gateway internal cache objects

- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/globalthrottle/databridge/agent/conf/AgentConfiguration.java
In windows, in the truststore path, the '\' character is replaced. 
`C:\User\Menaka\wso2-mgw-3.2.0\bin => C:UserMenakawso2-mgw-3.2.0`
This has led to SSL connection issues and affected the distributed throttling scenarios. 
This PR fixes this issue.  
Fixes https://github.com/wso2/product-microgateway/issues/1358
Not Tested
---
> Fix replacing '\' in truststore path in windows.

- components/micro-gateway-cli/pom.xml
- components/micro-gateway-core/pom.xml
- components/micro-gateway-interceptor/pom.xml
- components/micro-gateway-jwt-generator/pom.xml
- components/micro-gateway-jwt-transformer/pom.xml
- components/micro-gateway-tools/pom.xml
- components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/GetConfig.java
- components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/Main.java
- components/pom.xml
- distribution/pom.xml
- distribution/resources/bin/gateway
- distribution/resources/bin/gateway.bat
- tests/pom.xml
Startup tool lib was only reading the `jmx_port` config from the config file. When config is provided as program arg or env variable it was not picked up.
This fix will enable looking up for both program args and env vars for the configuration. This is implemented in the tool lib to make logic generic for both *nix and windows platforms.
Fixes #1201
MacOS
---
> Read jmx_port from args and env

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
- components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/revocation/revoked_jwt_retriever_task.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/revocation/revoked_token_map.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/callhome/Callhome.java
- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/jwt/generator/MGWJWTGeneratorInvoker.java
- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/mutualssl/LoadKeyStore.java
This PR fixes multiple issues.
1. JWT revocation does not work with APIM 3.1.0 due to the below reasons.
- Payload parameters are different
- JMS payloads are different
This PR fixes this issue and enables to use JWT revocation with APIM 3.1.0 and MGW 3.2.0
2. JWT generation fails due to path issues in Windows.
Fixes #1364
Fixes #1369
Unit tests added: Yes/No
Integration tests added: Yes/No
Not Tested
---
> Fix JWT revocation not working with APIM 3.1.0

- distribution/resources/bin/gateway
- distribution/resources/bin/gateway.bat
Set the ballerina thread pool size to 100 in order to enhance performance. In addition, users can override this configuration by providing the environmental variable.
`export BALLERINA_MAX_POOL_SIZE=50`
Fixes #
MacOS Mojave
---
> Set the ballerina thread pool size to 100

- envoy.yaml
- internal/pkg/mgw/mgw.go
- internal/pkg/oasparser/configGenerator.go
- internal/pkg/oasparser/envoyCodegen/httpFilters.go
- internal/pkg/oasparser/envoyCodegen/listener.go
- internal/pkg/oasparser/envoyCodegen/routesWithClusters.go
- internal/pkg/oasparser/models/envoy/envoyNode.go
- resources/apis/test2.yaml
Currently the control plane has implemented using v2 apis. But envoy will deprecated v2 apis from q4 in 2020. As $subject this will migrate to control plane xds v2 apis to v3. and also replace all the deprecated configurations.
When migrating to v3 apis, I have done the follwing steps.
- Migrate transport apis to v3 [1]
- Migrate resource apis to v3 [1]
- Change the boostrap configs to v3 [2,3]
[1] -  https://www.envoyproxy.io/docs/envoy/latest/faq/api/envoy_v3
[2] -  https://www.envoyproxy.io/docs/envoy/v1.14.1/configuration/overview/xds_api.html?highlight=transport_api_version#grpc-streaming-endpoints
[3] - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/config_source.proto.html?highlight=resource_api_version
Fixes #1297
- Integration tests …
> Migrate xds apis to v3

- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
- distribution/resources/conf/default-micro-gw.conf.template
> Makes microgateway server header in the response configurable. But still the server header can not be removed.
> Fix issue of key type is not setting when third party jwts are used. When 3rd party jwts are used default key type should be `PRODUCTION`
Fixes #1415 
Fixes #1435 
Not Tested
---
> Make server header configurable and issues in 3rd party jwts

- components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_dtos.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/key_template_retriever_task.bal
When keytemplate is updated (redeployed) in APIM order of the jms messages received by mgw is not guaranteed. If first msg is a 'add' and the next one is a 'remove', updated keyemplate is lost in mgw side. To resolve this we sync the msg order by looking at the jms msg timestamp.
Fixes #1433
Not Tested
---
> Fix inconsistency when updating APIM custom throttling policies

- adapter/pom.xml
- developer-guide.md
- enforcer/pom.xml
- remove-containers.sh
- resources/docker-compose.yaml
- router/pom.xml
Prepare for 4.0.0-m1 release.
Task
MacOS
---
> Prepare for 4.0.0-m1 release

- enforcer/src/main/resources/Dockerfile
Change the enforce base image to alpine based open jre 11 image.
Fixes Task
Not Tested
---
> Change enforcer imgae to alpine base image

- pom.xml
- test/test-integration/pom.xml
- test/test-integration/src/test/java/org/wso2am/micro/gw/tests/apiDeploy/APiDeployTestCase.java
- test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/ApiDeployment.java
As $subject, this will change the failsafe plugin to the surefire plugin and from this, we can define the preserved order for the test classes.
Fixes #1522
Not Tested
---
> [Envoy-MGW]  Change failsafe plugin to surefire to run test cases in integration tests

- pom.xml
This PR fixes processing headers as trailer headers when an HTTP/2 upstream responds with an empty body by bumping the ballerina version.
Fixes https://github.com/wso2/product-microgateway/issues/1528
> Bump ballerina version

- adapter/config/mgwtypes.go
- adapter/pkg/api/restserver/config_restapi.go
- resources/conf/config.toml
Refactor the adapter related configuration such that REST Server configuration is moved into a separate tag called `adapter`.
Support Multiple Users to deploy APICTL projects. (earlier it was single user). 
Hence the configuration would be changed as follows.
```
[adapter]
[adapter.server]
host = "0.0.0.0"
port = "9843"
publicKeyPath = "/home/wso2/security/localhost.pem"
privateKeyPath = "/home/wso2/security/localhost.key"
[[adapter.server.users]]
username = "admin"
password = "admin"
```
Fixes #1548 
MacOS Mojave
---
> Support Multiple Users to deploy APICTL projects

- adapter/pom.xml
- developer-guide.md
- distribution/pom.xml
- enforcer/pom.xml
- pom.xml
- remove-containers.sh
- resources/docker-compose.yaml
- router/pom.xml
- test/mock-backend-server/pom.xml
- test/pom.xml
- test/test-integration/pom.xml
Prepare for 4.0.0-m1 release.
Task
MacOS
---
> Prepare for 4.0.0-m3 release

- adapter/pkg/xds/xds_server.go
Add the openapi v2 struct to map assignment. Fixes #1580 
---
> Fix Open APIv2 struct issue

- enforcer/pom.xml
- enforcer/suppressions.xml
- test/pom.xml
task
Encountered following errors when building the project.
1. org.wso2.micro.gateway.enforcer: Failed during checkstyle execution: There are 2704 errors reported. 
sol: exclude gen folder from checkstyle check.
2. javadoc: error - No source files for package org.wso2am.micro.gw.mockbackend
sol: exclude test package from javadoc
catalina
---
> Fix checkstyle and javadoc issues

- pom.xml
Fixes issues in the release build.
1. Exit code: 1 - javadoc: error - The code being documented uses packages in the unnamed module, but the packages defined in https://docs.oracle.com/en/java/javase/11/docs/api/ are in named modules.
Catalina 
---
> Fix javadoc issue

- adapter/pkg/oasparser/configGenerator.go
- adapter/pkg/oasparser/model/mgwResource.go
- adapter/pkg/oasparser/model/mgwSwagger.go
- adapter/pkg/oasparser/model/mgwSwagger_internal_test.go
- adapter/pkg/oasparser/model/openApi.go
- adapter/pkg/oasparser/model/swagger.go
- adapter/pkg/xds/xds_server.go
1. Fixes #1621 - Replace multiple API maps (swagger2, swagger3, websocket) with one API map (existing mgwSwagger)
2. Rename vendorExtensible to vendorExtensions
3. Update apiMapKey to vhost:name:version
- Unit tests updated: Yes
---
> [envoy-gw] Refactor update API

- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnvVarConfig.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/Constants.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApiDiscoveryClient.java
- resources/docker-compose.yaml
If xds message is larger than the default 4MB. Enforcer will be killed during larger stream messages such as API discoveryresponse.
Fixes #1632
Tested on Mac with default docker compose
---
> Configure max inbound msg size for xds

- enforcer/pom.xml
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/config/APIConfig.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/APIConstants.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/grpc/ExtAuthService.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/grpc/interceptors/AccessLogInterceptor.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/AuthFilter.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/AuthServer.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/FilterUtils.java
- enforcer/src/main/resources/Dockerfile
- resources/conf/log4j2.properties
In the log4j2.properties file following logger is added.
```
logger.mgw-enforcer-interceptors.name = org.wso2.micro.gateway.enforcer.grpc.interceptors
logger.mgw-enforcer-interceptors.level = INFO
logger.mgw-enforcer-interceptors.additivity = false
logger.mgw-enforcer-interceptors.appenderRef.rolling.ref = MGW_ACCESS_LOG
```
By default access logs will not prints. By making the value `logger.mgw-enforcer-interceptors.level` to `DEBUG` in the above config will enable access logs without restarting the enforcer.
The access log format will be as follow. It will print the `server time`, `trace Id from envoy`, `gRPC service method`, `gRPC status code`, `response time`
```
[2021-02-19 07:48:49,505] - 5920896249661898188 envoy.service.auth.v3.Authorization/Check 16 34
[2021-02-19 07:48:52,592] - …
```
> Fix #1648 - Enable Access logs for the enforcer

- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/config_dtos/server_config.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/gateway_conf.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
- distribution/resources/conf/default-micro-gw.conf.template
This PR adds the configurations to preserve headers in the request/responses without any intermediate change in microgateway.
By adding the header properties under `server.headerConf` config, you have the ability to preserve headers by setting the config `preserveHeader` to true. Furthermore, by setting `preserveHeader` to false and adding the desired value to `overrideValue` config, you have the capability to override a header in request/response.
```
[server]
[[server.headerConf]]
headerName = "User-Agent"
preserveHeader = true
overrideValue = "ballerina"
[[server.headerConf]]
headerName = "Server"
preserveHeader = true
overrideValue = "ballerina"
```
Fixes https://github.com/wso2/product-microgateway/issues/1558
Ubuntu 20.04 LTS, OpenJDK 1.8.0_275
> Add configurations to preserve headers

- distribution/resources/bin/gateway.bat
Addresses the issue where the JAVA_ARGS parameter is not properly set in the batch script. (gateway.bat). The reason is that when some environmental variable is set and executed within parentheses of the if/else block, the execution command does not get the environmental parameter. Hence the setting environmental variable and being called should be separated.
Fixes #1502
- Unit tests added:No
Windows 10
---
> fix java_args not being set during the startup of gateway batch script

- pom.xml
- test/test-integration/pom.xml
When running integration tests we have to manually pull the testcontainers/ryuk:0.3.0 image.
With the fix it is pulled during the build process
Fixes Task
Not Tested
---
> Fix tests issues due to the absence of ryuk image

- resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml
- resources/k8s-artifacts/mg-adapter/deployment.yaml
- resources/k8s-artifacts/mg-enforcer/deployment.yaml
- resources/k8s-artifacts/mg-router/deployment.yaml
$subject
```
$ apictl init petstore --oas https://petstore.swagger.io/v2/swagger.json
Initializing a new WSO2 API Manager project in /Users/renuka/git/product-microgateway/distribution/target/wso2am-micro-gw-4.0.0-m7/resources/k8s-artifacts/petstore
Project initialized
Open README file to learn more
$ apictl mg deploy --host https://localhost:30200 --file petstore  -u admin -p admin -k
Successfully imported API.
$ curl -X GET "https://localhost:30201/v2/pet/1" -H "accept: application/json" -H "Authorization:Bearer $TOKEN" -k
{"id":1,"category":{"id":1,"name":"Dog"},"name":"Butch","photoUrls":[],"tags":[],"status":"available"}
$ k get po
NAME                           READY   STATUS    RESTARTS   AGE
mg-adapter-8564898c65-x55hn    1/1     Running   0          78s …
```
> Update K8s configs for MG 4.0.0-m7

- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/RequestContext.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/api/RestAPI.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/grpc/ExtAuthService.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleConstants.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleDataHolder.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleFilter.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleUtils.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/dto/Decision.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/FilterUtils.java
- integration/test-integration/src/test/resources/jwtGenerator/config.toml
Retry-After header in a throttled response defines when the resource is available again for accepting requests. Also this commit updates the tier/level selection logic for API & Res levels. If API level tier is defined we don't do resource level throttling and only perform API level throttling.
Fixes #1534 
Not Tested
---
> Add Retry-After header to throttle response

- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/ThrottleAgentConfigDto.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/ThrottlePublisherConfigDto.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/databridge/publisher/ThrottleDataPublisher.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/databridge/publisher/ThrottleDataPublisherPool.java
`[enforcer.throttling.publisher].password` was not resolved from env variables due to invalid pkg structure of a config dto. This was fixed by moving the config dto to correct pkg.
Fixes #1767
Not Tested
---
> Resolve throttle publisher pwd from env vars

- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/EnvVarConfig.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/Constants.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApiDiscoveryClient.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApiListDiscoveryClient.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationDiscoveryClient.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/KeyManagerDiscoveryClient.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/RevokedTokenDiscoveryClient.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/SubscriptionDiscoveryClient.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ThrottleDataDiscoveryClient.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/scheduler/XdsSchedulerManager.java
- enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/GRPCUtils.java
Fix issue of enforcer does not reconnect after adapter restart.
Fixes #1800 
Not Tested
---
> Fix #1800 - Enforcer reconnect after adapter restart

- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
This pr fixes the ArryIndexOutOfBound exception in enforcer in the first request with JWT generation is enabled.
Fixes https://github.com/wso2/product-microgateway/issues/1829
Not Tested
---
> Fix IndexOutofBound Exception in the first api call with JWT generation

- adapter/internal/messaging/throttle_data_listener.go
Blocking condition events have three states.
- true (created/enabled)
- false (disabled)
- deleted (policy deleted)
Removing a blocking condition from `/admin` portal was not reflecting in enforcer throttle data map due to incorrect evaluation of above `delete` throttle event. This PR fixes it.
Fixes #1838
Mac
---
> Handle deletion of blocking conditions

- enforcer/pom.xml
Remove  org.json:json dependency from shaded jar and use org.json.wso2 dependency
Task
Not Tested
---
> Remove org.json from shade jar and pack json.wso2 to docker image

- adapter/internal/messaging/connection.go
PR will logs the retry interval in each attempt
Related PR https://github.com/wso2/product-microgateway/pull/1864
OutPut: When retries='10' and connectdelay='30' seconds 
```
adapter_1   | 2021-04-08 09:49:54 INFO [throttle_data_listener.go:110] - [messaging.handleThrottleData] [-] handle: deliveries channel closed
adapter_1   | 2021-04-08 09:49:54 ERRO [connection.go:49] - [messaging.(*Consumer).reconnect] [-] CRITICAL: Connection dropped for tokenRevocation, reconnecting...
adapter_1   | 2021-04-08 09:49:54 ERRO [connection.go:49] - [messaging.(*Consumer).reconnect] [-] CRITICAL: Connection dropped for keymanager, reconnecting...
adapter_1   | 2021-04-08 09:49:54 INFO [revoked_token_listener.go:46] - [messaging.handleTokenRevocation] [-] handle: deliveries channel closed
adapter_1   | …
```
> Adding retry interval logs for every attempt when adapter connection retry happens with control plane

- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/Authenticator.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/UnsecuredAPIAuthenticator.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/jwtValidator/JwtTestCase.java
This Pr will add the www-authenticate header to authentication failed responses 
Fixes https://github.com/wso2/product-microgateway/issues/1713 https://github.com/wso2/product-microgateway/issues/1454
Not Tested
---
> Adding www-authenticate header to auth failures

- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/dto/ExtendedTokenIssuerDto.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
- integration/test-integration/src/test/resources/apim/config.toml
- integration/test-integration/src/test/resources/jwtGenerator/config.toml
- resources/conf/config.toml
- resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
- resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
This PR will avoid the inconsistency between all-in-one and distributed deployment by introducing separate issuer for APIM publisher to work internal key authentication. 
Fixes https://github.com/wso2/product-microgateway/issues/1906
Not Tested
---
> Adding new token issuer for APIM publisher

- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/swagger.go
- adapter/internal/oasparser/model/swagger_internal_test.go
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/config/APIConfig.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/models/API.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/subscription/SubscriptionDataStore.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/subscription/SubscriptionDataStoreImpl.java
$subject
fix https://github.com/wso2/product-microgateway/issues/1915
APIM 4.0.0-beta
Docker-Compose
```
Map<String, API> apiMap;
83af49dc-73e2-490d-9f8f-b7b0efec70a5 -> {API@6528} "API [apiId=38, provider=admin, name=SwaggerPetstore, 
version=1.0.5, context=/v2/1.0.5, policy=, apiType=HTTP, urlMappings=[]]"
6d42ab3a-fd05-49bd-8e92-d8f20a97ac74 -> {API@6531} "API [apiId=39, provider=admin, name=Web, version=v1, context=/websock/v1, policy=, apiType=WS, urlMappings=[]]"
d0093d81-ffef-4305-9645-a3d9fc2e84f7 -> {API@6525} "API [apiId=1, provider=admin, name=PizzaShackAPI, version=1.0.0, context=/pizzashack/1.0.0, policy=, apiType=HTTP, urlMappings=[]]"
```
---
> Use UUID to store APIs in SubscriptionDataStore

- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/docker-compose.yaml
- resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml
This pr to remove copying unnecessary configuration files to enforcer and adaptor nodes.
- Enforcer: only log4j2.properties file is used
- Adaptor: config.toml file and log_config.toml file are required.
Fixes https://github.com/wso2/product-microgateway/issues/1924
Not Tested
---
> Remove copying unnecessary config files to adaptor and enforcer

- .github/workflows/main.yml
- .gitignore
- .travis.yml
- pom.xml
We do not need to build the router in each every dev build. We need to build it during a release only. and in the jenkins pipelines. Hence moved it out to a separate maven profile
Fixes Task
Not Tested
---
> Add router build to maven profile

- adapter/internal/eventhub/subscription.go
- adapter/internal/messaging/notification_listener.go
- adapter/internal/oasparser/model/mgw_swagger.go
Earlier, there is a change introduced to avoid pulling the apis from /apis REST endpoint and generating the APIList from jms events. This could lead to inconsistencies as the JMS event contains less information (ex. the deploy_event does not contain API state)
Hence this change is reverted . (introduced with #1651)
Fixes #
Not Tested
---
> Revert: creating APIList from jms event rather than calling /apis endpoint.

- adapter/internal/api/apis_impl.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/discovery/xds/server_test.go
$subject
This is also not breaking the following scenario, tested with the following scenario as well.
Fixes https://github.com/wso2/product-microgateway/issues/1965
Docker-Desktop - Docker-Compose
macOS
---
> Keep existing environments when undeploy an API from APIM which is deployed with same vhosts

- adapter/internal/adapter/adapter.go
- adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
- adapter/loggers/logger.go
$subject
these logs can be enabled by adding following entry to the log_config.toml
```
#for router
[[pkg]]
name = "github.com/wso2/adapter/internal/discovery/xds/routercallbacks"
logLevel = "DEBG"
[[pkg]]
name = "github.com/wso2/adapter/internal/discovery/xds/enforcercallbacks"
logLevel = "DEBG"
```
Fixes #1988 
Not Tested
---
> Add callbacks to debug router connection

- adapter/internal/messaging/connection.go
- adapter/internal/messaging/listener.go
This PR introduces following changes.
1. Mask credentials in the jms connection url in logs.
`Retrying to connect with amqp://******@apim:5672 in every 2 seconds until exceed 3 attempts
`
2. Introduce infinite retry for jms connection with exponential interval.
When the configured retry count and the interval is exceeded, the connection will retry in exponential manner up to a maximum retry interval. This is 10X the configured retry interval.
Once the maximum retry interval is reached, the connection will be retried at the same max interval until the connection is successful.
Ex: 
Retry once every 30s for 5 times.
Maximum retry limit is reached, switching to exponential mode. 
(max retry interval is 10x30 (300s))
```
Retry in 30s
Retry in 60s (30 + 30)
Retry in 90s (30 + 60)
.
.
.
Retry …
```
> Mask connection url and improve jms retry 

- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/HttpConstants.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/interceptors/AccessLogInterceptor.java
Uses the same UUID to track request in envoy and enforcer
Fixes #2061 
Not Tested
---
> Fix #2061 - Use same UUID to track request in router and enforcer

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/listener.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackEndServer.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/timeouts/TimeOutTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
- integration/test-integration/src/test/resources/openAPIs/timeout_openAPI.yaml
- integration/test-integration/src/test/resources/testng-cc-standalone.xml
- resources/conf/config.toml.template
This pr introduces timeout configurations for router.
The sample config will be like below.
```
[router.upstream.timeouts]
routeTimeoutInSeconds = 60
routeIdleTimeoutInSeconds = 300
[router.connection.timeouts]
requestTimeoutInSeconds = 0
requestHeadersTimeoutInSeconds = 0
streamIdleTimeoutInSeconds = 300
idleTimeoutInSeconds = 3600
```
Fixes https://github.com/wso2/product-microgateway/issues/2063
Not Tested
---
> Add timeout configurations

- integration/test-integration/readme.md
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/ApimPreparer.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BasicEventsTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
- integration/test-integration/src/test/resources/testng-cc-with-apim.xml
- Combine the two test groups: `startup-pull` and `via-eventhub`
- Add a new testcase to test the events "create_api", "create_app", "create_sub", "delete_sub", "delete_api" 
OS name: "linux", arch: "amd64", family: "unix"
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
4 cores, 8 threads
---
> int-tests: combine startup pull and via eventhub tests

- adapter/internal/api/apis_impl.go
- adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
- adapter/internal/discovery/xds/routercallbacks/router_callbacks.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/eventhub/subscription.go
- adapter/pkg/messaging/connection.go
This PR introduces the connection retry support for failover amqp endpoints.
Failover reconnection strategy.. (example for 2 endpoints)
1. Try connecting to endpoint [0] with configured retry interval
2. If not successful, after the max retry count, try connecting to endpoint[1]
3. If not successful, after the max retry count, try connecting to endpoint[0] 
Fixes https://github.com/wso2/product-microgateway/issues/2090
Not Tested
---
> Add connection retry for failover endpoints

- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiListDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/KeyManagerDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionDiscoveryClient.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
Add improvements to logs, It will print below logs
```
Number of API artifacts received : 1
Number of applications received : 2
Number of subscriptions received : 2
Number of application key mappings received : 3
```
Fixes #2116 
Not Tested
---
> Fix #2116 - Improve enforcer side logs to print app, sub counts

- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/dto/JWTTokenPayloadInfo.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/InternalKeyTestCase.java
Fixes the issue of able to invoke with tampered internal key once the correct token gets cached.
Fixes #2081 
Not Tested
---
> Fix #2081 - Internal key cache issue

- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/SubscriptionValidationTestCase.java
Remove the `x-envoy-upstream-service-time` from response
Fixes #2146 
Not Tested
---
> Fix #2146 - Remove x-envoy-upstream-service-time header from response

- adapter/internal/adapter/adapter.go
If the `eventhub` configuration is not enabled, then the readiness probe doesn't get activated and hence the pod goes into a `CrashLoopBack`. Therefore we need to enable the probe if the event hub configuration is disabled
Fixes https://github.com/wso2/product-microgateway/issues/2172
Not Tested
---
> Enable readiness probe when the eventhub is disabled

- adapter/pkg/synchronizer/types.go
This is to reuse the `deployments.json` from `runtime-artifacts` endpoint for the same file received from `runtime-metadata` endpoint. The deployments.json from `runtime-metadata` has additional values `context` and `version` compared to the response from `runtime-artifacts`.
Related to #2040
Not Tested
---
> Updating APIDeployment type to match GA

- integration/test-integration/readme.md
- integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Add the two test groups: startup-pull and via-eventhub
Partially reverts https://github.com/wso2/product-microgateway/pull/2080
Validates https://github.com/wso2/product-microgateway/pull/2128
OS name: "linux", arch: "amd64", family: "unix"
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
4 cores, 8 threads
---
> int-tests: add startup and eventhub groups

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/messaging/azure_listener.go
- adapter/pkg/messaging/azure_connection.go
- resources/conf/config.toml.template
Correctly set the the valid connection string to be used for receiving events from azure service bus
Fixes https://github.com/wso2/product-microgateway/issues/2187
Not Tested
---
> Add correct environment variable name to be read for connection param

- adapter/src/main/assembly/assembly.xml
- pom.xml
- resources/conf/log_config.toml
- router/src/main/assembly/assembly.xml
1. Improve comments in log_config.toml
2. Fix following warnings
```
[WARNING] Some problems were encountered while building the effective model for org.wso2.am.choreo.connect:router:pom:0.9.0.2
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 33, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.wso2.am.choreo.connect:adapter:pom:0.9.0.2
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 58, column 21
[WARNING] 'build.plugins.plugin.version' for com.googlecode.maven-download-plugin:download-maven-plugin is missing. @ line 109, column 21
```
```
[WARNING] The assembly descriptor contains a filesystem-root relative reference, which is …
```
> Fix maven build warnings

- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/observability_util.bal
- pom.xml
AS $subject, this will remove the remove redundant resource appearances in observability metrics for **Per_Request_Duration_mean** attribute and,
introduce a config to remove HttpClient metrics which includes **ballerina_http_HttpClient_requests_total_value** and **ballerina_http_HttpClient_response_time_seconds_value** attributes.
`--b7a.observability.metrics.client.http.url.disabled=true`
> Remove redundant resource appearances in observability client metrics

- adapter/internal/oasparser/model/open_api.go
Fix not giving priority to x-wso2 extensions when server url is malformed. As the solution, stop throwing error if malformed URL/ templated URL is found under servers object
Fixes #https://github.com/wso2/product-microgateway/issues/2226
Manually tested
---
> Fix not giving priority to x-wso2 extensions when server url is malformed

- adapter/config/default_config.go
- enforcer/pom.xml
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigDefaults.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/RateLimitingSampler.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracerFactory.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracingConstants.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/AzureExporter.java
- enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/JaegerExporter.java
- enforcer/src/test/java/org/wso2/choreo/connect/enforcer/tracing/exporters/JaegerExporterTest.java
- pom.xml
- resources/conf/config.toml.template
Add jaeger exporter to enable exporting open telemetry metrics to jaeger. Only thrift exporter is supported at the moment.
```toml
[enforcer.tracing]
enabled = true
type = "jaeger"
[enforcer.tracing.configProperties]
connectionString = "http://jaeger:14268/api/traces"
instrumentationName = "CHOREO-CONNECT"
maximumTracesPerSecond = "2"
```
Partially fixes #2234 
Mac OS. docker-compose-with-apim
---
> Add Jaeger metric exporting

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/APIKeyTestCase.java
Adds a waiting time until API key relevant test setup properly prepares.
There were intermittent test cases in API key related tests.
https://github.com/wso2/product-microgateway/issues/2235
Mac OS Big Sur
java version "11.0.12" 2021-07-20 LTS
---
> Addition of wait time to API key test case

- pom.xml
As $subject, this will upgrade the balleirna to 1.2.21 and it will fix the oauth2 token validation cache issue.
Fixes https://github.com/wso2/product-microgateway/issues/2357
> Upgrade balleirna to 1.2.21

- enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/ParameterResolver.java
- enforcer-parent/commons/src/test/java/org/wso2/choreo/connect/enforcer/commons/model/RequestContextTest.java
$subject. 
In addition, allow path parameters to contain hyphen and underscore.
Fixes #2439 
Not Tested
---
> Bug fix: [Enforcer] Fix the issue where path parameters does not resolve depending on the trailing slash

- adapter/go.sum
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/AuthServer.java
Code to enable enforcer tracing after a succeful init was mistakenly removed during final refactoring of last tracing #2440 . This pr will fix it.
Fixes #2426 
Not Tested
---
> Fix enabling enforcer tracing

- adapter/pkg/discovery/protocol/cache/v3/resource.go
when there are multiple revoked tokens, only one of them is passed to enforcer via XDS communication. The reason for this behavior is that, in XDS cache these resources are maintained in a map. Hence, it is required to provide a key to maintain them as unique records. 
Fixes #2447
Not Tested
---
> bug-fix [TokenRevocation] Revoked Tokens are not properly updated when enforcer restarts.

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
The decorator field is used for tracing purposes. Hence rather than attaching resource path or endpoint basePath, it sounds correct to assign it with the complete routePath as routerPath remains unique across the router.
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=decorator#envoy-v3-api-msg-config-route-v3-decorator
Fixes #2445 
Not Tested
---
> Bug fix: [ Websocket] APIs with no endpointBasepath results in XDS update failure

- .github/workflows/nightly-integration-test.yml
Run tests if the workflow is manually triggered
The check job only runs, if the workflow triggered by the cron
Fixes https://github.com/wso2/product-microgateway/issues/2487
- Integration tests added:  N/A
Ubuntu ARM Images are tested in an Mac M1 chip lap - QSG
---
> Run tests if the workflow is manually triggered

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
When subscription validation is disabled, provide a meaningful application reference for analytics. The convention used here would be anon:<KM Ref>
Fixes #2356
Not Tested
---
> [Improvement] [Analytics] Showing application usage when subscription is disabled.

- enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/AuthenticationContext.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/dto/APIKeyValidationInfoDTO.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/WebSocketHandler.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketMetaDataFilter.java
Remove apitier field from AuthenticationContext and APIKeyValidationInfoDTO and only depend on tier field in APIConfig.
Fixes https://github.com/wso2/product-microgateway/issues/2264
Not Tested
---
> Only depend on tier in APIConfig which represents apiTier

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/SubscriptionThrottlingTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TokenUtil.java
- integration/test-integration/src/test/resources/configs/controlplane-enabled-config.toml
StopOnQuotaReach is properly populated as that was the root cause for subscription throttling failure.
Fixes #2368
Not Tested
---
> bug-fix: subscription throttling does not work for self contained access token

- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/open_api.go
- adapter/internal/oasparser/model/swagger.go
- adapter/internal/oasparser/model/swagger_test.go
- adapter/internal/oasparser/model/types.go
- adapter/internal/oasparser/operator/operator.go
- adapter/internal/oasparser/operator/operator_test.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/PrototypedAPITestCase.java
- integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Via this PR, the API.yaml is processed at the earliest. Then the openapi definition is processed and if there are any changes compared to API.yaml (ex. endpoints) those will be overridden by the openAPI. 
So the priority would be,
API.yaml < servers/host property (properties from openapi spec) < x-wso2 extensions
But for the prototyped apis, the endpoints would be determined based on API.yaml (servers/host property is ignored). 
Fixes #1955 
Not Tested
---
> [Bug-fix] Prioritize Swagger definition's vendor extensions over API.yaml for all APIs.

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/protobuf/ExtensionHolder.java
- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/protobuf/ProtobufParser.java
- distribution/resources/grpc/wso2_options.proto
As $subject, this will add the endpoint  timeout config support to GRPC API.
Users can define endpoint timeout as follows in the proto file.
- https://github.com/wso2/product-microgateway/issues/2373
> Add advance endpoint timeout config support to GRPC

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
- resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
- Send the same validateInfo used in authContext to jwt generator 
- Update k8 artifacts enable sub val for APIM publ
Fixes #
Not Tested
---
> Send the same validateInfo used in authContext to jwt generator 

- enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/RequestContext.java
When path temaplate is missing in scenarios like websocket API invocations, we should avoid trying to build path param map.
Fixes #2537
Not Tested
---
> Fix path param population error in Websocket APIs

- pom.xml
This PR upgrades the ballerina version to 1.2.22.
Fixes: https://github.com/wso2/product-microgateway/issues/2505, https://github.com/wso2/product-microgateway/issues/2456
> [3.2.x] Upgrade ballerina version to 1.2.22

- enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/APIConfig.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketMetaDataFilter.java
bug fix: If the openAPI's throttling is set to some operation level, and then revert back to API Level with Unlimited Tier, the resource level throttling still enforced instead on Unlimited Tier.
Fixes #2561 
Not Tested
---
> [Bug-Fix] Unlimited API Level Tier is not applied after resource level tier applied for once

- adapter/internal/api/restserver/config_restapi.go
- adapter/internal/discovery/xds/server.go
$subject
Approach
- When we want to add/update an API, the basepath can be overridden only if the basepath does not exist for the OrgId and VHost. 
- The only time such an basepath can exist is its own
Fixes https://github.com/wso2/product-microgateway/issues/2574
Not Tested
---
> Avoid adding API when its basepath is already used for a different API

- enforcer-parent/commons/src/main/java/org/wso2/choreo/connect/enforcer/commons/model/RequestContext.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/ResponseObject.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
bug fix: 
1. Stop sending the apiKey to backend (as a header and as a queryParam)
2. Stop sending authentication token/ apikey value within the throttle event
With this fix, users may be able to remove, modify query parameters using custom filters as well.
Fixes #2572 
Not Tested
---
> [Bug-Fix] Avoid Unwanted headers/query parameters being forwarded to the backend

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
UserId based deny policies not working as it is not populated correctly, when the InternalKey credential is used. The reason was that when InternalKey is used, there is no appTenant.  Hence the userID is populated in some incorrect manner. To fix, we have used APITenant instead. This will not cause any issue because apiTenant and appTenant remains same when oauth2 token or apiKey is used as cross tenant support is not available in the choreo connect,
Fixes #2578 
Not Tested
---
> [Bug-Fix] userId based deny policies not working 

- adapter/go.mod
- adapter/go.sum
Bump go openapi strfmt version to bump the version of `go.mongodb.org/mongo-driver`
Task
Not Tested
---
> Bump go openapi strfmt version

- adapter/internal/api/apis_impl.go
- adapter/internal/api/restserver/config_restapi.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/constants/constants.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/mgw_swagger_internal_test.go
- adapter/internal/oasparser/model/open_api.go
- adapter/internal/oasparser/model/resource.go
- adapter/internal/oasparser/model/swagger.go
- adapter/internal/oasparser/model/swagger_test.go
- adapter/internal/oasparser/model/types.go
- adapter/internal/oasparser/operator/operator_test.go
Move constants to a separate package to avoid confusions with variables and models, and having to use special patterns when naming constants.
Fixes https://github.com/wso2/product-microgateway/issues/2629
Related to https://github.com/wso2/product-microgateway/issues/2613
Not Tested
---
> Move constants to a seperate package

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithMultipleEnv.java
Fix intermittent test failure when undeploying API in CcWithMultipleEnv
Fixes #
Not Tested
---
> int-test: Fix intermittent test failure when undeploying API 

- pom.xml
This PR upgrades the ballerina version to 1.2.25 for some dependency updates.
> [3.2.x] Upgrade ballerina version to 1.2.25

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithSourceControl.java
Fixes build failure happens due to the test case failures. This PR increases the waiting time relevant to the CC instance used in source control test cases.
https://github.com/wso2/product-microgateway/issues/2676
Fixes # 
Not Tested
---
> [test-case fix] Waiting time increase for source control related tests

- adapter/internal/adapter/adapter.go
- adapter/internal/sourcewatcher/sourcewatcher.go
The readiness API is deployed and the sourcewatcher starts polling even when retrying to fetch artifacts from the repository fails.  This fixes the issue.
Fixes #2676
Not Tested
---
> Fix issue with source watcher startup

- adapter/internal/api/apis_impl.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/eventhub/subscription.go
- adapter/internal/messaging/notification_listener.go
- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/internal_dtos.go
- adapter/internal/oasparser/envoyconf/listener_test.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/model/api_yaml.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/pkg/messaging/azure_listener.go
- adapter/pkg/messaging/event_types.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/DefaultVersionApiTestCase.java
- integration/test-integration/src/test/resources/apiYaml/default_version_v1.yaml
- integration/test-integration/src/test/resources/apiYaml/default_version_v2.yaml
- integration/test-integration/src/test/resources/openAPIs/default_version_v1_OpenAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/default_version_v2_OpenAPI.yaml
- integration/test-integration/src/test/resources/testng-cc-standalone.xml
$subject.
default version change event is coming as an API_UPDATE type event from CP. This event doesn't contain enough information for CC to figureout if it should redeploy the API. Hence the `Action` property is introduced to API_UPDATE event.
Also API_UPDATE event doesn't contain the `gatewayLabels` property, therefore we are using internal maps to find the deployed envs of an API when default version change event is received.
Fixes #1581
Not Tested
---
> Add default version support

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
As $subject, this pr registers the javatime module in JSON mapper in order to handle the time date in the swaggerfile.
- https://github.com/wso2/product-microgateway/issues/2703
> Register the javatime module in jsonmapper

- adapter/internal/oasparser/model/common.go
- adapter/internal/oasparser/model/open_api_internal_test.go
Remove leading and/or trailing spaces present in an "endpoint" by trimming the string.
Fixes #2707
OS: Linux
Env: Docker
---
> Trim spaces in backend endpoints

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketResponseObserver.java
- Previously when compressed websocket frames arrived, we were unable to get the actual count since we were unable to decode them into separate frames. We logged an error and did not count the frames or throttle. 
- This PR temporarily fixes the issue by counting the raw frames arriving from the router. 
- There can be cases where an entire batch of frames is considered as one frame with this fix. The purpose is to have some sought of a limit.
- This is only relevant to compressed or other extended versions of the websocket protocol. 
- Checkout the issue for more info.
Fixes https://github.com/wso2/product-microgateway/issues/2693
Tested by using the changes in https://github.com/wso2/product-microgateway/pull/2736 together with the …
> Fix websocket compressed frames not being throttled

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketResponseObserver.java
- We decode the batched of frames at enforcer side to get the exact count of frames
- Thereafter, for each separate frame, we send a `WebSocketFrameResponse` back to the router
- Currently we clone the `WebSocketFrameRequest` and only update the new frame length
- The payload must also be updated
- This PR sets the payload of that single frame to the `WebSocketFrameResponse` within the loop, instead letting it send the payload of the entire batch of frames.
Fixes https://github.com/wso2/product-microgateway/issues/2765
Tested with the changes in the PR https://github.com/wso2/product-microgateway/pull/2736
---
> [websocket] Send only the payload of a single frame at a time from enforcer to router

- pom.xml
$Subject
* Bumping up the apache commons-io version to 2.11.0 to mitigate known vulnerabilities
> Bumping apache commons io version

- adapter/internal/oasparser/model/common.go
- adapter/internal/oasparser/model/common_test.go
- adapter/internal/oasparser/model/resource.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyTestCase.java
- integration/test-integration/src/test/resources/apiYaml/api_policies.yaml
- integration/test-integration/src/test/resources/openAPIs/api_policy_openAPI.yaml
- integration/test-integration/src/test/resources/testng-cc-standalone.xml
This will support a rewrite of
```
/shops/{shopId}/pets/{petId}/orders
to
/pets/{uri.var.petId}/hello-shops/abcd-shops/{uri.var.shopId}
```
Fixes https://github.com/wso2/product-microgateway/issues/2745
Tested in docker compose setup with apictl
---
> Support Path Params in Rewrite Paths with API Policy

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/FaultCodeClassifier.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/UnsecuredAPIAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/BlockedApiTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/websocket/WsClient.java
Following API Manager's implementation, the blocked API calls would be categorized under Auth failures despite the fact that the status code is 503.
Fixes #2701 
Fixes #2791 
- Integration tests added: Yes (for Internal key for blocked APIs test case_
Not Tested
---
> [Analytics] Publish analytics events for blocked API calls.

- adapter/internal/adapter/adapter.go
- adapter/pkg/health/controlplane.go
This PR will enables the health (in both adapter and router) when empty xds snapshot received from GA at the startup.
Fixes https://github.com/wso2/product-microgateway/issues/2618
Tested locally on minikube.
---
> Enable health when no apis received from GA at the startup

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnforcerConfig.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
The same JWTValidator object is used within the matched API, if users invoke with different tokens from different issuers with high concurrent they could mix one transformer for scopes another transformer for consumer key or other claims
Fix wso2/product-microgateway#2817
Not Tested
---
> Pass JWT transformer within methods

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/WebSocketFrameService.java
- In the class [WebSocketFrameService](https://github.com/wso2/product-microgateway/blob/main/enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/WebSocketFrameService.java), a map of observers is maintained to keep track of **open** grpc streams.
-  A grpc stream is created right when we receive the websocket upgrade request. https://github.com/wso2/product-microgateway/blob/e12313de297e143d877664f3be6654e1c1272155/envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.cc#L374
- Here, we do not `sendEnforcerRequest` since we do not know if the handshake was successful https://github.com/wso2/product-microgateway/blob/e12313de297e143d877664f3be6654e1c1272155/envoy-filters/mgw-source/filters/http/mgw-wasm-websocket/filter.cc#L393
- This is where we send …
> Remove additional log related to websocket stream

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnforcerConfig.java
$subject
Hence two default transformers will not created for the same issuer
Related to https://github.com/wso2/product-microgateway/pull/2823
Not Tested
---
> Synchronize Default JWT transformer creation per issuer

- resources/k8s-artifacts/apim/apim-config.yaml
- resources/k8s-artifacts/apim/apim-service.yaml
- resources/k8s-artifacts/choreo-connect/choreo-connect-with-apim-ingress.yaml
- resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
- resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
- samples/istio/mtls-mode/README.md
- samples/istio/mtls-mode/gw_vs.yaml
- samples/istio/sidecar-mode/README.md
- samples/istio/sidecar-mode/gw_vs.yaml
Reverts wso2/product-microgateway#2793
It seems we have to revert this PR to support the istio use cases. We can't use wso2apim as the hostname in Istio and they have the following validation. Basically short names are not allowed. In K8s docs, we can ask the user to change the jwks endpoint from the admin console.
admission webhook "validation.istio.io" denied the request: configuration is invalid: short names (non FQDN) are not allowed
> Revert "Updating APIM hostname"

- adapter/internal/api/apis_impl.go
- adapter/internal/discovery/xds/server.go
$subject
Solution:
To the routes array, all the default versioned apis should be in the tail. 
Hence always, 
/context/version pattern is matched prior to matching /context/*
Fixes https://github.com/wso2/product-microgateway/issues/2831
Not Tested
---
> Bug fix: Default versioned APIs would be called when a versioned API is expected if it has the resource /*

- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
Fixes https://github.com/wso2/product-microgateway/issues/2864
Update route path generation by adding a regex to handle training slash.
Update routing to the backend by updating `pathRegex` and `substitutionString` in the regex_rewrite envoy configs.
Results: 
On a **/pet/getByStatus**
On a **/pet/{petId}**
Ubuntu 20.04.4 , openjdk version "11.0.14.1" 
---
> Add fixes related to handling trailing slash in path

- enforcer-parent/enforcer/src/main/assembly/assembly.xml
This is to exclude following jars that are not required to run enforcer container. It was already excluded and had to correct the pattern for that.
- org.wso2.choreo.connect.enforcer-1.x.x-javadoc.jar
- org.wso2.choreo.connect.enforcer-1.x.x-sources.jar
OS: Darwin
Env: Docker
---
> Exclude sources and javadoc jars in enforcer container

- enforcer-parent/enforcer/pom.xml
- pom.xml
Enforcer was using  swagger-parser  to get javax-validation as a dependency. Instead removed swagger-parser  and added javax-validation directly. 
Tested 
#2912
---
> Removed unused swagger-parser and added javax-validation directly to enforcer

- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithDefaultConf.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithMultipleEnv.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/StandaloneBeforeTestSuite.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/AllHttpMethodsForWildcardTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/DefaultVersionApiTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apiDeploy/TrailingSlashTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/apipolicy/APIPolicyTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/HttpsClientRequest.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TestConstant.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
- integration/test-integration/src/test/resources/openAPIs/all_http_methods_for_wildcard_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/trailing_slash_openAPI.yaml
- integration/test-integration/src/test/resources/testng-cc-standalone.xml
- A minor fix for a bug introduced when adding the change https://github.com/wso2/product-microgateway/pull/2837
- Add tests 
- Invoking path with a trailing slash not given in the initial API definition
- Invoke rewritten path (via API policy) with a trailing slash
- Invoke default and non-default APIs with a trailing slash
- Invoke `/context/*` for all methods when path is /*
- Invoke `/context` for a few methods (get and post) when path is /*
Related to https://github.com/wso2/product-microgateway/issues/2864
- Unit tests added: Updated
Not Tested
---
> [main] Update fix for trailing stash and add tests

- adapter/internal/adapter/adapter.go
- adapter/pkg/synchronizer/apis_fetcher.go
Bug fix: If APIM responds with 204 where there are no artifacts, adapter does not start. (it was only reacting to 404 status code earlier)
Fixes #2935
Not Tested
---
> Adapter does not start if APIM responds with 204 status code

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/oasparser/envoyconf/listener.go
- resources/conf/config-for-eventhub.toml
- resources/conf/config.toml
- resources/conf/config.toml.template
- resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
- resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Envoy by default passes the x-forwarded-for to the upstream, so the upstream services can process the header and get information about the originating ip address, network hops etc. But when the router is used as an edge proxy, it has to append the ip address of the immediate downstream which is typically a load balancer. This is not added by the default configuration.
- `UseRemoteAddress = true` appends the ip address of the immediate downstream of the router to the `x-forward-for` header. Typically in edge proxy deployment, ip address of the load balancer will be added.
- `UseRemoteAddress = false` (default) passes the `x-forward-for` header to the upstream without appending the immediate downstream node ip address. 
Fixes #2957 
Mac …
> Edge proxy mode configuration added

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/JWTUtils.java
Choreo Connect does not start in Windows 10 with Docker WSL issue fixing. 
Fixes #2918
Windows 11 - WSL2 - Ubuntu 20.04
---
> CC not starting with WSL issue fixed

- components/micro-gateway-tools/pom.xml
Need to upgrade the gson version used within the org.wso2.micro.gateway.tools-3.2.0.jar of Microgateway Runtime. The currently used gson version is 2.8.1, and it gets added as a transitive dependency of toml4j. We need to bump this vulnerable version to a non-vulnerable version.
This PR adds json 2.8.9 as that is the latest release for the 2.8.x series.
- Related Issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/426
> [MGW] [3.2.x] Add gson dependency to micro-gateway-tools

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/CorsTestCase.java
- integration/test-integration/src/test/resources/configs/jwt-generator-config.toml
- integration/test-integration/src/test/resources/openAPIs/cors_openAPI.yaml
If the user provides the origin to be *`.foo.com`, the `*`considered to be a wild card. 
Fixes #3006 
Not Tested
---
> [CORS] Support providing origins with wildcard subdomains.

- adapter/pkg/synchronizer/types.go
Changed deployedTimestamp type in GatewayLabel struct from string to int64 due to the change of deployedTimestamp in `deployment.json` from string to long. 
OS: macOS Monterey 12.4
Env (Docker/K8s): Docker 20.10.16 on Rancher Desktop 1.4.1
---
> Changed deployedTimestamp type from string to int64

- adapter/internal/oasparser/envoyconf/http_filters.go
- adapter/internal/oasparser/envoyconf/listener.go
- adapter/internal/oasparser/envoyconf/routes_configs.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/router/EnvoyHttpFilterTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/EnvoyHttpFilterTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/ExistingApiTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
- integration/test-integration/src/test/resources/apim/1/apis/EnvoyHttpFilterAPI.json
- integration/test-integration/src/test/resources/apim/1/apps/applications.json
- integration/test-integration/src/test/resources/apim/1/subscriptions/subscriptions.json
- integration/test-integration/src/test/resources/testng-cc-standalone.xml
- integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Prevent x-envoy headers `X-envoy-original-path` and `x-envoy-expected-rq-timeout-ms` being sent to the backend.
Fixes https://github.com/wso2/product-microgateway/issues/2986
Not Tested
---
> [main] Prevent x-envoy headers being sent to the backend

- .trivyignore
Remove trivy ignore entry for adapter health probe
Not Tested
---
> Remove trivy ignore entry for adapter health probe

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/JwtTestCase.java
Check auth header bearer format during canAuthenticate. Reduce token parse error log length.
Fixes https://github.com/wso2/product-microgateway/issues/2993
Not Tested
---
> [main] Fix error when auth header has bearer twice

- adapter/internal/oasparser/envoyconf/http_filters.go
- adapter/internal/oasparser/envoyconf/listener.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/router/EnvoyHttpFilterTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/EnvoyHttpFilterTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
- integration/test-integration/src/test/resources/apimApisAppsSubs/apis.json
- integration/test-integration/src/test/resources/apimApisAppsSubs/applications.json
- integration/test-integration/src/test/resources/apimApisAppsSubs/subscriptions.json
- integration/test-integration/src/test/resources/testng-cc-standalone.xml
- integration/test-integration/src/test/resources/testng-cc-with-apim.xml
Prevent x-envoy headers `x-envoy-original-path` and `x-envoy-expected-rq-timeout-ms` being sent to the backend
Fixes https://github.com/wso2/product-microgateway/issues/2986
OS: macOS Monterey 12.4
Env (Docker/K8s): Docker 20.10.16 on Rancher Desktop 1.4.1
---
> Suppress x-envoy headers and cluster header being sent to the backend service

- enforcer-parent/enforcer/src/main/assembly/assembly.xml
$subject due to trivy scan failure.
Fixes #
Not Tested
---
> Stop copying certs to /home/wso2/security directory in enforcer image

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/ScopesAsArrayTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/throttle/SubscriptionThrottlingTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/TokenUtil.java
- integration/test-integration/src/test/resources/openAPIs/scopes_openAPI.yaml
- integration/test-integration/src/test/resources/testng-cc-standalone.xml
- Fix scope parsing error when multiple scopes provided in an array
- Currently the jwt parser expects multiple scopes as a space separated single string. ex: "scope": "write:pet read:pet"
With this change the jwt scope field can also have an array of strings. "scope": [ "write:pet", "read:pet"]
Test Changes - standalone mode
- Test when jwt has multiple scopes provided in an array. Refactor and update TokenUtil to reuse code to provide scopes as array.
Fixes https://github.com/wso2/product-microgateway/issues/3057
Not Tested
---
> Fix scope parsing error when multiple scopes provided in an array

- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/MockBackendProd.java
- integration/mock-backend-server/src/main/java/org/wso2/choreo/connect/mockbackend/Utils.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/router/EnvoyHttpFilterTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/Utils.java
- integration/test-integration/src/test/resources/openAPIs/openAPI.yaml
Confirm the case change done to headers by envoy and confirm that it does not affect the query params.
router to backend - Header keys gets converted to first letter upper case, remaining letters lowercase
backend to client - Header keys gets converted to all lowercase letters
header values and query params - unchanged
Fixes https://github.com/wso2/product-microgateway/issues/3075
- https://github.com/wso2/product-microgateway/issues/3009
- https://github.com/wso2/product-microgateway/issues/3071 (enforcer receives the case similar to the client receiving the response header)
Not Tested
---
> int-test: Confirm the case change done to headers by envoy

- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
Make MGW default cache expiry time as a configurable property from MGW level. Related to public git issue, https://github.com/wso2/api-manager/issues/691.
- Added token expiry time from the micro-gw.conf configuration to `IntrospectionServerConfig` section. 
- In case of the absence of configuration, default configuration will be loaded from micro gateway default constant file. The default configuration is `DEFAULT_TOKEN_EXPIRY`.
> Made MGW default cache expiry time as a configurable property from MGW level

- enforcer-parent/enforcer/pom.xml
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracerFactory.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/TracingConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/AzureExporter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/JaegerExporter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/OTLPExporter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/tracing/exporters/ZipkinExporter.java
- pom.xml
- resources/conf/config.toml.template
Currently WSO2 Choreo Connect supports distributed tracing with Jaeger, Zipkin and Azure Application Insights using the OpenTelemetry SDK and relevant exporters. With this PR, support for publishing traces via native OTLP protocol is added. OTLP is a vendor agnostic general purpose telemetry data delivery protocol which is considered as the standard protocol for publishing telemetry data. 
1. Enable OTLP collector in jaeger. (jaeger version has to be >= 1.35)
```yaml
jaeger:
image: jaegertracing/all-in-one:1.37
environment:
- COLLECTOR_OTLP_ENABLED=true
ports:
- "16686:16686"
- "4317:4317"
``` 
2. Enable tracing in `config.toml` and add relevant tracing config.
```toml
[tracing]
enabled = true
type = "otlp"
[tracing.configProperties]
maxPathLength = "256"
host = "jaeger"
port = "4317" …
```
> Add OpenTelemetry OTLP exporter support for publishing traces

- pom.xml
This PR upgrades the Ballerina version to 1.2.33 for some third party dependency upgrades.
OS - Ubuntu 20.04
JDK - OpenJDK 1.8.0_342
---
> [3.2.x] Upgrade ballerina version to 1.2.33

- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/apim/ApimResourceProcessor.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/withapim/ApimStartupExecutor.java
In integration tests for CC with APIM, the test class ApimPreparer runs multiple times creating and deploying different sets of APIs. The set of API to deploy is given by the apimArtifactsIndex. This PR is to limit the number of APIs per set. This,
- prevents test dubugging becoming difficult
- prevents having to increase the default limit of getAllAPIs in the API-M Publisher REST API (used to delete created APIs in the later runs)
Fixes https://github.com/wso2/product-microgateway/issues/3098
Not Tested
---
> [int-tests] Avoid creating more than 25 APIs in a single run of ApimPreparer

- components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
- pom.xml
This PR upgrades the Call Home Core version to 1.0.14 to upgrade the Snake YAML version to 1.32.
OS - Ubuntu 20.04
JDK - OpenJDK 1.8.0_342
---
> [3.2.x] Upgrade Call Home Core version to 1.0.14

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/withapim/PrototypedAPITestCase.java
$subject. 
Prototyped APIs should be validated using a valid token in order to access the API.
Fixes #3118
Not Tested
---
> Enable security for prototyped APIs

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/GraphQLAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/Utils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/interceptor/MediationPolicyFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleDataHolder.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/APIKeyTestCase.java
- integration/test-integration/src/test/resources/openAPIs/api_key_swagger_security_openAPI.yaml
Fix apikey failure when header key is in uppercase and prevent common auth headers reaching websocket backends.
- Use lowercase header key when accessing header map in request context in APIKeyAuthenticator. (Router automatically converts header keys to lowercase when sending to enforcer. This has been already handled for access token and internal key)
- Use lowercase header key when adding headers to protectedHeaders map and removeHeaders array since they are accessed in other parts of the enforcer.
- Move auth header removal to a cmmon util method
- Prevent common auth headers reaching websocket backends
Integration Tests
- Test apikey with uppercase header name. 
- Access token and internal key tests already include the respective header with first letter uppercase.
Fix …
> Fix apikey failure when header key is in uppercase

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleDataHolder.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/ThrottleFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/throttle/utils/ThrottleUtils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/websocket/WebSocketThrottleFilter.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtValidator/JwtTestCase.java
When throttling based on JWT claims, we parsed the payload of the JWT similar to a SWT until now. This was a direct transition from the json to a Map<String, String>. This did not require initializing a JSON parser and upto now we only had come accross use cases where the claim value was a string, and not an object. Recently, an update has been released for API-M 4.1.0 where the access token generated from developer portal includes the claim "realm" with a value that is an object (Ex. {\n "signing_tenant": "carbon.super" \n}). Hence, the payload must be considered as an actual JWT token which may include an JSON object as the claim value.
Fixes https://github.com/wso2/product-microgateway/issues/3129
Not Tested
---
> Parse JWT payload with JSON parser during JWT based throttle validations

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/EnvVarConfig.java
Added a method to load the trusted root certificates in the `<javahome>/lib/security/cacerts` location to the existing truststore.
Made cert trusting method configurable via env config 
| env variable name | values | default value|
|--|--|--|
|TRUST_DEFAULT_CERTS | **true** / **false**  | **true**| 
Ex:
Docker compose config:
```
enforcer:
hostname: enforcer
image: wso2/choreo-connect-enforcer:1.2.0-m1-SNAPSHOT
...
...
environment:
...
...
- TRUSTED_CA_CERTS_PATH=/home/wso2/security/truststore
- TRUST_DEFAULT_CERTS=false
...
```
k8s config:
```
...
spec:
containers:
- name: choreo-connect-enforcer
...
image: wso2/choreo-connect-enforcer:1.2.0-m1-SNAPSHOT
...
env:
...
...
- name: TRUSTED_CA_CERTS_PATH
value: "/home/wso2/security/truststore"
- name: TRUST_DEFAULT_CERTS
value: "false"
... …
```
> Enforcer truststore should trust ca root certs

- components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Entity.java
To fix the error when calling the `getHeaders(String headerName)` method.
Fixes https://github.com/wso2/product-microgateway/issues/3121
macOS 12.6, jdk 1.8
---
> Fix for error in getHeaders method

- pom.xml
Increment the version of APIMGT common gateway dependency to start using kid instead of x5t to identify which certificate to use for validation.
no
Not Tested
---
> Enable kid property on JWT header

- .github/workflows/nightly-integration-test.yml
Signed-off-by: Renuka Fernando <renukapiyumal@gmail.com>
Notify the chat, when nighly build has failed.
Fixes #
Not Tested
---
> Notify CC chat when nightly build failed

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/jwtGenerator/JwtGeneratorTestCase.java
Use the same hashing between the backend JWTGenerator and the JWKS endpoint to allow for  keys to be matched for verification.
Updated Integration test for JWKS
Not Tested
---
> Match kid properties between JWT and JWKS generators

- integration/test-integration/pom.xml
Signed-off-by: Renuka Fernando <renukapiyumal@gmail.com>
Getting the following error when running integration tests in Mac M1.
```log
[WARNING] Ignoring download failure.
[INFO] Downloading: https://github.com/wso2/product-apim-tooling/releases/download/v4.1.0/default-package-to-be-overridden
[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.6.3:wget (download-apictl) on project test-integration: IO Error: Error while expanding /Users/renuka/git/product-microgateway/integration/test-integration/target/default-package-to-be-overridden: Archive is not a ZIP archive
```
Fixes #
Not Tested
---
> Fix error downloading apictl in Mac M1 for integration tests

- enforcer-parent/enforcer/pom.xml
- pom.xml
Updates below dependencies,
- tomcat-embed-core v10.0.27 to v10.1.4
- graphql-java v19.2 to v20.0
- jackson-databind 2.13.4.2 to v2.14.1
Removes snakeyaml dependency from the Enforcer
Fixes #
Not Tested
---
> [main] Dependency version upgrades

- adapter/pkg/discovery/protocol/server/sotw/v3/server.go
Signed-off-by: Lahiru De Silva <lahirude@wso2.com>
Increase channel capacity in sotw v3 server to avoid a possible deadlock
Fixes #3182 
Not Tested
---
> [xDS]: Increase channel capacity in sotw v3 server

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/DefaultAnalyticsEventPublisher.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AnalyticsConstants.java
Stop JWKS requests from being published to the analytics platform.
Issue: [3157](https://github.com/wso2/product-microgateway/issues/3157}
---
> Stopped publishing analytics logs for JWKS requests

- adapter/pkg/discovery/protocol/server/sotw/v3/server.go
Signed-off-by: Lahiru De Silva <lahirude@wso2.com>
Increase channel capacity in sotw v3 server to avoid a possible deadlock
Fixes #3182 
Not Tested
---
> [Choreo][xDS]: Increase channel capacity in sotw v3 server

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/issuer/HttpTokenServerHandler.java
TestKey endpoint wasn't working when JWKS was enabled. This is to fix that.
Testkey handler now flushes the netty channel after providing the response.
Fixes #
Not Tested
---
> Testkey handler flushes channel after writing response

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
- Update `removeSpecialCharsInPathParameters` method to facilitate a special use case where path parameters are in format `abc.{var}`
- Fix https://github.com/wso2/product-microgateway/issues/3201
> [3.2.x] Update removeSpecialCharsInPathParameters method

- distribution/LICENSE-RUNTIME.txt
- distribution/resources/bin/gateway
- distribution/resources/bin/gateway.bat
- pom.xml
Vulnerabilities [CVE-2022-1471](https://github.com/advisories/GHSA-mjmj-j48q-9wg2) and [CVE-2022-25857](https://github.com/advisories/GHSA-3mc7-4q67-w48m)  are identified in `org.yaml:snakeyaml 1.26` version which is coming from `jmx_prometheus_javaagent-0.14.0.jar` included in the Microgateway runtime.
This PR upgrades `jmx_prometheus_javaagent` to the latest version [0.17.2](https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.17.2/) to fix the vulnerabilities.
> Upgrade jmx_prometheus_javaagent to 0.17.2

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoFaultAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/MetadataConstants.java
- pom.xml
Same changes done in this PR can be found in the approved PR #3143
Modification to retrieve the end user name and api context as a default analytics metric.
By default, end user name and api context should be sent as a metric by the provider.
Fix the enforcer AnalyticsFilter
Fix the default analytics provider (ChoreoAnalyticsProvider)
JDK 11.0.16
Ubuntu 22.04.1 LTS
Not Tested
> Fixed attribute issue.

- components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
- tests/src/test/resources/openAPIs/validation/specialCharacterAPI.json
- Update the API definition used for the integration test `BuildWithSpecialCharsTestCase` to have the special path parameter with the format `abc.{var}`
- Related PR: https://github.com/wso2/product-microgateway/pull/3202
- Related Issue: https://github.com/wso2/product-microgateway/issues/3201
> [3.2.x] Update API definition for the BuildWithSpecialCharsTestCase

- components/micro-gateway-cli/pom.xml
- pom.xml
This PR adds the io.swagger.core.v3:swagger-core dependency to the POM to define the version packed into the CLI jar.
Fixes https://github.com/wso2/product-microgateway/issues/3231
---
> [3.2.x] Add swagger-core dependency to the POM

- pom.xml
This PR upgrades the Ballerina version to 1.2.36.
Fixes https://github.com/wso2/api-manager/issues/1447
> [3.2.x] Upgrade Ballerina version to 1.2.36

- adapter/internal/discovery/xds/server.go
we have noted that the choreo-connect adapter still update it's xds cache under a label as same as the gateway environment's name. Due to this router is not getting such updates, because router is only configured to listen on a particular gateway label.
With these changes, adapter will set xds cache under a common label(specific to dataplane cluster), which specified in config (`conf.ControlPlane.gatewayLabels`) 
Note: This applies only if dynamic environments enabled (`conf.Controlplane.DynamicEnvironments`) 
Fixes #
Not Tested
---
> [choreo] bug fix: set xds cache under a common label for dynamic environments

- enforcer-parent/enforcer/pom.xml
- pom.xml
$subject
The slf4j.api.version 2.0.6 is incompatible for org.wso2.am.analytics.publisher.client
Default versions
```log
[INFO] +- org.wso2.am.analytics.publisher:org.wso2.am.analytics.publisher.client:jar:1.1.3:compile
[INFO] |  +- io.github.openfeign:feign-httpclient:jar:11.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.2:compile
```
```log
[INFO] \- org.wso2.orbit.graphQL:graphQL:jar:19.2.wso2v2:compile
[INFO]    +- com.graphql-java:graphql-java:jar:19.2:compile
[INFO]    |  \- org.slf4j:slf4j-api:jar:1.7.35:compile
```
Related PR: https://github.com/wso2/product-microgateway/pull/3044
Fixes https://github.com/wso2/product-microgateway/issues/3269
Tested in Docker Compose for Analytics Debug logs + Analytics in Choreo
---
> Fix not printing debug logs in apim-analytics-publisher

- dev-scripts/code-coverage/prepare-files-before-int-tests.sh
- distribution/src/main/assembly/assembly.xml
- integration/test-integration/src/test/resources/dockerCompose/apim-in-common-network-docker-compose.yaml
- resources/docker-compose/apim/docker-compose.yaml
- resources/docker-compose/apim/dockerfiles/apim/Dockerfile
- resources/docker-compose/apim/dockerfiles/apim/docker-entrypoint.sh
- resources/k8s-artifacts/apim/apim-deployment.yaml
$subject
APIM RC docker image will bot available in DockerHub, hence users have to download the APIM 4.2.0 from WSO2 website and copy it to the following location of the Choreo Connect distribution.
```
<Distribution Location>/docker-compose/choreo-connect-with-apim/dockerfiles/apim/wso2am-4.2.0.zip
```
And start the docker compose as usual.
For kubernetes try out, users have to first run the following command and build the APIM docker image.
```
docker-compose -f <Distribution Location>/docker-compose/choreo-connect-with-apim/docker-compose.yaml  build apim 
```
Fixes #
Mac ARM64 - Docker Compose
---
> Build APIM Docker image instead of pulling from DockerHub

- pom.xml
This will update the analytics publisher client version to 1.2.2
Related with https://github.com/wso2-enterprise/choreo/issues/19544
> Update analytics publisher client version

- adapter/internal/discovery/xds/rate_limiter_cache.go
- adapter/internal/discovery/xds/rate_limiter_cache_test.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/model/api_yaml.go
- adapter/internal/oasparser/model/api_yaml_test.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/types.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/setup/standalone/CcWithJwtConfigAndTransformer.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/ratelimit/APILevelWithoutRateLimitTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/ratelimit/ApiLevelRatelimitTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/ratelimit/OperationLevelRatelimitTestCase.java
- integration/test-integration/src/test/resources/apiYaml/api_level_without_ratelimit_api.yaml
- integration/test-integration/src/test/resources/apiYaml/operation_level_ratelimit_api.yaml
- integration/test-integration/src/test/resources/openAPIs/api_level_without_ratelimit_openAPI.yaml
- integration/test-integration/src/test/resources/testng-cc-standalone.xml
- pom.xml
- resources/conf/config.toml
- resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml
Fixes the request count value assigning for the Unlimited value in rate-limiter.
```
{
"id": "",
"target": "/*",
"verb": "GET",
"throttlingLimit": {
"requestCount": -1,
"unit": "MINUTE"
},
"authType": "Application \u0026 Application User",
"scopes": [],
"usedProductId
```
rate-limiter config value :
```
choreo-connect %  curl http://localhost:6070/rlconfig -i                         
HTTP/1.1 200 OK
Date: Fri, 10 Mar 2023 12:19:57 GMT
Content-Length: 0
```
Fixes https://github.com/wso2/product-microgateway/issues/3290
Not Tested
---
> [Choreo] Fix for rate-limiter unlimited value

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
Reduce calls to JWKS endpoint  for Access token validation by caching all JWKS objects against their url. Before making a jwks call to a specific url we check the JWKS cache and try verify if it has the needed public key, otherwise we make the call.
Not Tested
---
> Global cache for JWKS

- adapter/internal/oasparser/envoyconf/access_loggers.go
- adapter/pkg/config/log_types.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/RouterAccessLogConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/grpc/ExtAuthService.java
- resources/conf/log_config.toml
Include the original vhost in access logs
The original vhost (authority header received from request) has to be included in the access log to filter out the gateway environment.
Query params will be available in the original request path as well as in the backend request path in access logs. The user is responsible for not sending sensitive data with query params.
```toml
[accessLogs]
enable = true
logfile = "/dev/stdout" # This file will be created inside router container.
```
```log
[2023-04-18T12:50:47.897Z]' '-' 'enforcer' 'POST' '-' '/testkey' 'HTTP/1.1' '200' 'via_upstream' '-' 'curl/7.79.1' 'c1142d8f-ddbf-4c19-b97e-f2b073862330' '-' '172.26.0.4:9001' '15' '762' '107' '-' '56' '0' '1' '107' '
[2023-04-18T12:50:49.921Z]' '-' 'localhost:9095' 'GET' '-' …
```
> Include the original vhost in access logs

- pom.xml
The Prometheus jar is upgraded to 0.18.0 to upgrade snakeyaml to resolve security vulnerabilities.
Fixes #3344
Tested in Mac OS
---
> Upgrade Prometheus jar to 0.18.0 to upgrade snakeyaml

- adapter/internal/adapter/adapter.go
$subject
Fixes #
Not Tested
---
> fix: use RetrieveRuntimeArtifacts endpoint to fetch APIs in RetryFetchingAPIs when dynamic environments are enabled

- components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
Change log level of subscription validation failure from `ERROR` to `INFO`.
Fixes https://github.com/wso2/api-manager/issues/1773
- MacOS Ventura ( v13.2.1 )
- OpenJDK 1.8
---
> Change log level of subscription validation failure

- components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
- components/micro-gateway-core/src/main/ballerina/Ballerina.toml
- pom.xml
Update json-smart, callhome and ballerina platform versions for micro-gateway 3.2.0 version.
Mac OS, JDK-1.8
---
> Update json-smart, callhome and ballerina platform versions

- adapter/internal/oasparser/envoyconf/internal_dtos.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
- adapter/pkg/config/log_types.go
- resources/conf/log_config.toml
$subject
Since for all API versions, there is an API UUID, it is possible to filter access logs for an endpoint in a component version.
Even though the sem version is used (the user invokes just with the major version) we will be able to verify the exact version the request belongs to.
Fixes #
Not Tested
---
> Include API UUID in Access logs

- adapter/internal/discovery/xds/semantic_versioning.go
- adapter/pkg/semanticversion/semantic_version.go
This PR updates the semanticversion package by adding `Compare` function which returns boolean by comparing a semantic version with another semantic version
---
> Move semantic version comparison to package

- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/ratelimit/ApiLevelRatelimitTestCase.java
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/ratelimit/OperationLevelRatelimitTestCase.java
- integration/test-integration/src/test/resources/apiYaml/operation_level_ratelimit_api.yaml
- integration/test-integration/src/test/resources/apiYaml/ratelimit_api.yaml
- integration/test-integration/src/test/resources/openAPIs/operation_level_ratelimit_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/ratelimit_openAPI.yaml
Please find the details on the attached issue
Fixes #
- Integration tests added: Updated existing tests to support Sem Versions in Rate Limits
Not Tested
---
> Accept special chars in resource path of the Open API

- adapter/internal/oasparser/envoyconf/access_loggers.go
- adapter/pkg/config/log_types.go
- integration/mock-backend-server/src/main/resources/Dockerfile
- resources/conf/log_config.toml
$subject
Config
```yaml
[accessLogs.excludes]
[accessLogs.excludes.systemHost]
enabled = true
pathRegex = "^(/health|/ready)$" # keep this empty to match all paths
```
```sh
$ curl -X GET "https://localhost:9095/health" -H "accept: application/json" -H "Authorization:Bearer $TOKEN" -k
{"status": "healthy"}
```
No Access log printed.
```sh
$ curl -X GET "https://localhost:9095/health" -H "accept: application/json" -H "Authorization:Bearer $TOKEN" -k -H 'Host: foo'
{"description":"The requested resource is not available.","code":"404","message":"Not Found"}
```
```json
{"apiPath":null,"respTxDur":null,"respCode":404,"upstrmSvcTime":null,"respCodeDtls":"route_not_found","respDur":null,"bytesSent":94,"extAuthDtls":null,"dur":0,"respFlag":"NR","time":"2023-09-04T05:48:03.697Z","reqTxDur":null," …
```
> Remove /health and /ready from Access Logs

- adapter/internal/discovery/xds/semantic_versioning.go
Add non capturing group syntax to fix path parameter matching issue related to semantic versioning
Fixes #
Not Tested
---
> Bug fix: Path Parameter forwarding issue when semantic versioning is enabled.

- adapter/internal/discovery/xds/enforcercallbacks/enforcer_callbacks.go
- adapter/internal/eventhub/subscription.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApiListDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/KeyManagerDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/RevokedTokenDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/discovery/ThrottleDataDiscoveryClient.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/subscription/SubscriptionDataStoreImpl.java
Log each and every XDS request response within adapter so that we can ensure when an XDS request is sent.
Setup XDS max message size for all the grpc client stubs.
Disable APIListDiscoveryClient
Fixes #
Not Tested
---
> Improvements related XDS communication between enforcer and adapter.

- adapter/internal/discovery/xds/server.go
Fix the memory leak where applications, application-keyMappings were accumulating over time as new application, key-mapping creation happens.
Fixes #
- Unit tests added: No 
- Integration tests added: No (Existing tests covers this)
Not Tested
---
> Fix the memory leak, where xds resources getting accumulated over time

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/oasparser/envoyconf/listener.go
- adapter/internal/oasparser/envoyconf/listener_test.go
- resources/conf/config.toml.template
> Add config to modify the buffered payload limit in choreo connect

- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/grpcAnalytics/gRPC_analytics_client.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
- Resolves https://github.com/wso2/product-microgateway/issues/3471
- Forwardport https://github.com/wso2-support/product-microgateway/pull/411
- Make gRPC `timeoutInMillis` parameter user configurable. Previously this was set to 2147483647. Now users can configure this with a default value of 2147483647.
> [3.2.x] Make gRPC timeout parameter configurable

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
$Subject
Fixes
* https://github.com/wso2-enterprise/choreo/issues/26158
Not Tested
---
> Supporting whitelisted organizations to access any environment with Production tokens

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
$subject as if some request authentication fails due to issue with JWKS endpoint call, it would be hard to debug. 
Fixes #
Not Tested
---
> Add a log to indicate errors related to JWKS request in enforcer

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/oasparser/envoyconf/constants.go
- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/listener.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testcases/standalone/security/CorsTestCase.java
This PR enables the `x-choreo-test-session-id` header to be used for internal endpoint testing. Also the header is added to the RequestHeadersToRemove config.
Related to https://github.com/wso2-enterprise/choreo/issues/25701
Not Tested
---
> Internal-endpoint-testing: handle x-choreo-test-session-id header cors config

- adapter/internal/synchronizer/apis_fetcher.go
Bug Fix: When the retry limit reaches its maximum limit, the worker threads which calls the control plane gets blocked. 
Fixes #
Locally tested in the following manner.
Started choreo-product-apim locally
then Started choreo-connect locally pointing to local choreo-product-apim and ASB connection string. (I used PDP mode in choreo-connect here)
Stopped the choreo-product-apim so that we could replicate a network unreachable type failure.
Sent deploy events via ASB 
Monitored the behavior with and without the fix. And with the fix it did not blocked.
---
> Bug fix: deadlocked worker pool threads during a controlplane connection failure.

- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
$subject happens depending on the number of resources. For 1st resource once, for the second two times and so on. And this could lead to failures at nginx level due to increased header buffer sizes.
Fixes #
Not Tested
---
> Bug fix: x-choreo-test-session-id is appended to CORS config repeatedly 

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/discovery/xds/marshaller.go
- adapter/internal/discovery/xds/payloadfmt.go
- adapter/internal/discovery/xds/payloadfmt_test.go
- adapter/internal/messaging/notification_listener.go
- adapter/pkg/messaging/azure_connection.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/keymgt/KeyManagerHolder.java
- resources/conf/config.toml.template
$subject
adapter-1   | 2024-02-16 15:10:13 INFO [marshaller.go:346] - [xds.MarshalKeyManager] [-] [Renuka] Key Manager Configuration Before Filter: map[AuthorizeURL:https://choreo-am-service:9443/oauth2/authorize LogoutURL:https://choreo-am-service:9443/oidc/logout OAuthConfigurations.EncryptPersistedTokens:true RevokeURL:https://choreo-am-service:9443/oauth2/revoke ServerURL:https://choreo-am-service:9443/services/ TokenURL:https://choreo-am-service:9443/oauth2/token VALIDITY_PERIOD:3600 authorize_endpoint:https://choreo-am-service:9443/oauth2/authorize certificate_type:JWKS certificate_value:https://sts.preview-dv.choreo.dev/oauth2/jwks enable_map_oauth_consumer_apps:false enable_oauth_app_creation:true enable_token_encryption:false enable_token_generation:true enable_token_hash:false …
> Remove unnecessary configs passed from Adapter to Enforcer through xDS messages

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/adapter/adapter.go
- adapter/internal/api/apis_impl.go
- adapter/internal/common/types.go
- adapter/internal/discovery/xds/server.go
- adapter/internal/synchronizer/apis_fetcher.go
- adapter/pkg/adapter/adapter.go
- adapter/pkg/utils/slice_utils.go
- adapter/pkg/utils/slice_utils_test.go
- resources/conf/config.toml.template
Chunk retrieving deployments from controlplane to reduce the overhead to the controlplane.
Tested in Dev envirionment
---
```log
adapter-1   | 2024-02-28 06:20:01 INFO [main.go:39] - [main.startMicroGateway] [-] Starting Choreo Connect Adapter
adapter-1   | 2024-02-28 06:20:37 INFO [adapter.go:339] - [adapter.fetchAPIsOnStartUp] [-] Fetching APIs at startup with the received API UUID list (size: 3998)...
adapter-1   | 2024-02-28 06:27:28 INFO [adapter.go:350] - [adapter.fetchAPIsOnStartUp] [-] Fetching APIs at startup is completed...
```
```log
adapter-1   | 2024-02-29 10:02:22 INFO [main.go:39] - [main.startMicroGateway] [-] Starting Choreo Connect Adapter
adapter-1   | 2024-02-29 10:02:57 INFO [adapter.go:343] - …
```
> Chunk fetching APIs from Control Plane on startup

- adapter/internal/oasparser/envoyconf/access_loggers.go
> Bug fix: Secondary Logformat entries are not shown when the access log format is json

- adapter/config/default_config.go
- adapter/config/parser.go
- adapter/config/types.go
- adapter/internal/oasparser/envoyconf/dns_resolver.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- resources/conf/config.toml.template
$subject
Fixes #
Docker Compose 
```toml
[router.upstream.dNS.DNSResolver]
resolverType = "c-ares"
[router.upstream.dNS.DNSResolver.cAres]
useResolversAsFallback = false
filterUnroutableFamilies = false
useTCPForDNSLookups = false
noDefaultSearchDomain = false
[[router.upstream.dNS.DNSResolver.cAres.resolvers]]
protocol = "TCP" 
address = "0.0.0.0"
port = 53
```
---
> Make typed_dns_resolver_config configurable in Envoy Cluster configuration

- adapter/internal/discovery/xds/semantic_versioning.go
- adapter/pkg/semanticversion/semantic_version.go
This PR,
- Removes unwanted minor version based intelligent routing regex building for the envoy router
- Fixes a bug where the vhost is neglected on API undeployment
Addresses: https://github.com/wso2-enterprise/choreo/issues/28419
OS: ubuntu
Go: 1.22
---
> [Choreo] Fix intelligent routing availability after deleting and re-creating an API

- components/micro-gateway-cli/src/main/resources/templates/dockerConfig.mustache
This will fix mustache encoding of special characters (=), as it's necessary to provide commands including the = character for the Docker CMD command
- https://github.com/wso2/product-microgateway/issues/3513
- https://github.com/wso2/api-manager/issues/2886
> Fix encoding issue in the mustache file

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/Utils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/WebSocketAPI.java
At invocation, we get the below error log in enforcer. This PR will fix it.
Additionally it fixes the issue of being unable to invoke sandbox deployment using the sandbox internal api key
```
13/05/2024, 22:01:17.851
choreo-connect-deployment-external-p3-68fb7b84f4
at org.wso2.choreo.connect.enforcer.grpc.ExtAuthService.check(ExtAuthService.java:83)
13/05/2024, 22:01:17.851
choreo-connect-deployment-external-p3-68fb7b84f4
at org.wso2.choreo.connect.enforcer.grpc.ExtAuthService.buildResponse(ExtAuthService.java:193)
```
https://github.com/wso2-enterprise/choreo/issues/26743
Fixes #
Not Tested
---
> Add support for invocations with internal key for Websocket APIs

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/features/FeatureFlags.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/subscription/SubscriptionDataStoreImpl.java
```java
SubscriptionPolicy subPolicy = datastore.getSubscriptionPolicyByOrgIdAndName(apiConfig.getOrganizationId(),
sub.getPolicyId());
```
We are getting the org ID from API. API always has an org. So let's say org Foo's API is invoked and his org is not in feature flag.
```java
@Override
public SubscriptionPolicy getSubscriptionPolicyByOrgIdAndName(String orgId, String policyName) {
String organizationId = StringUtils.isEmpty(orgId) ? APIConstants.SUPER_TENANT_DOMAIN_NAME : orgId;
String key = PolicyType.SUBSCRIPTION +
SubscriptionDataStoreUtil.DELEM_PERIOD + organizationId +
SubscriptionDataStoreUtil.DELEM_PERIOD + policyName;
return subscriptionPolicyMap.get(key);
}
```
But every org still does not have a sub-policy. Hence getting null pointer exception.
Fixes #
Related Issue: …
> Retrieve subscription policies from SubscriptionDataStore for organizations the feature is enabled

- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/token_introspection_handler.bal
- distribution/resources/conf/default-micro-gw.conf.template
This will introduce the following configuration to enable introspection for all tokens that failed jwt validation and this will allow introspection without considering the token format.
.
```
[keyManager]
enableIntrospectForFailedJWT = true
```
By default this is set to false.
- https://github.com/wso2/product-microgateway/issues/3533
> Introduce configuration to enable introspection for all tokens that failed jwt validation

- adapter/internal/adapter/adapter.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/features/FeatureFlags.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/GRPCUtils.java
This PR aims to resolve an issue with the XDS/GRPC connection where the enforcer doesn't know that the connection has failed and doesn't reach out to another replica of the local adapter for new configuration.
This fix works by configuring GRPC client on the enforcer to send HTTP/2 Ping frames every 2 minutes, if the ping isn't returned with an ACK the connection is closed.
This only checks connection health and not the healthiness of the adapter.
This was tested with in a localsetup where the adapter is paused using a debugger after initial discovery and subscription from the enforcer.
- Before this fix the connection to the adapter would remain until the enforcer checks the connection in 2 hours (default keep alive configuration).
- …
> [Choreo] [Bugfix] Adds keepalive pings to enforcer XDS connection

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Limit the maximum connection duration of a webSocket connection to 1hour
Fixes https://github.com/wso2-enterprise/choreo/issues/26361
Tested locally.
After one hour the connection is terminated with the below router log - "max_duration_timeout"
`[2024-07-27T15:30:04.962Z]' 'd3a7dfea-fb10-4371-b21d-85d1bc28667b-dev.e1-us-east-azure.preview-dv.choreoapis.dev' 'host.docker.internal' 'GET' '/d3a7dfea-fb10-4371-b21d-85d1bc28667b/websocket/websocket-local/v1.0/chat' '/chat' 'HTTP/1.1' '101' 'max_duration_timeout' '-' '-' 'debb007e-c902-40e8-8acf-e38f35c29b02' '-' '192.168.5.2:8085' '7173' '4315' '3600011' '-' '-' '-' '-' '107' '667d009fff17fc0d6af31cb5' '-' '`
---
> [Choreo] Limit WS connection duration to 1h

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Add further validations for emoticons and substrings
https://github.com/wso2-enterprise/choreo/issues/28819
Not Tested
---
> Add envoy config route validations for emoticons and substrings

- pom.xml
https://github.com/wso2-enterprise/choreo/issues/26321
To support implementation to add a header for the response sent from upstream
Fixes #
Locally tested
---
Router logs locally
```
[2024-08-01 10:33:21.265][9][info][admin] [source/server/admin/admin.cc:67] admin address: 0.0.0.0:9000
[2024-08-01 10:33:21.265][9][info][config] [source/server/configuration_impl.cc:131] loading tracing configuration
[2024-08-01 10:33:21.265][9][info][config] [source/server/configuration_impl.cc:91] loading 0 static secret(s)
[2024-08-01 10:33:21.265][9][info][config] [source/server/configuration_impl.cc:97] loading 4 cluster(s)
[2024-08-01 10:33:21.310][9][info][config] [source/server/configuration_impl.cc:101] loading 0 listener(s)
[2024-08-01 …
```
> [Choreo] Update envoy cp api version & protobuf.java.version

- adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
- adapter/internal/oasparser/envoyconf/internal_dtos.go
- adapter/internal/oasparser/envoyconf/listener_test.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters_test.go
Configure Envoy to retry connections when upstream Kubernetes endpoints, proxied by Cilium Envoy, send RST packets. This change aims to mitigate https://github.com/cilium/cilium/issues/33880 which cause unexpected 503 responses for requests.
Fixes #
- Unit tests added: Yes/~No~
- Integration tests added: ~Yes~/No
Not Tested
---
> Add retry on resets for local endpoints

- adapter/internal/oasparser/model/api_env.go
- adapter/internal/oasparser/model/async_api.go
- adapter/internal/oasparser/model/constants.go
- adapter/internal/oasparser/model/mgw_swagger.go
- adapter/internal/oasparser/model/open_api.go
- adapter/internal/oasparser/model/open_api_internal_test.go
- adapter/internal/oasparser/model/swagger.go
- adapter/internal/oasparser/operator/operator_test.go
> Fix issue identified on websocket endpoint URL type set to http

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/ChoreoAnalyticsProvider.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/AnalyticsConstants.java
Currently the WebSocket Access logs with status code 101 are not published in analytics UI. This PR will fix it by using the current default analytics provider.
Later in the  handleGRPCLogMsg(StreamAccessLogsMessage message) method we need to define a seperate analytics provider for websocket connections. Currently there is no way of identifying this.
Furthermore this can be improved with access logs been flushed for a duration instead of completion
https://www.envoyproxy.io/docs/envoy/v1.26.8/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-hcmaccesslogoptions
access_log_flush_interval
([Duration](https://developers.google.com/protocol-buffers/docs/reference/google.protobu …
> [Choreo] [ws analytics] Fix publishing 101 success requests

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
Reduce the maximum connection duration of a webSocket connection to 15 minutes.
https://github.com/wso2/product-microgateway/pull/3558
Not Tested
---
> Reduce the connection duration time to 15 mints

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyUtils.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
$subject
Fixes #
Not Tested
---
> Add support to send PAT JWT to backend

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
$subject
Fixes #
Not Tested
---
> Improve x-forwarded-authorization header setting logic

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/analytics/AnalyticsFilter.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/MetadataConstants.java
- Adding insights data to metadataContext
Fixes #
Not Tested
---
> Adding insights data to metadataContext

- adapter/config/default_config.go
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/ChoreoAPIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
$subject
Fixes #
Not Tested
---
> Move token resolving logic from the request ctx to separate method

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/Constants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/UnsecuredAPIAuthenticator.java
- enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticatorTest.java
- enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticatorTest.java
> Change keyword used in auth

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
The use of connection pooling for intra-cluster communications has led to a few conflicts with Cilium Envoy, resulting in intermittent 503 errors. The goal of this PR is to disable connection pooling within the cluster to mitigate the issue described in https://github.com/cilium/cilium/issues/33880.
Fixes #
Not Tested
---
> Add support for disabling in-cluster endpoint connection pooling

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyUtils.java
- enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/security/jwt/APIKeyAuthenticatorTest.java
$subject 
Fixes #
Not Tested
---
> Add component ID to API key identifier

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/TokenValidationContext.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
- integration/test-integration/src/test/resources/openAPIs/api_key_swagger_security_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/openAPI_startup.yaml
- integration/test-integration/src/test/resources/openAPIs/scopes_openAPI.yaml
- integration/test-integration/src/test/resources/openAPIs/security_openAPI.yaml
$subject
Fixes #
Not Tested
---
> Fix scope validation issue when multiple security schemes are configured

- pom.xml
This PR upgrades the commons-io and ballerina versions in microgateway.
ballerina.platform.version: 1.2.54 -> 1.2.55
commons-io.version: 2.11.0 -> 2.14.0
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/8103
Port of https://github.com/wso2-support/product-microgateway/pull/456 for 3.2.9 version.
> Upgrade commons-io and ballerina versions

- adapter/internal/messaging/azure_listener.go
When multi-tenanted ASB is enabled (i.e. config.ControlPlane.ASBDataplaneTopics are provided) it should get the AmqpOverWebsocketsEnabled flag from each topic wise configuration, rather getting from the global configuration.
Fixes #
Not Tested
---
> [choreo] Fix: propely get AmqpOverWebsocketsEnabled flag

- pom.xml
Upgrade `ballerina.platform.version` to `1.2.56` to address issue `Docker Image Build Failure in Micro Gateway Toolkit Due to Jersey Library Update`.
Issue: https://github.com/wso2/product-microgateway/issues/3635
Internal issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/8441
> Bump `ballerina.platform.version`

- adapter/internal/adapter/adapter.go
- adapter/pkg/synchronizer/apis_fetcher.go
$subject
Relates with: https://github.com/wso2-enterprise/choreo/issues/31875
Fixes #
Not Tested
---
> [Choreo] Removal of unused internal service resource path named retrieve-api-artifacts and its usage

- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
The use of connection pooling for intra-cluster communications has led to a few conflicts with Cilium Envoy, resulting in intermittent 503 errors. The goal of this PR is to make sure choreo connect doesn't keep up a connection open for too long resulting in reusing of stale upstream connection. This is a compromise between having connection pooling fully turned of vs having to deal with 503 errors.
https://github.com/wso2-enterprise/choreo/issues/33447
Not Tested
---
> Added a env var to control MaxConnectionDuration

- adapter/config/default_config.go
- adapter/config/types.go
- adapter/internal/oasparser/envoyconf/routes_with_clusters.go
This PR adds a feature flag for the previous PR https://github.com/wso2/product-microgateway/pull/3655 which adds the port to the host header for keda multiple endpoints routing.
Related to https://github.com/wso2/product-microgateway/pull/3655
Not Tested
---
> Add feature flag for port in host header

- components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
- components/micro-gateway-core/pom.xml
- components/micro-gateway-core/src/main/ballerina/Ballerina.toml
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_request_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_response_filter.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/native/validator.bal
- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/OpenAPIRequest.java
- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/OpenAPIResponse.java
- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/SchemaValidationUtils.java
- components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java
- distribution/pom.xml
- pom.xml
- tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
This PR revamps the schema validation logic to align with APIM 4.x versions.
Additionally, it includes the changes from PR [1]. Therefore, if a user is using a custom date/time format in the API definition, they must add -Dregister.timeModule=true to register the JavaTimeModule for schema validation to function properly.
Fixes https://github.com/wso2/api-manager/issues/3763
[1] https://github.com/wso2/carbon-apimgt/pull/12432
---
> [3.2.x] Revamp schema validation logic to align with APIM 4.x versions

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/keymgt/KeyManagerHolder.java
- enforcer-parent/enforcer/src/test/java/org/wso2/choreo/connect/enforcer/keymgt/KeyManagerHolderTest.java
Issuer claim can be null, but in choreo context we do not support because the issuer is critical. 
This is a bug fix. If token issuer is not present, return 401 error. 
N/A
- Unit tests  : added
- Integration tests: Not required
- Followed secure coding standards in https://security.docs.wso2.com/en/latest/security-guidelines/secure-engineering-guidelines/? yes
- Ran golangci-lint plugin and verified report? N/A
- Ran maven-checkstyle-plugin and verified report? Yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? Yes
> List any other related PRs
> Fix NPE when issuer claim is not available in JWT

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/jwks/JWKSRequestHandler.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/mcp/request/McpRequestHandler.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/issuer/HttpTokenServerHandler.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/RestServerInitializer.java
- mcp/pkg/mcp/request.go
- mcp/pkg/mcp/utils.go
This PR makes the content length configurable for the Netty REST server
Related issue: https://github.com/wso2-enterprise/apim-saas/issues/594
Not Tested
---
> Make Netty content length configurable

- adapter/internal/adapter/adapter.go
- adapter/internal/common/types.go
- adapter/internal/ga/client.go
- adapter/internal/ga/client_test.go
- adapter/internal/synchronizer/apis_fetcher.go
For example:
Before fix: API 1 Dev deployment is in partition 1 and Prod Deployment is assigned to partition 2. During startup, development and production both are deployed in gateway partition 1. After fix: only api1 Dev deployment is deployed in partition 1
Fixes #
Not Tested
---
> When applying the APIs to gateway, selectively deploy only the assigned deployments for that partition

- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/mcp/McpConstants.java
- enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/mcp/request/McpRequestHandler.java
This PR adds the `Access-Control-Expose-Headers` header to the MCP response when the `mcp-session-id` header is available in the response. This is done in order to fix the MCP inspector in the Bijira console not working properly when the MCP server honors the session ID.
Related issue: https://github.com/wso2-enterprise/apim-saas/issues/802
---
> Add Access-Control-Expose-Headers header to MCP response

- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_security_constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
- components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
- distribution/resources/conf/default-micro-gw.conf.template
- tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuth2andBasicAuthTestCase.java
Introduces a config that returns 401 instead of 500 for malformed basic auth headers.
> [3.2.x] Return 401 for malformed basic auth header
