components/micro-gateway-core/src/main/ballerina/gateway/sample_gold_policy.bal

Revert the const and used correct value …

Revert the const and used correct value

---

components/micro-gateway-core/src/main/ballerina/gateway/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/throttle_filter.bal
components/micro-gateway-core/src/main/resources/ballerina.conf

Added UUID to the message flow
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Added UUID to flow

---

components/micro-gateway-core/src/main/ballerina/gateway/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/gateway/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/gateway_dtos.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils.bal
components/micro-gateway-core/src/main/resources/ballerina.conf
distribution/product/pom.xml
distribution/product/src/main/assembly/bin.xml

> Add access token key type and the api publisher to the authentication context
> These details are required for throttling analytics filters.

Improve authentication context

---

components/micro-gateway-cli/pom.xml

adding pom

---

components/micro-gateway-cli/src/main/resources/templates/mock/service.mustache

adding template changes

---

components/micro-gateway-cli/pom.xml
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/cmd/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/cmd/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/config/bean/TokenConfig.java
components/micro-gateway-cli/src/main/resources/default-config.yaml
distribution/product/pom.xml
distribution/product/resources/bin/micro-gw.sh
distribution/product/src/main/assembly/bin.xml

1. Support stored project root location 
Initially, set up a project using --path variable
```
wso2am-micro-gw-1.0.0-SNAPSHOT/bin$ ./micro-gw.sh  setup -l internal --path /home/malintha/wso2apim/cur/c4mgw/malintha
```
In subsequent runs, no need to specify --path; it will be automatically resolved using the previously provided path.
```
wso2am-micro-gw-1.0.0-SNAPSHOT/bin$ ./micro-gw.sh  setup -l internal
```
2. Support specifying the relative path to the trust store location from <CLI_HOME> in config.yaml
`  trustStoreLocation: lib/platform/bre/security/ballerinaTruststore.p12`
3. BALLERINA_HOME set to <CLI_HOME>/lib/platform
> Describe how you are implementing the solutions. Include an …

Support stored project root location

---

pom.xml

Updating root pom's cli artifact id

---

distribution/product/resources/bin/micro-gw.sh

fixing workspace.txt reading issue

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/cmd/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/cmd/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/exception/CLIZipException.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/utils/ZipUtils.java
components/micro-gateway-cli/src/main/resources/distribution/bin/micro-gw.sh

Creates a distribution for a label in the label /target folder when building the source using a label `./micro-gw.sh  build -l <label-name>`
Start the label distribution by directly running the sh in the distribution bin folder.
`microgw-{labelName}/bin$ ./micro-gw.sh`
> Link(s) to …

Creating a GW distribution when building a label

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/cmd/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/cmd/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/utils/ZipUtils.java
components/micro-gateway-cli/src/main/resources/distribution/bin/micro-gw.sh
distribution/product/resources/bin/micro-gw.sh

Refactoring label distribution build

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/cmd/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/cmd/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/cmd/Main.java
components/micro-gateway-cli/src/main/resources/templates/mock/endpoints.mustache
distribution/product/resources/conf/micro-gw.conf
distribution/product/resources/filters/extension_filter.bal
distribution/product/resources/templates/endpoints.mustache

- Add conf file to the project structure when build command is given
-  Add extension filter to generated endpoints.bal

Add conf file to the project structure

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/service/APIServiceImpl.java
components/micro-gateway-cli/src/main/resources/default-config.yaml

> Bump rest API version to v0.13 in the Gateway CLI

Bump rest API version to v0.13

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/config/bean/TokenConfig.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/service/APIServiceImpl.java
components/micro-gateway-cli/src/main/resources/default-config.yaml
components/micro-gateway-cli/src/main/resources/templates/mock/service.mustache

> Remove hard coded urls for publisher and admin APIs and perform config file lookup.

Config lookup for publisher & admin APIs

---

components/micro-gateway-cli/src/main/resources/templates/mock/service.mustache

disable endpoint cache of ballerina endpoint based on api definition

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/dtos/throttle_dtos.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
distribution/product/resources/conf/micro-gw.conf

> 
Remove unused values
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

 Remove unused values

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/config/bean/Config.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/model/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/codegen/service/APIServiceImpl.java
components/micro-gateway-cli/src/main/resources/default-config.toml
components/micro-gateway-cli/src/main/resources/templates/service.mustache

- Add default cors configs
- Add scope annotations to generated services

Add default cors config and scopes to generated services

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/ThrottlePolicyGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/GenSrcFile.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/TokenManagementUtil.java

adding code improvements

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
distribution/resources/conf/micro-gw.conf
tests/src/test/java/org/wso2/micro/gateway/tests/services/AuthenticationFailureTestCase.java

> This PR fixes the following issues.
[1] - https://github.com/wso2/product-microgateway/issues/38
[2] - https://github.com/wso2/product-microgateway/issues/39

Fix #product-microgateway-38 and #product-microgateway-39

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal

- Provides capability to host default versioned apis in the micro gateway
Fixes the issue : https://github.com/wso2/product-microgateway/issues/44

Issue 44 Fix - Capability to have default api version

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java

Code improvements

---

components/micro-gateway-cli/pom.xml
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/resources/distribution/bin/micro-gw.sh
components/micro-gateway-core/pom.xml
components/pom.xml
distribution/pom.xml
distribution/resources/bin/micro-gw
distribution/src/main/assembly/bin.xml
pom.xml
tests/pom.xml

Refactoring pom versions and scripts

---

pom.xml

add wso2 parent pom

---

components/micro-gateway-cli/pom.xml

remove source plugin

---

components/micro-gateway-cli/pom.xml

skip gpg plugin

---

components/micro-gateway-cli/pom.xml
pom.xml

add gdp plugin skip to root pom

---

pom.xml

change scm property value

---

pom.xml

reverting back to original id

---

pom.xml

change the scm id

---

pom.xml

changing scm id to scm-server

---

pom.xml

adding plugin management section

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
distribution/resources/bin/micro-gw

Adding cli home as a system property

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/data_writer.bal
components/micro-gateway-core/src/main/ballerina/gateway/dtos/analytics_dtos.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/gateway/uploade_files_timer.bal
components/micro-gateway-core/src/main/ballerina/gateway/usagedata_uploader.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
distribution/resources/conf/micro-gw.conf
tests/src/test/resources/confs/base.conf
tests/src/test/resources/confs/default-test-config.conf
tests/src/test/resources/confs/startup.conf

Intercept request and extract necessary data to publish to analytics server.
Intercepting requests, take necessary data, persist into file.

Adding analytics filter for microgateway

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/data_writer.bal
components/micro-gateway-core/src/main/ballerina/gateway/uploade_files_timer.bal
components/micro-gateway-core/src/main/ballerina/gateway/usagedata_uploader.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
distribution/resources/conf/micro-gw.conf
tests/src/test/resources/confs/base.conf
tests/src/test/resources/confs/default-test-config.conf
tests/src/test/resources/confs/startup.conf

Requests related stat data publishing and showing. …

Fixing request stat publishing issues.

---

components/micro-gateway-core/src/main/ballerina/Ballerina.toml
components/micro-gateway-core/src/main/ballerina/gateway/api_gateway_cache.bal
components/micro-gateway-core/src/main/ballerina/gateway/constants/api_throttle_out_constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/data_writer.bal
components/micro-gateway-core/src/main/ballerina/gateway/endpoints/api_gateway_endpoint.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authz_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/gateway_conf.bal
components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/throttle_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
distribution/pom.xml
distribution/resources/filters/extension_filter.bal
pom.xml
tests/src/test/java/org/wso2/micro/gateway/tests/services/AuthenticationFailureTestCase.java
tests/src/test/resources/apis/pizza_shack_api.bal

> Update to ballerina version 0.975
> Change filter interfaces

Update to ballerina version 0.975

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/resources/cli-help/cli-build.help
components/micro-gateway-cli/src/main/resources/cli-help/cli-setup.help
distribution/resources/bin/micro-gw
distribution/resources/conf/cli-config.toml

> 
1. Improve args to provide project name and external config file
2. Improve to use CLI home config file instead if workspace config
ex command:
i) will use the default config in <CLI_HOME>/resources/conf/cli-config.toml
bin/micro-gw setup 
-u admin 
-p admin 
-l apimTestLabel 
--path /path/to/workspace/
--base-url https://localhost:9444/ 
--trustStore path/to/truststore 
--trustStorePass password
-n rukshan
ii) will use the given config 
bin/micro-gw setup 
--path /home/rukshan/apim/2.5.0/path 
-l apimTestLabel 
-c /path/to/conf/cli-config.toml
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email …

Add arg to provide project name and config file

---

distribution/pom.xml

> Change ballerina download url to download from production url

Change ballerina download url

---

distribution/pom.xml
distribution/src/main/assembly/bin.xml
tests/pom.xml

Renaming distribution to wso2am-micro-gw-toolkit-<version>

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/DefaultCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/HelpCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ResetCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/RunCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/exception/CLIRuntimeException.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
distribution/resources/conf/cli-config.toml
tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
tests/src/test/java/org/wso2/micro/gateway/tests/services/APIInvokeTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/services/AuthenticationFailureTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/services/ThrottlingTestCase.java

> Findbug issues fixed and Refactoring

Findbug issues fixed and refactoring

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/exception/CLIInternalException.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
distribution/resources/bin/micro-gw
distribution/resources/cli-conf/logging.properties

To generate code for a single API using name and version.
**Setting up**
```
$ micro-gw setup -a PizzaShackAPI -v 1.0.0 -n pizzaproject
BALLERINA_HOME environment variable is set to /home/malintha/wso2apim/cur/c4mgw/wso2am-micro-gw-toolkit-2.5.0-SNAPSHOT/lib/platform
MICROGW_TOOLKIT_HOME environment variable is set to /home/malintha/wso2apim/cur/c4mgw/wso2am-micro-gw-toolkit-2.5.0-SNAPSHOT
Enter Password for admin: 
```
**Building**
```
$ micro-gw build -n pizzaproject
```

Support generating code for a single API without a label

---

distribution/resources/bin/micro-gw.bat

* Initial version of `micro-gw.bat`
* Execute micro-gw CLI tool from Windows command line interface
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you …

Add micro gateway CLI bat

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/gateway/filters/authz_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/throttle_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal

> Fixed mustache errors when endpoints are not available
> Handled errors when endpoint is not defined for a keytype

Fixed endpoint errors

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
components/micro-gateway-core/src/main/ballerina/gateway/annotation.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal
distribution/resources/bin/micro-gw
distribution/resources/cli-conf/logging.properties
distribution/resources/conf/micro-gw.conf

Set default log level to trace mode in both GW and ToolKit (till release).
Added more debug trace logs.
To give invalid credentials response when used an invalid JWT token.
```
curl -k -X GET "https://localhost:9095/pizzashack/1.0.0/menu" -H "accept: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlVCX0JReTJIRlYzRU1UZ3E2NFEtMVZpdFliRSJ9.eyJhdWQiOiJodHRwOlwvXC9vcmcud3NvMi5hcGltZ3RcL2dhdGV3YXkiLCJzdWIiOiJhZG1pbiIsImFwcGxpY2F0aW9uIjp7ImlkIjo5LCJuYW1lIjoiYXBwMSIsInRpZXIiOiJVbmxpbWl0ZWQifSwic2NvcGUiOiJhbV9hcHBsaWNhdGlvbl9zY29wZSBkZWZhdWx0IiwiaXNzIjoiaHR0cHM6XC9cL2xvY2FsaG9zdDo4MjQzXC90b2tlbiIsImtleXR5cGUiOiJQUk9EVUNUSU9OIiwic3Vic2NyaWJlZEFQSXMiOlt7Im5hbWUiOiJQaXp6YVNoYWNrQVBJMTIzIiwiY29udGV4dCI6IlwvcGl6emFzaGFjazEyM1wvMS4wLjAiLCJ2ZXJzaW9uIjoiMS4wLjAiLCJw …
```

Adding more debug/trace logs, fixing response issue with invalid jwt

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal

Refactor methods

---

components/micro-gateway-core/src/main/ballerina/gateway/api_gateway_cache.bal
components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal
distribution/resources/conf/micro-gw.conf
tests/src/test/java/org/wso2/micro/gateway/tests/services/AuthenticationFailureTestCase.java

> Gateway add two level of caches
> Make caching enable configurable

gateway add two layers of cache

---

components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/httpEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache

Update endpoint alias name. Now the endpoint should be provided as following
`-e TestAPI.v1.sand.endpoint.0="http://wso2.com"`

Update endpoint alias name

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
distribution/resources/bin/micro-gw.bat

- Fix project location issues
- Refactor usage of project `label` with `project name`
- Fixed issue when using `java.debug` with `micro-gw build` command
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of …

Improve micro-gw CLI tool for windows .bat 

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerationContext.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/HashUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesDeployment.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java

- Removed unnecessary root/projectRoot variables as now projectRoot can be taken from current working DIR.
- hashing improvements
- Replaced unnecessary label occurrences with projectName

Code refactoring and hashing improvements

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal

Fixing JWT expiry validation. Atm, you can invoke an API with an expired JWT token. This PR fixes the https://github.com/wso2/product-microgateway/issues/134 …

Fixing JWT expiry time validation

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/resources/distribution/bin/gateway.bat

- Add `gateway.bat` startup script to start the micro-gateway in windows environments 
> Link to the PR for changes to the …

Add gateway.bat startup script for windows

---

components/micro-gateway-cli/src/main/resources/distribution/bin/gateway

Fixes https://github.com/wso2/product-microgateway/issues/130

Fix gateway background startup issue

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/resources/distribution/bin/gateway
components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/data_writer.bal
components/micro-gateway-core/src/main/ballerina/gateway/dtos/analytics_dtos.bal
components/micro-gateway-core/src/main/ballerina/gateway/executiontime_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/file_rotating_timer.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/responsetime_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/uploade_files_timer.bal
components/micro-gateway-core/src/main/ballerina/gateway/usagedata_uploader.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal

Improving analytics filter by adding a file location to write files.
Omit filter when throttle out or request is auth filter failed.
File location added to use it as a shared location.

Improving analytics filter

---

components/micro-gateway-cli/src/main/resources/distribution/bin/gateway.bat
distribution/resources/bin/micro-gw.bat

- Fix issue in running micro-gw CLI from a different partition other than the partition containing the `micro-gw.bat`
> Link to …

micro-gw bat improvments

---

components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal

> This PR fixes the issue: https://github.com/wso2/product-microgateway/issues/123
> Refactor the code to remove duplicate codes.

Fix product-microgateway issue 123: Remove duplicate code

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/HashUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/gateway/api_gateway_cache.bal
components/micro-gateway-core/src/main/ballerina/gateway/data_writer.bal
components/micro-gateway-core/src/main/ballerina/gateway/file_rotating_timer.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal
components/micro-gateway-core/src/main/ballerina/gateway/uploade_files_timer.bal
components/micro-gateway-core/src/main/ballerina/gateway/usagedata_uploader.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/throttle_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
tests/src/test/resources/apis/pizza_shack_api.bal

Checked outputs, error messages etc. for grammar and spelling

Reviewed and fixed error messages

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/policy/ThrottlePolicyInitializer.java
components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
components/micro-gateway-core/src/main/ballerina/gateway/constants/api_throttle_out_constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/ThrottlingTestCase.java

> Fixes issue occurred when policies are not deployed 
> Added test cases

Fixed issue when policy not deployed

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java

Show an error message for invalid users and users without permissions

Fix invalid user related error handling

---

components/micro-gateway-cli/src/main/resources/distribution/bin/gateway
components/micro-gateway-cli/src/main/resources/distribution/bin/gateway.bat
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal

This PR replaces Xms and Xmx values in script and bat files. …

Adding bat and script changes for Xms and xmx values

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/data_writer.bal
components/micro-gateway-core/src/main/ballerina/gateway/dtos/analytics_dtos.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/responsetime_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/analytics_util.bal

> Added faulty analytics event
> Populate hostname and protocol

 Added faulty analytics event

---

components/micro-gateway-core/src/main/ballerina/gateway/faults_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/responsetime_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/analytics_util.bal

Adding fault data publishing to analytics.
Populate fault dto
Generate event dto using faultDTO.
Modify analytics filter to cater fault invocations.

Adding fault data publishing.

---

LICENSE.txt
README.md

- Adding LICENSE.txt 
- minor changes to readme

Adding LICENSE.txt and minor changes to readme

---

distribution/src/main/assembly/bin.xml

Copy LICENSE.txt to toolkit

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/uploade_files_timer.bal
components/micro-gateway-core/src/main/ballerina/gateway/usagedata_uploader.bal
distribution/resources/conf/micro-gw.conf
tests/src/test/resources/confs/base.conf
tests/src/test/resources/confs/default-test-config.conf
tests/src/test/resources/confs/startup.conf

Define username and password for analytics in conf file

Reading analytics username/password from conf.

---

distribution/resources/cli-conf/logging.properties
distribution/resources/conf/micro-gw.conf

Removing debug levels

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/executiontime_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authz_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
tests/src/test/java/org/wso2/micro/gateway/tests/common/MockAPIPublisher.java

> Fixed missing parameters issue

Fixed missing parameters issue

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/file_rotating_timer.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/uploade_files_timer.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
distribution/resources/conf/micro-gw.conf
tests/src/test/resources/confs/base.conf
tests/src/test/resources/confs/default-test-config.conf
tests/src/test/resources/confs/startup.conf

Enable/Disable analytics filter based on the need
Introduce a value in the conf
Read it in analytics filter (one time config reading)
If enabled, implement filtering task

Adding flag to enable/disable analytics.

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authz_filter.bal
distribution/resources/conf/micro-gw.conf

Removed unused config

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java

Handle building a project with invalid project name scenario. A valid error message is shown

Fix invalid project build scenario

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/data_writer.bal
components/micro-gateway-core/src/main/ballerina/gateway/file_rotating_timer.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/uploade_files_timer.bal
components/micro-gateway-core/src/main/ballerina/gateway/usagedata_uploader.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal

Optimizing logs for the ease of debugging.
Introduce fullError, debug methods.

Optimizing logs

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache

Fixing destination issue in service mustache.

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache

Disable http/https transports as per API's definition

 Disable http/https transports as per API's definition

---

components/micro-gateway-cli/src/main/resources/distribution/bin/gateway
components/micro-gateway-cli/src/main/resources/distribution/bin/gateway.bat
distribution/resources/bin/micro-gw.bat

- Write content of stderr and stdout to `logs/microgateway.log` file
- Suppress java info logs in `micro-gw.bat`
- Add an environment variable  to pass `api.usage.data.path` for analytics (in gateway.bat)
- Fix issue in using `help` command (in micro-gw.bat)
> Link(s) to product …

Improvements to MG bat's and sh's 

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java

- Setting get apis limit from default (25) to 500

Setting get apis limit from default (25) to 500

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal

Read analytics config at the server start up.

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/DockerCopyFile.java
components/micro-gateway-cli/src/main/resources/default-deployment-config.toml

Support multiple docker copy files from deployment config

---

components/micro-gateway-cli/src/main/resources/templates/dockerConfig.mustache
components/micro-gateway-cli/src/main/resources/templates/dockerCopyFiles.mustache

Fixes docker copy files issue.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Fixing docker copy files mustache issue

---

distribution/resources/conf/micro-gw.conf
tests/src/test/resources/confs/base.conf
tests/src/test/resources/confs/default-test-config.conf
tests/src/test/resources/confs/startup.conf

Modifying uploading endpoint url in conf 

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesConfigMapConfigItem.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
components/micro-gateway-cli/src/main/resources/templates/kubernetesConfigMap.mustache

 Issue with k8s config map

---

components/micro-gateway-cli/src/main/resources/default-deployment-config.toml

Commenting configmap unnecessary configurations …

Commenting configmap unnecessary configurations

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal

> Add null check key validation json response

Add null check

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/ContainerConfig.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Kubernetes.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/SecureKubernetesIngress.java
components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
components/micro-gateway-cli/src/main/resources/templates/kubernetes.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesIngress.mustache
components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-cli/src/main/resources/templates/secureKubernetesIngress.mustache

> Adds support for Ingresses to be used with http (9090) and https (9095) transport for the APIs exposed from the micro gateway.

Add support for Ingress - HTTP and HTTPS

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache

This PR is to remove Bal to Swagger generation. …

Removing Ballerina to Swagger generation

---

components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-cli/src/main/resources/templates/service.mustache

Fixes #199: Cannot run two (or more) APIs with in docker

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/ContainerConfig.java

Fix null check

---

components/micro-gateway-core/src/main/ballerina/gateway/annotation.bal
components/micro-gateway-core/src/main/ballerina/gateway/api_gateway_cache.bal
components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/dtos/analytics_dtos.bal
components/micro-gateway-core/src/main/ballerina/gateway/dtos/gateway_dtos.bal
components/micro-gateway-core/src/main/ballerina/gateway/dtos/throttle_dtos.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authz_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/gateway_conf.bal
components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_secure_listener.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal
pom.xml
tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java

> This PR update ballerina version from 0.975 to 0.980.0

Update ballerina version to 0.98

---

pom.xml

This PR is to upgrade ballerina version from 0.980.0 to 0.980.1 …

Upgrade ballerina version to 0.980.1

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/CopyFile.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/CopyFileConfig.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Docker.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesDeployment.java
components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache

This PR is to fix https://github.com/wso2/product-microgateway/issues/194

Add copy file support for kubernetes deployment

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/endpoints/api_gateway_endpoint.bal
distribution/resources/conf/micro-gw.conf

This PR is to fix https://github.com/wso2/product-microgateway/issues/193

Add configuration to disable SSL hostname verification for KM

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/data_writer.bal
components/micro-gateway-core/src/main/ballerina/gateway/dtos/analytics_dtos.bal
components/micro-gateway-core/src/main/ballerina/gateway/executiontime_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/responsetime_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/analytics_util.bal

With the move to SP in 2.6 we need to combine request,response,execution event streams into a single stream and publish it in the response path. This PR implements this functionality.

Combining request,response,execution events to a single stream

---

distribution/pom.xml
distribution/src/main/assembly/bin.xml
tests/pom.xml

This PR removes the name "toolkit" from the microgateway distribution. …

Remove name toolkit from the distribution

---

README.md
README.txt
components/micro-gateway-cli/src/main/resources/cli-help/cli-default.help
components/micro-gateway-cli/src/main/resources/cli-help/cli-help.help
components/micro-gateway-cli/src/main/resources/cli-help/cli-reset.help
components/micro-gateway-cli/src/main/resources/cli-help/cli-setup.help
distribution/resources/bin/micro-gw
distribution/resources/bin/micro-gw.bat
distribution/resources/cli-conf/logging.properties

This PR removes the name "toolkit" from other referenced files. …

Remove name toolkit from other references

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal

Enable access to valid JWT token which is not subscribed to API
JWT token which is valid and not subscribed to any API can access to API in the micro-gateway. …

Enable access to valid JWT token which is not subscribed to API

---

components/micro-gateway-core/src/main/ballerina/gateway/file_rotating_timer.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/analytics_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal

Analytics refactoring

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal

allow access to valid JWT token which is not subscribed to any API.
valid JWT able to access the resources in API which is not subscribed to any API. …

Access with valid jwt

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/data_writer.bal
components/micro-gateway-core/src/main/ballerina/gateway/dtos/analytics_dtos.bal
components/micro-gateway-core/src/main/ballerina/gateway/dtos/throttle_dtos.bal
components/micro-gateway-core/src/main/ballerina/gateway/faults_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/file_rotating_timer.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/gateway/responsetime_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/analytics_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/throttle_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal

Fault and Throttle event support for MGW analytics 2.6.0

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
components/micro-gateway-cli/src/main/resources/cli-help/cli-setup.help
tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
tests/src/test/resources/confs/default-cli-test-config.toml
tests/src/test/resources/confs/default-test-config.conf

Add Insecure Options

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/dtos/throttle_dtos.bal
components/micro-gateway-core/src/main/ballerina/gateway/responsetime_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/analytics_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/throttle_util.bal

This PR will populate the hostname field in analytics stream to the value of "datacenterId" env variable if specified.

Populating datacenterId for hostname field

---

pom.xml

This PR upgrades the ballerina version to 0.981.1 …

Upgrade Ballerina Version

---

distribution/resources/filters/extension_filter.bal

Rectify method comments

---

components/micro-gateway-core/src/main/ballerina/gateway/usagedata_uploader.bal

When the zip is uploaded using microgateway, the FILE_CONTENT in the DB was null. This PR fixes this issue,

Fix File_content null issue

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
tests/src/test/resources/confs/default-cli-test-config.toml

This PR upgrades Rest API version to v0.14

Upgrade Rest API version to v0.14

---

distribution/resources/conf/micro-gw.conf

resolves #https://github.com/wso2/product-apim/issues/3562

Change Issuer Url in JWT

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal

This PR introduces new throttling tier for unsubscribed APIs

Introduce new throttling tier for unsubscribed APIs

---

distribution/resources/updates/product.txt

Change wum product name for in-place update …

Change wum product name for in-place update

---

components/micro-gateway-cli/pom.xml
components/micro-gateway-core/pom.xml
components/pom.xml
distribution/pom.xml
pom.xml
tests/pom.xml

update versions for next release
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …

Prepare for next release

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal

> With this commit mico gw toolkit can be used with APIM v3

Make micro gw compatible with APIM v3

---

components/micro-gateway-cli/pom.xml
components/micro-gateway-core/pom.xml
components/pom.xml
distribution/pom.xml
pom.xml
tests/pom.xml

Alter micro gateway version to 3.0.0-SNAPSHOT

---

components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
distribution/resources/conf/micro-gw.conf

> Provide support for fail over and load balanced endpoints for micro gateway v3

V3 micro gateway load balance and failover endpoint support

---

pom.xml

> Update carbon-apimgt version

Update apimgt version

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
pom.xml
tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/IntrospectInfo.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/MockAPIPublisher.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
tests/src/test/java/org/wso2/micro/gateway/tests/services/AuthenticationFailureTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/APIInvokeTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/ThrottlingTestCase.java
tests/src/test/resources/api-json.json
tests/src/test/resources/application-policies.json
tests/src/test/resources/confs/base.conf
tests/src/test/resources/confs/default-cli-test-config.toml
tests/src/test/resources/confs/default-test-config.conf
tests/src/test/resources/confs/startup.conf

> Re enable test module for micro-gw v3
> Throttling and subscription related tests are disabled for now, since micro-gw v3 still does not have that support

Enable test module for v3

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIDetailedDTO.java

This fixes issue caused by not recognizing the newly introduced apiSecurity field of an API object which was introduced via the mutual SSL feature
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …

Fix for https://github.com/wso2/product-apim/issues/3890

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ExternalUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenApiCodegenUtils.java
components/micro-gateway-cli/src/main/resources/policies/application_10PerMin.bal
components/micro-gateway-cli/src/main/resources/policies/application_20PerMin.bal
components/micro-gateway-cli/src/main/resources/policies/application_50PerMin.bal
components/micro-gateway-cli/src/main/resources/policies/subscription_Bronze.bal
components/micro-gateway-cli/src/main/resources/policies/subscription_Gold.bal
components/micro-gateway-cli/src/main/resources/policies/subscription_Silver.bal
components/micro-gateway-cli/src/main/resources/policies/subscription_Unauthenticated.bal
components/micro-gateway-cli/src/main/resources/policies/throttle_policy_initializer.bal
distribution/src/main/assembly/bin.xml

> The existing Microgateway loads the api via contacting the API Manager instance that should be up and running. This feature gives the option to setup the Microgateway without an API Manager instance running, by using a open api specification file.

Developer-First Microgateway Creation

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/api_security_constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/cookie.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/CookieAuthTestCase.java
tests/src/test/resources/testng.xml

Provide authentication for product micro-gateway with basic authentication which uses usernames and passwords for authentication.
Providing feature of enabling Cookie based authentication for to product micro-gateway along with OAuth2 token based authentication. User will be benefited with using only OAuth2 token based authentication alone, or using Cookie to authenticate micro-gateways.
When an user invoke an API with a cookie, micro-gateway has to validate that cookie prior to the response. The list of cookies included in the HTTP request which use to authenticate, have to be extracted from the request. From all extracted cookies,their respective session ID value has to be extracted properly.
The Authn filter will check incoming request to micro-gateway and determine whether it contains …

Add Cookie based authentication for Micro-gateway master branch

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/api_security_constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/cookie.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/CookieAuthTestCase.java
tests/src/test/resources/testng.xml

Provide authentication for product micro-gateway with basic authentication which uses usernames and passwords for authentication.
Providing feature of enabling Cookie based authentication for to product micro-gateway along with OAuth2 token based authentication. User will be benefited with using only OAuth2 token based authentication alone, or using Cookie to authenticate micro-gateways.
When an user invoke an API with a cookie, micro-gateway has to validate that cookie prior to the response. The list of cookies included in the HTTP request which use to authenticate, have to be extracted from the request. From all extracted cookies,their respective session ID value has to be extracted properly.
The Authn filter will check incoming request to micro-gateway and determine whether it contains …

Add Cookie based authentication for micro-gateway 2.X branch

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIDetailedDTO.java
components/micro-gateway-cli/src/main/resources/templates/generateSwagger.mustache
components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-core/src/main/ballerina/gateway/constants/api_security_constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/executiontime_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/validation_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/validation_util.bal
tests/PizzaShackAPI_swagger.json
tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/ValidationTestCase.java
tests/src/test/resources/confs/validation.conf
tests/src/test/resources/testng.xml

The WSO2 API Manager Microgateway currently does not have an approach to validate client requests that are sent to the Microgateway and also to validate responses coming from the backend. This feature will validate requests/responses based on a predefined API schema.
Providing feature of enabling schema based request/response validation for product-microgateway. The user will be able to enable request validation, response validation or both request and response validation.
1. Validating a request
- Sending a valid request
- Sending an invalid request
2.  Validating a response
- Backend sends a valid response
- Backend sends an invalid resposponse
Whenever a request comes to the microgateway that request should be validated against the swagger file of the requested API. If the request is …

Add API schema based request/response validation

---

components/micro-gateway-core/src/main/ballerina/gateway/file_rotating_timer.bal

Fix semantic errors in file_rotating_timer

---

components/micro-gateway-core/src/main/ballerina/gateway/utils/analytics_util.bal

Fix syntax issues for ballerina update

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/authz_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_secure_listener.bal

>  Remove EndpointConfig from listeners and use http:ServiceEndpointConfiguration.
> Refactor listeners in order to work with new b7a version

Improve listeners in order to update b7a version

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/validation_filter.bal

> Fix validation filter semantic issues

Fix validation filter issues

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/mutualSSL_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal

Fix issues with analytics_request_filter.bal, mutualSSL_filter.bal, throttle_filter.bal

Fix semantic issues with gateway ballerina files

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal

> Migrate subscription_filter.bal

Migrate subscription_filter.bal

---

components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal

Fix the compilation issues in oauthn_handler.bal.

Fix compilation issues in oauthn_handler

---

components/micro-gateway-core/src/main/ballerina/gateway/utils/validation_util.bal

 Fix ballerina upgrade

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GRPCUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/BalFileGenerationUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/grpc/GrpcGen/DescriptorsGenerator.java
components/micro-gateway-cli/src/main/resources/policies/throttle_policy_initializer.bal
components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/http2.mustache
components/micro-gateway-cli/src/main/resources/templates/httpEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/subscription_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/throttle_util.bal
distribution/pom.xml
distribution/resources/bin/micro-gw
distribution/resources/bin/micro-gw.bat
distribution/resources/filters/extension_filter.bal
distribution/src/main/assembly/bin.xml

>  Fix compilation and semantic issues when updating b7a version

Fix compile issues after b7a update

---

components/micro-gateway-cli/src/main/resources/distribution/bin/gateway
components/micro-gateway-cli/src/main/resources/policies/throttle_policy_initializer.bal
components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
components/micro-gateway-core/src/main/ballerina/gateway/annotation.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authz_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/mutualSSL_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/validation_filter.bal
distribution/resources/filters/extension_filter.bal

> Fix the issues in templates and filters

Fix template and build time issues

---

components/micro-gateway-cli/src/main/resources/distribution/bin/gateway
components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-core/src/main/ballerina/gateway/annotation.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_secure_listener.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal

> Fix until the jwt basic flow works after b7a update
> Need to remove the generated policy files in order to work.

Fix jwt basic flow after b7a upgrade

---

components/micro-gateway-cli/src/main/resources/distribution/bin/gateway
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal

> Fix oauth2 flow issues
> Since json to object conversion is failing in new version, we are manually creating the DTO object from json which is received from key validation service.

Fix oauth2 scenarios after b7a update

---

components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache

> Update load balance and fail over templates to work with new b7a version

Update faiover and load balance templetes

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java

Fix endpoint config flag

---

components/micro-gateway-cli/src/main/resources/templates/policy.mustache

adding functionName

---

README.txt

Improving README.md readability.
Same as above.
Rewrote elements of the first section of README.md.
Made changes to the first section of README.md to improve readability
N/A, simply changed some wording in README.md
N/A, simply changed some wording in README.md
N/A, simply changed some wording in README.md
N/A, simply changed some wording in README.md
N/A, simply changed some wording in README.md
N/A, simply changed some wording in README.md
N/A, simply changed some wording in README.md
N/A, simply changed some wording in README.md
N/A, simply changed some wording in README.md
N/A, simply changed some wording in README.md

Improved readability in README.md

---

components/micro-gateway-core/src/main/ballerina/gateway/annotation.bal
components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/dtos/gateway_dtos.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/mutualSSL_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/oauthn_handler.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal

> Properly declare  dto variables(optional, required and assign default values)
> Change annotation types correctly
> Read configs one time and save it
> Remove adding default values in subscription and mutual ssl filter, because dto is now populated with default values.
> Proper error handling in oauthn_handler
> Completer ballerina update and gain performance imrpvements

Add code review suggestions

---

components/micro-gateway-cli/src/main/resources/templates/policy.mustache

fix a formatting issue in mustache file

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache

Adding CORS allowMethods to template

Adding CORS allowMethods to template

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache

Removing "Expect" header from the request if the request is expecting a 100 continue header.

Removing "Expect" header from the request

---

tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/DistributedThrottlingTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/ThrottlingTestCase.java

> The PR will resolve the distributed throttling test issues.

Fixed Distributed test issue

---

components/micro-gateway-core/src/main/ballerina/gateway/basicAuth.bal
components/micro-gateway-core/src/main/ballerina/gateway/constants/api_security_constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/APIInvokeWithOAuth2andBasicAuthTestCase.java
tests/src/test/resources/testng.xml

> Fix issues in basic auth feature
> Fix basic auth integration tests

Fix basic auth feature after b7a upgrade

---

components/micro-gateway-core/src/main/ballerina/gateway/endpoints/api_gateway_endpoint.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/usagedata_uploader.bal
distribution/resources/conf/micro-gw.conf

> Fixing the bug of subscription validation when third party jwt is used after the b7a update
> Add host name verification  skip ability when connecting with analytics file upload endpoint

Fix subscription validation and analytics host verfication issue

---

distribution/resources/updates/product.txt
distribution/src/main/assembly/bin.xml
distribution/src/main/assembly/filter.properties

Reverts wso2/product-microgateway#362

Revert "Add product version to filter properties"

---

distribution/resources/updates/product.txt
distribution/src/main/assembly/bin.xml
distribution/src/main/assembly/filter.properties

Fixes: #243
This will help update delivery clients to identify the product version.

Add product version to filter properties

---

components/micro-gateway-cli/src/main/resources/distribution/bin/gateway.bat

gateway.bat file was not updated to work with the latest ballerina changes. PR will fix an identified issue.

Fix gateway.bat issue

---

distribution/src/main/assembly/bin.xml

fixing Readme.txt issue

---

components/micro-gateway-cli/src/main/resources/policies/application_10PerMin.bal
components/micro-gateway-cli/src/main/resources/policies/application_20PerMin.bal
components/micro-gateway-cli/src/main/resources/policies/application_50PerMin.bal
components/micro-gateway-cli/src/main/resources/policies/subscription_Bronze.bal
components/micro-gateway-cli/src/main/resources/policies/subscription_Gold.bal
components/micro-gateway-cli/src/main/resources/policies/subscription_Silver.bal
components/micro-gateway-cli/src/main/resources/policies/subscription_Unauthenticated.bal
components/micro-gateway-cli/src/main/resources/templates/policy.mustache
components/micro-gateway-core/src/main/java/org/ballerina/gateway/siddhi/extension/EmitOnStateChange.java
components/micro-gateway-core/src/main/java/org/ballerina/gateway/siddhi/extension/ThrottleStreamProcessor.java
distribution/resources/bin/micro-gw

Reverts wso2/product-microgateway#344

Revert "Ballerina siddhi"

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal

changing constant file

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java

> Fix the issue : https://github.com/wso2/product-microgateway/issues/249

Fix for wso2/product-microgateway#271

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/AddCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/GatewayCliCommands.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ListCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIMetadataDTO.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/JsonProcessingUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenApiCodegenUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/OASAPIInvokeTestCase.java

> Resolve the bugs (identified by integration tests) and implementation of "add api" command.

Cli restructure

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/policy/ThrottlePolicy.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/policy/ThrottlePolicyInitializer.java

> Fixes the issue : https://github.com/wso2/product-microgateway/issues/358

fix issue #358

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/AddCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/GatewayCliCommands.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ListCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/SetupCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/HashUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ext/ExtendedAPI.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenApiCodegenUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/SwaggerUtils.java
components/micro-gateway-cli/src/main/resources/templates/failoverResourceEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/httpResourceEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/lbResourceEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/service.mustache

>  "list apis" command is implemented. In addition, the issues and bugs related to "add cmd" are resolved.

Implement "List APIs/Resources" and "Add Route" Cmds 

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/FunctionCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/GatewayCliCommands.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointConfig.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java

>This feature support users to define custom mediation functions and add them to the “request in” and “request out” in global, API and resource levels. 
>Provide set of commands that enable users to add custom mediation functions.

New feature to provide support for adding custom mediation as a function

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/logging/CLILogConfigReader.java
distribution/resources/bin/micro-gw
distribution/resources/bin/micro-gw.bat

This will update the distribution CLI tools to work with the current toolkit structure, after the changes made in #361 
- Update LogManager reference to CLILogManager
- Update .bat after restructure
- Update code styling of scripts

Update CLI tools after toolkit restructure

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaParameter.java

> This PR is needed to merge the PRs 
https://github.com/wso2/product-microgateway/pull/355
https://github.com/wso2/product-microgateway/pull/368/

Update BallerinaParameter model to match with new swagger model version

---

CONTRIBUTING.md

Introduce initial version of project contributing guideliness

Initiate project contributing guide

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/GatewayCliCommands.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/ThrottlePolicyGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
distribution/resources/bin/micro-gw
distribution/resources/bin/micro-gw.bat
tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java

Init command will replace the behavior of previous setup command. Generated project structure is also updated.
|_api_definitions
|_conf
|_definition.yaml
|_gen
|_interceptors
|_policies.yaml
|_target

Introduce init command

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
tests/src/test/resources/testng.xml

> Resolve throttle policy related issue related to Import Command.

Resolve Throttle Policy Enforcement in Import Command

---

pom.xml

fixing pom versions

---

tests/src/test/java/org/wso2/micro/gateway/tests/context/Constants.java
tests/src/test/java/org/wso2/micro/gateway/tests/context/ServerInstance.java

> To fix the throttling test cases

Copy the policies.yaml to test running pack

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/resources/templates/jwtRevocation.mustache
components/micro-gateway-cli/src/main/resources/templates/main.mustache
components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/endpoints/etcd_token_revocation_endpoint.bal
components/micro-gateway-core/src/main/ballerina/gateway/jwt_authentication_handler.bal
components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/gateway/revoked_token_map.bal
components/micro-gateway-core/src/main/ballerina/gateway/services/token_revocation_event_listener.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/token_revocation_etcd_util.bal
distribution/pom.xml
distribution/resources/conf/micro-gw.conf
distribution/resources/filters/token_revocation_extension.bal
tests/src/test/java/org/wso2/micro/gateway/tests/common/MockETCDServer.java
tests/src/test/java/org/wso2/micro/gateway/tests/jwtRevocation/JWTRevocationSupportTestCase.java
tests/src/test/resources/confs/default-test-config.conf
tests/src/test/resources/testng.xml

`dev_first` has conflicts with master after merging #420

Resolve conflict with master

---

components/micro-gateway-cli/src/main/resources/templates/main.mustache
distribution/resources/conf/micro-gw.conf

> By default disable jwt revocation feature
> Fix issues in build command

Fix issues in revocation feature

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesSecret.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesSecretItem.java
components/micro-gateway-cli/src/main/resources/templates/kubernetesSecret.mustache

> Fixes the issue : https://github.com/wso2/product-microgateway/issues/401

fixes the issue #401: k8s secret not working

---

tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/OASAPIInvokeTestCase.java
tests/src/test/resources/definition.yaml

>fix the OASAP JWT token invocation test case.

Fixing OASAPI JWT token invocation test fails #454

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java

>Fixes for no arguments in Linux CLI

fixing Error when no arguments are provided for linux CLI #446

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/AddAPICmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/AddRouteCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/FunctionCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ListAPIsCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ListResourcesCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/UpdateRouteCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIDefinition.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwdefinition/MgwAPIsDefinition.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionUtils.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache

> Assigns UUID for each operation id.

fix the issue API level interceptors implementation. fixes #450 and #444

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/SecureKubernetesIngress.java
components/micro-gateway-cli/src/main/resources/templates/dockerConfig.mustache
components/micro-gateway-cli/src/main/resources/templates/secureKubernetesIngress.mustache

> Fixes the issue : https://github.com/wso2/product-microgateway/issues/449

Fix #449 - enableTLS should be configurable in k8s ingress

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
distribution/resources/bin/micro-gw
distribution/resources/bin/micro-gw.bat

> Checking the hash value of the extracted platform as it is a time-consuming task.
Applied the same change applied in https://github.com/wso2/product-microgateway/pull/379/files

Remove Hash Value Checking and Fixes #446

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/responsetime_util.bal

> Improvement for : https://github.com/wso2/product-microgateway/issues/228
> If response is chunked currently we are not building the message. Response size will be sent as zero

Improvement for #228 : analytics response size set to zero

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java

> Resolve the error occurs due to unavailability of the verbose flag while running tests.

fix the issue occurs due to unavailability of verbose property

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-cli/src/main/resources/cli-help/cli-build.help
components/micro-gateway-cli/src/main/resources/cli-help/cli-help.help
components/micro-gateway-cli/src/main/resources/cli-help/cli-import.help
components/micro-gateway-cli/src/main/resources/cli-help/cli-init.help
tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java

> Fixes #473 
Fixes #474 
> Fix the issue regarding the default version support in import cmd

Add deployment-Config Path with build command, Fix the issue with help command

---

components/micro-gateway-core/src/main/ballerina/gateway/services/token_revocation_event_listener.bal

> fixing for the test failure testRevokedTokenResponse

 Fixes for test failure testRevokedTokenResponse

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java

Fix bug in support for default version

---

components/micro-gateway-cli/pom.xml
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/APIDefinition.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/APIDefinitions.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/DefinitionConfig.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/EndpointListDefinition.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/PathsDefinition.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/definition/ResourceDefinition.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinition.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionBuilder.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/YamlValidator.java
components/micro-gateway-cli/src/main/resources/definition-schema.json
distribution/src/main/assembly/bin.xml
pom.xml

YAML validator is required for validating different yaml files such as definition.yaml, policies.yaml. This validator implementation can be used later for validating such documents. Rules included in definition-schema.json is not yet complete. We need to have a discussion and review these rules to finalize schema
Fixes #445

Introduce yaml schema validation

---

components/micro-gateway-cli/src/main/resources/templates/prodEndpointReinit.mustache
components/micro-gateway-cli/src/main/resources/templates/sandEndpointReinit.mustache
components/micro-gateway-cli/src/main/resources/templates/service.mustache

> Fix build issues when --etcd is used

Fix issues with etcd related templates

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
distribution/resources/bin/micro-gw
distribution/resources/bin/micro-gw.bat

Recent fixes done for CLI has made micro-gw.bat file unstable. This PR will resolve critical functionality issues in the bat file. 
Partial resolution for #428

Fix issues in micro-gw.bat

---

components/micro-gateway-cli/src/main/resources/templates/prodEndpointReinit.mustache
components/micro-gateway-cli/src/main/resources/templates/sandEndpointReinit.mustache
components/micro-gateway-cli/src/main/resources/templates/service.mustache

>  Persist is_etcd_enabled variable during init command. Related to #479

Persist "is_etcd_enabled" variable during init command

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java

> introduce '--etcd' parameter instead of '-etcd' and '--enabled-etcd' parameters.
Related to #481

change -etcd paramter to --etcd

---

README.md

Re word the content to bring more meaning.
> Link(s) to product documentation that addresses the changes of this PR. If no doc …

Reword the content.

---

distribution/pom.xml
distribution/resources/bin/gateway
distribution/resources/bin/gateway.bat
distribution/src/main/assembly/ballerina_runtimes/runtime_linux_zip.xml
distribution/src/main/assembly/ballerina_runtimes/runtime_macos_zip.xml
distribution/src/main/assembly/ballerina_runtimes/runtime_windows_zip.xml
distribution/src/main/assembly/bin.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
pom.xml
tests/pom.xml

> Separate the toolkit and run time as two distributions.
> There will be three run time distributions created for Linux, mac, and windows operating systems
> For now we are keeping the run time inside toolkit as well. This can be removed once the integration tests are refactored to work with new restructure.

Separate toolkit and runtime

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ext/ExtendedAPI.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/route/EndpointListRouteDTO.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/MgwDefinitionBuilder.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache
pom.xml
tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
tests/src/test/resources/testapi.json

> To have an openAPI definition as the only required resource for the dev-first approach to avoid having duplicate records over different configuration.

Dev-First Approach using openAPI definition only. Fixes #325

---

README.md
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APICorsConfigurationDTO.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
samples/cors_sample.yaml
samples/interceptors_sample.yaml
samples/per_resource_endpoint.yaml
samples/petstore_basic.yaml
samples/petstore_swagger3.yaml
samples/policies_sample.yaml

> Add readme samples with open API extensions

Update README with new swagger extension samples

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ext/ExtendedAPI.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
tests/src/test/resources/testapi.json

> Support resource level security for oauth2, basic and JWT
> Support for the scopes in oauth2 security schemes
> Add security-disable option
> Fixes #504

Provide resource level security, support for scopes and fixes #504

---

README.md

Add jenkins build status to README

---

README.md
docker/Dockerfile
docker/conf/micro-gw.conf
samples/security_sample.yaml

> Add quick start section to README
> Add security samples

Add quick start to README

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/HashingConstants.java
components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache

> Fixes : https://github.com/wso2/product-microgateway/issues/520
> Change hashing algorithm to sha-256

Fix for issie #520 : K8s fails when copy files are used

---

distribution/resources/bin/gateway
distribution/resources/bin/gateway.bat
distribution/src/main/assembly/ballerina_runtimes/runtime_linux_zip.xml
distribution/src/main/assembly/ballerina_runtimes/runtime_macos_zip.xml
distribution/src/main/assembly/ballerina_runtimes/runtime_windows_zip.xml

> Fix issue : https://github.com/wso2/product-microgateway/issues/524
> Fix issue : https://github.com/wso2/product-microgateway/issues/526

Fixes issue #524: Error in gateway runtime script

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
distribution/resources/bin/micro-gw
samples/security_sample.yaml

> Fixes : https://github.com/wso2/product-microgateway/issues/532
> Modify readme with basic security type

Fix #532 : Issue in API level throttling

---

README.md
components/micro-gateway-core/src/main/ballerina/gateway/basicAuth.bal

> Fixes : https://github.com/wso2/product-microgateway/issues/537
> Update README to position the quick start on top

Fixes #537 : Basic auth issue

---

README.md
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-core/src/main/ballerina/gateway/filters/authn_filter.bal
distribution/resources/bin/gateway.bat

> Fix issues in .bat file
> Change generation of API ID using hash of API name and version

Fix issues in bat file

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
pom.xml
tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/APIInvokeWithBasicAuthTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/APIInvokeWithOAuth2andBasicAuthTestCase.java
tests/src/test/resources/api-definition.json

Tests were failing after moving to swagger based gateway definition.

Fix test cases

---

tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/ThrottlingTestCase.java
tests/src/test/resources/policies.yaml

> Fix throttle and distributed throttling test cases

Fix test failures

---

distribution/pom.xml
distribution/resources/bin/gateway
distribution/resources/bin/gateway.bat
distribution/src/main/assembly/ballerina_runtimes/runtime_linux_zip.xml
distribution/src/main/assembly/ballerina_runtimes/runtime_macos_zip.xml
distribution/src/main/assembly/ballerina_runtimes/runtime_windows_zip.xml
pom.xml

> Include open jdk to OS dependent run times

Pack open jdk to run times

---

components/micro-gateway-cli/src/main/resources/templates/failoverEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/lbEndpoint.mustache

fix lb/failover endpoint syntax issue

---

README.md
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/DistributedThrottlingTestCase.java
tests/src/test/resources/testapi.json

> Fix https://github.com/wso2/product-microgateway/issues/559
> Fix test failures

Fix #559 and test failures

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/GatewayLauncherCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/HelpCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ResetCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/exception/CliLauncherException.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java

Usage details will be printed using jcommander. Other help content will be still available using the cli-help files.
Fixes #560

Fix jcommander usage and help issues

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache

> Fix https://github.com/wso2/product-microgateway/issues/575

Fix #575 - baspath trailing / character issue

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-cli/src/main/resources/templates/useAPIProdEp.mustache
components/micro-gateway-cli/src/main/resources/templates/useApiSandEp.mustache
components/micro-gateway-cli/src/main/resources/templates/useResourceProdEp.mustache
components/micro-gateway-cli/src/main/resources/templates/useResourceSandEp.mustache
components/micro-gateway-core/src/main/ballerina/gateway/responsetime_util.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal

There were some issues in published events for dev first APIs. This PR will fix those issues.
Fixes #558

Fix issues in analytics data

---

distribution/LICENSE-RUNTIME.txt
distribution/LICENSE-TOOLKIT.txt

Update license for 3.0.1 release

Update License for 3.0.1

---

distribution/src/main/assembly/filter.properties

Update product version property used by WUM

Update product version property

---

components/micro-gateway-cli/pom.xml
components/micro-gateway-core/pom.xml
components/micro-gateway-tools/pom.xml
components/pom.xml
distribution/pom.xml
pom.xml
tests/pom.xml

3.0.1-rc1 vote failed. Therefore reverting the dev version back to initial version

Revert back to 3.0.1-SNAPSHOT

---

README.md
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-cli/src/main/resources/templates/openAPIJsonConstants.mustache
components/micro-gateway-core/src/main/ballerina/gateway/filters/validation_filter.bal
samples/cors_sample.yaml
samples/endpoint_by_reference_sample.yaml
samples/interceptors_sample.yaml
samples/per_resource_endpoint.yaml
samples/petstore_basic.yaml
samples/policies_sample.yaml
samples/security_sample.yaml
tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
tests/src/test/java/org/wso2/micro/gateway/tests/context/ServerInstance.java
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/OASAPIInvokeTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/toolkit/ValidationTestCase.java
tests/src/test/resources/PizzaShackAPI_swagger.json
tests/src/test/resources/api-definition.json
tests/src/test/resources/testapi.json

> Fix https://github.com/wso2/product-microgateway/issues/580

Fix #580: Change Open API extensions

---

components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/validation_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/validation_util.bal
tests/src/test/resources/api-definition.json
tests/src/test/resources/confs/validation.conf

> Fixes schema validator issue in Open API 3.0.1.

fix validator swagger3

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/resources/templates/main.mustache
distribution/resources/filters/startup_extension.bal
tests/src/test/java/org/wso2/micro/gateway/tests/context/ServerInstance.java

> Fix https://github.com/wso2/product-microgateway/issues/587

Fix #587 : startup extension for gateway

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/validation_filter.bal
distribution/resources/conf/micro-gw.conf
tests/src/test/resources/confs/validation.conf

> Removed swagger reference entry from micro-gw.conf

removing swagger reference from validator

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointDTO.java

fix the issue where the default URL is not taken into account when etcd option is provided.

Bug fix related to default URL in etcd endpoints

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/mutualSSL_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/filters/validation_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/validation_util.bal

> Fixing Throttle out message is incorrect (#595)

fixes #595

---

components/micro-gateway-core/src/main/ballerina/gateway/uploade_files_timer.bal

Avoid unwanted error message

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-core/src/main/ballerina/gateway/data_writer.bal
components/micro-gateway-core/src/main/ballerina/gateway/upload_files_timer.bal
pom.xml

Event details written to stat data file was getting overridden due to missing `append=true` property, while opening the file channel.
Fixes #600

Fix stat event appending issue

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GatewayCliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-core/src/main/ballerina/gateway/endpoints/api_gateway_endpoint.bal
distribution/resources/tokenServices/authorize_endpoint.bal
distribution/resources/tokenServices/revoke_endpoint.bal
distribution/resources/tokenServices/token_endpoint.bal
distribution/resources/tokenServices/user_info_endpoint.bal
distribution/src/main/assembly/bin.xml

> 9096 port can not be exposed in k8s as a k8s service. This will fix that issue
> Move the /token, /authorize and etc services to the project.
> Move the 9096 listener also to the listener.mustache file
> Fix https://github.com/wso2/product-microgateway/issues/609

Fix issue in exposing 9096 ports in k8s environments

---

components/micro-gateway-cli/pom.xml
components/micro-gateway-core/pom.xml
components/micro-gateway-tools/pom.xml
components/pom.xml
distribution/pom.xml
pom.xml
tests/pom.xml

3.0.1-rc2 failed therefore reverting the dev version back to 3.0.1-snapshot.

Revert dev version

---

distribution/resources/bin/gateway
distribution/resources/bin/gateway.bat
distribution/src/main/assembly/gw_runtimes/gw_runtime.xml

>  b7a.http.worker.nonblocking=true should be removed from default startup script. 
> if wanted can be added as environment variable or as a argument.

remove non blocking parameter from startup scripts

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointDTO.java

> Identify malformed URLs which are provided as production/sandbox endpoints.

Identify malformed URLs

---

release-notes.html

`release-notes.html` file in product .zip distribution was not updated for 3.0.1 release. This PR will update it.

Update release notes for 3.0.1

---

release-notes.html

Update release note

---

tests/src/test/java/org/wso2/micro/gateway/tests/extensions/OASAPIInvokeTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/http2/HTTP2RequestsWithHTTP1BackEndTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/http2/HTTP2RequestsWithHTTP2BackEndTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithBasicAuthTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuth2andBasicAuthTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/security/APIInvokeWithOAuthTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/security/AuthenticationFailureTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/security/CookieAuthTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/security/MutualSSLTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/throttling/DistributedThrottlingTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/throttling/PreRequisites.java
tests/src/test/java/org/wso2/micro/gateway/tests/throttling/ThrottlingTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/validation/ValidationTestCase.java
tests/src/test/resources/testng.xml
tests/src/test/resources/testngEtcd.xml

> Restructure test class packages for #625

Initailly restructure test cases for #625

---

tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/MultipleEndpointsTestCase.java
tests/src/test/resources/openAPIs/common_api.yaml
tests/src/test/resources/testng.xml

> Load balance endpoint test case
> Fail over endpoints test case
> Improvement for #625

Add load balance fail over endpoint test cases : #625

---

tests/src/test/java/org/wso2/micro/gateway/tests/common/BaseTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/MultipleEndpointsTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/ResourceLevelEndpointsTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/extensions/OASAPIInvokeTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/validation/ValidationTestCase.java
tests/src/test/resources/openAPIs/endpoints/fail_over.yaml
tests/src/test/resources/openAPIs/endpoints/load_balance.yaml
tests/src/test/resources/testng.xml

> Add API level load balance endpoints
> Add API level failover endpoints
> Improvement for #625

API level load balance and fail over tests #625

---

tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
tests/src/test/java/org/wso2/micro/gateway/tests/throttling/OpenApiThrottlingTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/throttling/ThrottlingTestCase.java
tests/src/test/resources/openAPIs/common_api.yaml
tests/src/test/resources/policies.yaml
tests/src/test/resources/testng.xml

add test case for API/Resource level throttling policies : #625

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache
tests/src/test/java/org/wso2/micro/gateway/tests/security/ScopesTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/util/TokenUtil.java
tests/src/test/resources/openAPIs/common_api.yaml
tests/src/test/resources/testng.xml

> Fix #635 
> Add test cases for scopes
> Improvement for #625

Fix #635 : Issue when multiple scopes are used

---

tests/src/test/java/org/wso2/micro/gateway/tests/security/DisableSecurityAndCustomAuthHeaderTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/util/HttpClientRequest.java
tests/src/test/java/org/wso2/micro/gateway/tests/util/TestConstant.java
tests/src/test/resources/openAPIs/common_api.yaml
tests/src/test/resources/openAPIs/security/disable_security.yaml
tests/src/test/resources/testng.xml

> Add test cases for disable security at API/resource level
> Add test cases for custom authentication header
> Improvement for #625

Disable security and custom auth header test cases

---

components/micro-gateway-core/pom.xml
components/micro-gateway-tools/pom.xml
distribution/pom.xml
pom.xml

This changes is required to merger PR : https://github.com/wso2/product-microgateway/pull/384
since attached goal is removed from new version
https://github.com/wso2/product-microgateway/pull/384
Not Tested
---

Changes needed to update assembly plugin version

---

pom.xml
tests/pom.xml

Update andes version with regards to : https://github.com/wso2/product-microgateway/pull/555
https://github.com/wso2/product-microgateway/pull/555
Not Tested
---

Update andes version

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/rest/RESTAPIServiceImpl.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RESTAPIUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ZipUtils.java
pom.xml

Enable checkstyle plugin for `org.wso2.apimgt.gateway.cli.utils` package in `cli` component.
Related to #647 
- Linux
- Java 8
---

Enable checkstyle on org.wso2.apimgt.gateway.cli.utils

---

README.md

FIxes grammatical errors in the readme file.
fixes #651 
- Unit tests added: NA
- Integration tests added: NA
NA
---

Fix grammar and spelling in readme

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cipher/AESCipherTool.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cipher/AESCipherToolException.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/config/TOMLConfigParser.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/exception/CLIInternalException.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/exception/CLIRuntimeException.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/hashing/HashUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/logging/CLILogManager.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/builder/DCRRequestBuilder.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/builder/OAuthTokenRequestBuilder.java
pom.xml

Resolve issues in following packages.
1. org.wso2.apimgt.gateway.cli.logging.*
1. org.wso2.apimgt.gateway.cli.config.*
1. org.wso2.apimgt.gateway.cli.exception.*
1. org.wso2.apimgt.gateway.cli.hashing.*
1. org.wso2.apimgt.gateway.cli.oauth.*
1. org.wso2.apimgt.gateway.cli.cipher.*
Related #647 
Linux
Java 8
---

Fix more checkstyle issues

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Token.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ClientCertificatesDTO.java

There were some javadoc comments that are not complete.
Related to #647 
Not Tested
---

Fix incomple java docs

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/SecureKubernetesIngress.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
components/micro-gateway-cli/src/main/resources/templates/listeners.mustache

Fixes the compile time issue when k8s ingress is used
Fix: #676
mac-os
---

Fix #676 : build error when k8s ingress is used

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache

If we add multiple scopes to same resource in the open API definition, API invocation fails even with correct jwt as well.
This PR fixes that issue
Fixes #635 
- Integration tests added: Will provide with test refactoring
Not Tested
---

Fix #635 - Multiple scope validation issue

---

distribution/resources/bin/gateway.bat
samples/security_sample.yaml

Fix for Gateway runtime does not start at special locations in Windows
https://github.com/wso2/product-microgateway/issues/702

fixes for #709

---

components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/api_gateway_endpoint.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authn_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal

Migrate the listeners, and initialize handlers for the authentication
Fixes #717 
Not Tested
---

Update listerners, and caches related files

---

components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/usagedata_uploader.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/lang_utils.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/subscription_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal

Ballerina has removed some of the required string utility methods from ballerina string type. Until these methods are implemented in wso2/string util package, mgw will have to use these util methods to implement it's functionalities.
Related to #717 
Not Tested
---

Add temporary string utils

---

tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointOverrideTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointWithSecurityTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointsByReferenceTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/security/CookieAuthTestCase.java
tests/src/test/resources/openAPIs/endpoints/endpoint_override.yaml
tests/src/test/resources/openAPIs/endpoints/endpoint_security.yaml
tests/src/test/resources/openAPIs/endpoints/endpoints_by_reference.yaml
tests/src/test/resources/testng.xml

Add integration tests for endpoints provided by reference, endpoint override, and endpoints with backend security functionalities.
Fixes #625 
MacOS mojave
Windows 10
---

Add integration tests for endpoints

---

components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

Removing the extra closing bracket.
<TierConfiguration?>reflect:getResourceAnnotations(s, resourceFunction, RESOURCE_TIER_ANN_NAME, GATEWAY_ANN_PACKAGE)

remove unwanted symbol

---

components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal

Fix issues in authn filer and subscription filter.
Fixes #717 
Not Tested
---

Fixe #717 - migrate subscription filter and authn filter

---

components/micro-gateway-core/src/main/ballerina/src/gateway/cookie.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/executiontime_util.bal

Fix compilation issues in executiontime_util.bal and cookie.bal
---

Fix compilation issues

---

components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/api_gateway_endpoint.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_endpoint.bal

Fixes for endpoint ballerina files.
---

fixes for endpoint bals

---

components/micro-gateway-core/src/main/ballerina/src/gateway/annotation.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/data_writer.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/lang_utils.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/token_revocation_etcd_util.bal

- Add replaceFirst string util method
- Fixes few compilation issues
Related to #717 
MacOS
---

More jballerina fixes

---

components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_security_constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/etcd_token_revocation_endpoint.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

Fixes for compilation failures.

fixes for compilation failures

---

components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/analytics_dtos.bal

adding fixes for ExecutionTimeDTO
---

adding fixes for ExecutionTimeDTO

---

components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/file_rotating_timer.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/validation_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/responsetime_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/services/token_revocation_event_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/upload_files_timer.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/etcd_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/token_revocation_etcd_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/validation_util.bal

Commented out .bal files to continue the flow and test runtime issues. We will fix the code immediately.
---

WIP: comment out the code to continue

---

components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/subscription_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

Fixes the subscription bal and some other util bals
Fixes #717 
Not Tested
---

Fix for #717 - jBallerina migration

---

components/micro-gateway-cli/src/main/resources/templates/httpEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/httpEndpointReInit.mustache
components/micro-gateway-cli/src/main/resources/templates/httpResourceEndpoint.mustache
components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-cli/src/main/resources/templates/service.mustache
distribution/resources/tokenServices/authorize_endpoint.bal
distribution/resources/tokenServices/revoke_endpoint.bal
distribution/resources/tokenServices/token_endpoint.bal
distribution/resources/tokenServices/user_info_endpoint.bal

Migrate the service.mustache and the listener.mustache
Fixes #717 
Not Tested
---

Initial migration of templates

---

components/micro-gateway-cli/pom.xml
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/HelpCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesConfigMapConfigItem.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesSecretItem.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/MutualSSL.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointDTO.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/mgwcodegen/MgwEndpointListDTO.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/oauth/DCRRequest.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/oauth/OAuthTokenRequest.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/APIDetailedDTO.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
pom.xml

We've used wrong spotbugs annotations earlier. This PR will correct it.
Related to #642
MacOS
---

Update spotbugs configs

---

components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/data_writer.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/api_gateway_endpoint.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/usagedata_uploader.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
distribution/resources/conf/micro-gw.conf
distribution/resources/tokenServices/authorize_endpoint.bal
distribution/resources/tokenServices/revoke_endpoint.bal
distribution/resources/tokenServices/token_endpoint.bal
distribution/resources/tokenServices/user_info_endpoint.bal
docker/conf/micro-gw.conf

With this PR basic jwt flow will work with https endpoint.
Fixes #717 
Not Tested
---

Migration of templates to work with jwt flow

---

components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal

Fixes for compilation issues in local throttling.
Not Tested
---

Fixes for compilation issues in local throttling

---

components/micro-gateway-cli/src/main/resources/templates/endpointReinit.mustache
components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-cli/src/main/resources/templates/main.mustache
components/micro-gateway-cli/src/main/resources/templates/noProdAvailableError.mustache
components/micro-gateway-cli/src/main/resources/templates/noSandAvailableError.mustache
components/micro-gateway-cli/src/main/resources/templates/policy.mustache
components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-cli/src/main/resources/templates/useAPIProdEp.mustache
components/micro-gateway-cli/src/main/resources/templates/useApiSandEp.mustache
components/micro-gateway-cli/src/main/resources/templates/useResourceProdEp.mustache
components/micro-gateway-cli/src/main/resources/templates/useResourceSandEp.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
distribution/resources/filters/extension_filter.bal
distribution/resources/filters/token_revocation_extension.bal
distribution/resources/tokenServices/authorize_endpoint.bal
distribution/resources/tokenServices/revoke_endpoint.bal
distribution/resources/tokenServices/token_endpoint.bal
distribution/resources/tokenServices/user_info_endpoint.bal

Migrate the templates to work with jBallerina 1.0.0-alpha3
Fixes #717 
Not Tested
---

Migrate templates to alpha3

---

pom.xml

Version property set in sportbugs plugin configuring was incorrect. This PR will correct it.
Related to #642 
Not Tested
---

Change spotbugs version property

---

components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/data_writer.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/analytics_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/file_rotating_timer.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/responsetime_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/upload_files_timer.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/etcd_util.bal
distribution/resources/conf/micro-gw.conf

Uncommented the analytics related filter and .bal files with fixes for ballerina alpha3
---

Fixes for the compilation issues in analytics 

---

components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-cli/src/main/resources/templates/policy.mustache
components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/emitOnStateChange.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/time_batch.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal

This rewrites the emitOnStateChange and TimeBatch siddhi extensions in ballerina, which was previously written in java.
Fixes #717 
Not Tested
---

Re write java siddhi extension in ballerina

---

.github/ISSUE_TEMPLATE/issue_template.md

Update 'BUG' issue template

---

components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-cli/src/main/resources/templates/main.mustache
components/micro-gateway-cli/src/main/resources/templates/policy.mustache
components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_security_constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/file_rotating_timer.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/time_batch.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

- Re enables throttle filter. Local throttling will work with jBallerina.
- Add new handler for jwt self contained tokens
Fixes #717 
Not Tested
---

Re enable throttle filter

---

components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/executiontime_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/file_rotating_timer.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/responsetime_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/emitOnStateChange.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/subscription_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
distribution/resources/filters/extension_filter.bal

Migrate to jBal 1.0.0-beta version
Fixes #717 
Not Tested
---

Migrate to jabl 1.0.0-beta

---

components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/executiontime_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/file_rotating_timer.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/responsetime_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/emitOnStateChange.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/subscription_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
distribution/resources/filters/extension_filter.bal

Reverts wso2/product-microgateway#777
Revert this change until the b7a beta get released.

Revert "Migrate to jabl 1.0.0-beta"

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/ToolkitLibExtractionUtils.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-cli/src/main/resources/templates/useAPIProdEp.mustache
components/micro-gateway-cli/src/main/resources/templates/useApiSandEp.mustache
components/micro-gateway-cli/src/main/resources/templates/useResourceProdEp.mustache
components/micro-gateway-cli/src/main/resources/templates/useResourceSandEp.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/throttle_endpoint.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/executiontime_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/file_rotating_timer.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/subscription_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/responsetime_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/throttler/emitOnStateChange.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/subscription_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
distribution/resources/filters/extension_filter.bal
pom.xml

Fix the issues in templates when using b7a 1.0.0-alpha3
Fixes #717 
Not Tested
---

Fix template issues

---

.github/workflows/maven.yml

Configuring a sample github action for tested purpose
Doesn't fix or relate to any PR. Testing a github feature
Not Tested
---

Add sample github action

---

.github/workflows/maven.yml

Add new configuration for windows build
No issue. Testing Github Actions
Not Tested
---

Update maven build action

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache

APIs with SOAP endpoints were not working due to few issues. This PR fixes those issues.
Fixes #716 
Fixes #748 
MacOS
Runtime 3.0.1
Tested for REST APIs with root(`/`) resource .
Tested for SOAP APIs
---

Fix issues with SOAP endpoints

---

distribution/resources/bin/micro-gw
distribution/resources/bin/micro-gw.bat

Build target details will be shown below the build status message. Also a build failure message is included.
Fixes #687 
MacOS
---

Update build command output

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache

`replace` will replace all occurrences of `{{basepath}}` from the request path. Which will cause issues if resource path also contain the `{{basepath}}` in it.
Fixes #749 
MacOS
---

Replace only basepath

---

components/micro-gateway-core/src/main/ballerina/gateway/filters/throttle_filter.bal

Fix the issue in resource level throttling when used with distributed throttling
Fixes #806
Not Tested
---

Fix #806 : Resource level global throttling issue

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/analytics_util.bal

Error in publishing analytics data will affect the request flow. This PR fixes that issue.
Fixes #808 
Not Tested
---

Fix #808: Analytics filter improvements

---

components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesHpa.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesIngress.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesJob.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesSecret.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesService.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttp.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttps.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceToken.mustache
components/micro-gateway-cli/src/main/resources/templates/secureKubernetesIngress.mustache

Default configuration model provided for k8s Secrets was incorrect. Secret configs should be given as a table.
Also label and annotation configs contain quotes which should be escaped before building the source file.
Fixes #734 
MacOS
---

Fix k8s labels, secrets and annotations

---

components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesHpa.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesIngress.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesJob.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesSecret.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesService.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttp.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceHttps.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesServiceToken.mustache
components/micro-gateway-cli/src/main/resources/templates/secureKubernetesIngress.mustache

- Default configuration model provided for k8s Secrets was incorrect. Secret configs should be given as a table.
- Also label and annotation configs contain quotes which should be escaped before building the source file.
Fixes #734 
MacOS
---

Fix issues in k8s configs

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java

Show a `git status` like output giving tips on what to do next. 
Message was not added to these commands,
- build - no next action within toolkit's scope
- reset - next action can be anything. Its a simple config reset
Fixes #686 
MacOs
---

Add next step tips to CLI Commands

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/ImportCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java

Show a git status like output giving tips on what to do next.
Tips were not added to these commands,
- build - no next action within micro-gw
- reset - next action can be anything. Its a simple config reset
Fixes #686 
MacOS
---

Add next step tips to toolkit commands

---

distribution/pom.xml
distribution/src/main/assembly/bin.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml

Download and add latest in-place tool to distribution. For platform specific distributions, the appropriate in-place executable is added.

Download and add latest in-place tool

---

components/micro-gateway-core/src/main/ballerina/gateway/basicAuth.bal
components/micro-gateway-core/src/main/ballerina/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/gateway/dtos/gateway_dtos.bal
distribution/resources/definitions/policies.yaml
tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
tests/src/test/resources/policies.yaml

Add a new default policy for subscription level.
Fixes #832
Not Tested
---

Introduce default subscription policy

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/GatewayCmdUtils.java
distribution/resources/bin/gateway.bat
distribution/resources/bin/micro-gw
distribution/resources/bin/micro-gw.bat

- Fix some of the issues found in executables. 
- Specially this PR will fix some of the differences in `micro-gw` *nix and windows executables.
Fixes #428 
MacOS
Windows server 2012 R2
---

Fix issues in executables

---

components/micro-gateway-cli/pom.xml
components/micro-gateway-core/pom.xml
components/micro-gateway-tools/pom.xml
components/pom.xml
distribution/pom.xml
distribution/src/main/assembly/filter.properties
pom.xml
tests/pom.xml

Next runtime release is going to be 3.1.0 as per the discussions so far. Updating the versions in the pom files to avoid confusions with 3.0.x branch build artifacts.
Preparing for next release
MacOS
---

Update development version

---

.github/ISSUE_TEMPLATE/documentation_template.md
.github/ISSUE_TEMPLATE/feature_template.md
.github/ISSUE_TEMPLATE/issue_template.md

Add new template for reporting doc issues
Fixes #633 
Not Tested
---

Add new issue templates

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/config_basic_auth_provider.bal
distribution/resources/definitions/policies.yaml
tests/src/test/resources/policies.yaml

Front port fixes from 3.0.x branch to the issue #827 , #806 , #832 
Fixes #827, #806, #832
Not Tested
---

Front port fixes from 3.0.x to jballerina branch

---

docker/Dockerfile

Fix issue in Micro-GW Docker Base Image
Fixes #863
MacOS catalina
---

Fix dockerfile

---

components/micro-gateway-cli/pom.xml
components/micro-gateway-core/pom.xml
components/micro-gateway-tools/pom.xml
components/pom.xml
distribution/pom.xml
pom.xml
tests/pom.xml

Change the pom version to 3.0.3-SNAPSHOT in order to perform 3.0.3 release
This is done to revert the version upgrade by automated release process
Not Tested
---

Rollback to 3.0.3-SNAPSHOT

---

components/micro-gateway-cli/src/main/resources/policies/throttle_policy_initializer.bal
components/micro-gateway-cli/src/main/resources/templates/jwtRevocation.mustache
components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
components/micro-gateway-core/assembly/jms_zip.xml
components/micro-gateway-core/pom.xml
components/micro-gateway-core/src/main/ballerina/Ballerina.toml
components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/services/token_revocation_event_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
distribution/pom.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
pom.xml
tests/src/test/java/org/wso2/micro/gateway/tests/jwtRevocation/JWTRevocationSupportTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/prepare/PreRequisites.java
tests/src/test/resources/testng.xml

Jballerina upgrade Distributed throttling and JWT revocation
MacOS
---

Fixes for Distributed throttling and JWT revocation

---

components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
components/micro-gateway-core/src/main/ballerina/gateway/annotation.bal
components/micro-gateway-core/src/main/ballerina/gateway/utils/utils.bal

#898 was merged with some remaining review comments in it. This PR will fix those issues.
#896 
MacOS
APIM 3.0.0
---

Fix comments in PR #898

---

components/micro-gateway-cli/src/main/resources/default-deployment-config.toml

Sample values for Label configuration in deployment toml had invalid format. This PR will correct it.
Fixes #838 
Not Tested
---

Fix invalid config samples

---

components/micro-gateway-cli/pom.xml
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/InitCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/TokenManagementConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/oauth/OAuthServiceImpl.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
components/micro-gateway-cli/src/main/resources/cli-help/cli-build.help
components/micro-gateway-cli/src/main/resources/cli-help/cli-init.help
pom.xml

This introduces the following mgw toolkit commands:
init command : 
-a/ --api-definition to set the api definition 
(options: --headers, --values, -k/--insecure )
build command : 
--docker to prompt for basic docker configurations (options: --docker-image, --docker-base-image )
Fixes #866, #858
MacOS Catalina
---

Introduce new toolkit command options

---

components/micro-gateway-core/src/main/ballerina/gateway/listeners/api_gateway_secure_listener.bal

Fixing formatting issue mentioned in [comment](https://github.com/wso2/product-microgateway/pull/345#discussion_r297019894)
Fixes issue mentioned in #345 
Tested
---

Fixing formatting issue

---

.travis.yml

Add travis build configuration for Pull requests
#917 
Not Tested
---

Add travis build configuration

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/BasicAuth.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/Config.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache

Provide API Level auth providers as an Array to the services.mustache
Fixes #915
catalina 
java version "1.8.0_201"
---

API Level auth providers as an Array

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java
components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
components/micro-gateway-cli/src/main/resources/templates/httpEndpointReInit.mustache
components/micro-gateway-cli/src/main/resources/templates/service.mustache

Fixes following issues.
1. Address type endpoints defined in API Manager is not support by MGW when such API is imported.
1. Appending `"/"` to SOAP request URLs break the request as SOAP services doesn't expect the trailing `"/"`
1. Sample values of `deployment-config.toml`'s k8s label configuration is invalid
1. ETCD endpoint is not properly reinitialized after updating the endpoint in etcd server.
Fixes #716 
Fixes #748 
Fixes #838
Fixes #923
MacOSx
etcd v3.3.13
---

Port some fixes from 3.0.x

---

components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal

Fixes the issue of cache configs initialisation with default values even we provide values with the configuration.
Fixes #954 
Not Tested
---

Fix #954 - Fix cache initialisation issue

---

distribution/resources/conf/micro-gw-default.conf
distribution/resources/conf/micro-gw.conf

Documenting default configs
#947
Not Tested
---

Default configs documentation

---

components/micro-gateway-core/pom.xml
components/micro-gateway-core/scripts/ballerina-build.bat

Fix an issue in windows build
Possible fix for release build failure in jenkins
Fix for a build failure
Not Tested
---

Fix build issues

---

components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
pom.xml

- Add cache layer for introspect endpoint
- Update ballerina version for 1.1.1
Fixes #919 
Not Tested
---

Fix #919 - Cache for introspect endpoints

---

components/micro-gateway-core/pom.xml
components/micro-gateway-core/src/main/ballerina/Ballerina.toml
distribution/pom.xml
distribution/src/main/assembly/bin.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime_linux.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime_macos.xml
distribution/src/main/assembly/gw_runtimes/gw_runtime_windows.xml
pom.xml
tests/pom.xml

-  Make all maven URLs https
- Prepare core module for 3.1.0-m2 dev cycle
- Fix some maven build warnings 
Fixes #960
MacOS Catalina, jdk8
---

Improvements to maven build

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
distribution/resources/bin/gateway.bat
distribution/resources/bin/micro-gw
distribution/resources/bin/micro-gw.bat

- Fix windows batch scripts to work with jballerina
- Add same build output improvements included in 3.0.x to master
Fixes #908 #428 
WIndows server 2016
---

Make windows executable work with jballerina

---

README.md
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/APIKey.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/ApplicationSecurity.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/TransportSecurity.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ext/ExtendedAPI.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-core/src/main/ballerina/Ballerina.toml

Add x-wso2-transport extension support
Change extension name x-wso2-api-security to x-wso2-application-security 
Fixes https://github.com/wso2/product-microgateway/issues/969,
https://github.com/wso2/product-microgateway/issues/964
Related to https://github.com/wso2/carbon-apimgt/pull/8153 
catalina
---

Application and Transport security

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/KubernetesDeployment.java
components/micro-gateway-cli/src/main/resources/default-deployment-config.toml
components/micro-gateway-cli/src/main/resources/templates/kubernetesConfigMap.mustache
components/micro-gateway-cli/src/main/resources/templates/kubernetesDeployment.mustache
components/micro-gateway-cli/src/main/resources/templates/listeners.mustache

- Supports pulling from private docker registries
- Fixes issues in k8s artifacts generation
Fixes #976 #774 
Not Tested
---

Fix #976 #774 - K8s issues and pull from private registries

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/native/throttle.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleConfigHolder.java
components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleDataReceiver.java
distribution/resources/conf/default-micro-gw.conf.template

Improve performance in throttle and pre authentication filter
Fixes #982 
Not Tested
---

Fix #982 - Improve performance in throttle and pre auth filter

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/TransportSecurity.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/rest/ext/ExtendedAPI.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/api_key_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

Add mutual SSL for API Level
Add support for optional application security 
Fixes #988, #964
Not Tested
---

Mutual SSL authentication for API

---

README.md
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
distribution/resources/cli-conf/toolkit-config.toml
tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
tests/src/test/resources/confs/default-cli-test-config.toml

Related to #https://github.com/wso2/product-microgateway/issues/995
Not Tested
---

Fix dcr version

---

components/micro-gateway-cli/src/main/resources/templates/listeners.mustache

Fixes for git issue #997 
Fixes #997 
Not Tested
---

Fixes the openAPIJsonConstants.json issue while starting the micro-gw

---

README.md

Update the README file .
Fixes #
Not Tested
---

Update QSG on readme file

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache

Correct missing grpc logic
#901 
Not Tested
---

Correct missing grpc logic

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/GeneratorConstants.java
components/micro-gateway-cli/src/main/resources/templates/healthCheck.mustache
components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal

This will add an /health endpoint to mgw.
Fixes #690
Not Tested
---

Fix #690 - Add health check endpoint

---

distribution/resources/bin/gateway
distribution/resources/bin/micro-gw
distribution/src/main/assembly/macos_bin.xml
docker/Dockerfile

- Resolves the issue of not having the wso2_options proto file inside macos toolkit dist.
- jre-alpine base image is not suitable for the microgateway as the gateway crashed during the startup when the 
Fixes #1011 
MacOS Mojave
---

Change the dockerfile base image

---

README.md
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/resources/cli-help/cli-build.help

Remove --docker option
Fixes #https://github.com/wso2/product-microgateway/issues/1015
Not Tested
---

Make --docker build command optional for Docker 

---

components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_security_constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
tests/src/test/java/org/wso2/micro/gateway/tests/apikey/APIKeyTestCase.java
tests/src/test/resources/confs/api-key.conf

Fixes #https://github.com/wso2/product-microgateway/issues/1013
Fixes API Key test.
Remove unnecessary debug log in analytics filter.
Fix Mutual SSL check in authorization filter to support AND combination in filters.
Not Tested
---

Fixes mutual ssl and api key test

---

components/micro-gateway-core/src/main/ballerina/Ballerina.toml
distribution/resources/conf/Ballerina.toml
pom.xml

Upgrade ballerina 1.1.1 to 1.1.2
#867
Not Tested
---

upgrade ballerina 1.1.1 to 1.1.2

---

components/micro-gateway-cli/src/main/resources/policies/throttle_policy_initializer.bal
components/micro-gateway-cli/src/main/resources/templates/policy_init.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal

Add default key type in jwt handler.
Fix formatting issues.
Fixes #https://github.com/wso2/product-microgateway/issues/1030
Fix review comments in https://github.com/wso2/product-microgateway/pull/1028 
catalina
---

Fix default key type in jwt handler

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

Fixes #https://github.com/wso2/product-microgateway/issues/1041
Not Tested
---

Fix api level security

---

components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/key_validation_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

Fixes https://github.com/wso2/product-microgateway/issues/991
Not Tested
---

Send backend jwt header if jwt has backendJwt claim

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/interceptors/InterceptorInvoker.java
components/micro-gateway-interceptor/pom.xml
components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Caller.java
components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Constants.java
components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Entity.java
components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/InterceptorUtils.java
components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/MGWBlockingCallBack.java
components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Request.java
components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Response.java
components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Utils.java
distribution/pom.xml
distribution/resources/conf/Ballerina.toml
pom.xml
tests/pom.xml
tests/src/main/java/org/wso2/micro/gateway/tests/interceptor/TestInterceptor.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/CLIExecutor.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
tests/src/test/java/org/wso2/micro/gateway/tests/context/Constants.java
tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/InterceptorTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/JavaInterceptorTestCase.java
tests/src/test/resources/openAPIs/interceptor/interceptor.yaml
tests/src/test/resources/testng.xml

This PR add payload getter and setter methods to the request and response objects.
Fixes #992 
Not Tested
---

Java interceptor feature- provide payload modification

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-cli/src/main/resources/templates/service.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/annotation.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/api_throttle_out_constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/native/throttle.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/DataProcessAgent.java
components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleCounter.java
components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleData.java
components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/throttle/ThrottleDataReceiver.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java
tests/src/test/java/org/wso2/micro/gateway/tests/throttling/OpenApiThrottlingTestCase.java

This PR will apply the API level throttle policy instead of applying it to per resource basis.
If API contains multiple resources all the resources will share the API level throttle limit.
Fixes #1019 
Not Tested
---

Fix #1019 - Throttling consistant with APIM

---

components/micro-gateway-cli/src/main/resources/templates/jwtRevocation.mustache
components/micro-gateway-core/pom.xml
components/micro-gateway-core/scripts/ballerina-build.sh
components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/services/token_revocation_event_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/token_revocation_etcd_util.bal

- Fix etcd jwt revoke
- Improve jms based rovocation
- Download ballerina from b7a dist during core module's mvn build
#1060
MacOS
---

Improve jwt revocation feature

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/config/ApplicationSecurity.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaService.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-cli/src/main/resources/templates/mutualSSL.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

Add more debug logs
Fix issues in combined auth schemes
Fixes #1074
Not Tested
---

Fix issues in combined auth schemes

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java

Fix build failure in QSG build step.
Fixes #1086 
MacOS
---

Fix issue during QSG

---

docker/Dockerfile

Update the docker file with beta version.
Fixes #
Not Tested
---

Update the docker file for beta release

---

README.md

Update the README to work with the beta docker image
Fixes #
Not Tested
---

Update the README to work with new docker image

---

components/micro-gateway-core/src/main/ballerina/Ballerina.toml
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/api_key_utils.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
distribution/resources/conf/Ballerina.toml
distribution/resources/conf/default-micro-gw.conf.template
distribution/resources/conf/micro-gw.conf
tests/src/test/resources/confs/api-key.conf

Removing aud claim from api key issuer and validator.
Change api key apis configuration format to below;
```
[[apikey.issuer.api]]
name="name"
versions="1.0.0, v2"
[[apikey.issuer.api]]
name="name2"
versions="1.0.0"
```
Fixes #1105
Fixes #1104 
Not Tested
---

change api key config

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/OpenAPIConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

New open API extension is introduced to template the base path of the API. This is explained in the issue #1113 
Fixes #1113 
Not Tested
---

Fix #1113 - Template the API base path with version

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/model/template/service/BallerinaOperation.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java

Improve error logs on extensions

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/observability_constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/filter_wrappers/analytics_request_filter_wrapper.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/filter_wrappers/validation_filter_wrapper.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/observability_util.bal
distribution/resources/bin/gateway
distribution/resources/bin/gateway.bat

Fixes the following issues
1. An exception message is sent to the client when authentication failure happens during the invocation. 
2. Interceptor function is not identified if there is no space between the function name and the opening parenthesis.
3. Apply ballerina metrics for the validation filter.
Fixes #1119
Fixes #1118 
Fixes #1063
Not Tested
---

Bug fixes: Observability and Interceptor related issues.

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/CliConstants.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java

Save the openAPI mappings created for the gRPC services for debugging purposes.
Fixes #1126 
MacOS Mojave
---

Save the OpenAPI mapping created for the gRPC service

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/Main.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/protobuf/ProtocCommandBuilder.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CmdUtils.java
distribution/resources/bin/gateway.bat
distribution/resources/bin/micro-gw
distribution/resources/bin/micro-gw.bat

There were few usability issues and incompatibilities in the windows env. This PR will fix those.
Fixes #1067  
Fixes #1107 
Fixes #428 
MacOS catalina
Windows server 2016
---

Fixes issues in windows scripts 

---

docker/alpine/Dockerfile
docker/ubuntu/Dockerfile

Update the docker files
Fixes #
Not Tested
---

Update the docker files

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/callhome/Callhome.java

This handles the errors when calling the call home functionality.
Fixes #
Not Tested
---

Handle error in call home function

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache
components/micro-gateway-core/pom.xml
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
components/micro-gateway-interceptor/pom.xml
distribution/pom.xml
pom.xml

This will remove the org.json dependency and add the org.json.wso2 orbit dependency instead
Fixes #
Not Tested
---

Remove org.json dependency

---

distribution/LICENSE-RUNTIME.txt
distribution/LICENSE-TOOLKIT.txt
release-notes.html

Update release note and License.txt for 3.1.0-RC1
Not Tested
---

Update release note and License.txt

---

tests/src/test/java/org/wso2/micro/gateway/tests/grpc/BasicGrpcTestCase.java
tests/src/test/resources/protobuf/mgwProto/basicProto.proto

Fixes the throttling test failures in GRPC test cases
Fixes #
Not Tested
---

Fix gRPC test case failures

---

distribution/pom.xml
docker/alpine/Dockerfile

- Fix docker motd for bash
- Fix version.txt
Task
Alpine
---

Fix docker motd for bash

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache

Fix response interceptor in template
Fixes #1212
Not Tested
---

Fix response interceptor

---

components/micro-gateway-tools/src/main/java/org/wso2/micro/gateway/tools/GetConfig.java

Allow to tracing alone without throw exception for matrics
https://github.com/wso2/product-microgateway/issues/1215
Tested in macOS
---

Bug Fix #1215 :Allow to tracing alone 

---

components/micro-gateway-cli/src/main/resources/templates/tokenServices.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

Fix / at the start and end of the token context given in the runtime configuration file
Fixes #1206
Catalina
---

Fix tokenContext "/"

---

README.md

From 310 onwards MGW changed how it accepts endpoint override parameters. This PR will update this info in the Readme.
Fixes #1188
Not Tested
---

Update EP override params

---

tests/src/test/java/org/wso2/micro/gateway/tests/common/MockBackEndServer.java
tests/src/test/java/org/wso2/micro/gateway/tests/endpoints/EndpointsByReferenceTestCase.java
tests/src/test/resources/openAPIs/endpoints/endpoint_security.yaml

Fix a test failure after #1250 
Failed test: https://wso2.org/jenkins/view/All%20Builds/job/products/job/product-microgateway/960/
```
2020-06-01 21:46:30 INFO  ServerLogReader:114 - There are 2 updates available for the product 'wso2am-micro-gw-toolkit-linux-3.1.0'.
2020-06-01 21:46:30 INFO  ServerLogReader:114 - ....................................................................................
2020-06-01 21:46:31 INFO  ServerLogReader:114 - Compiling source
2020-06-01 21:46:31 INFO  ServerLogReader:114 - 	wso2/EndpointReferenceProject:3.1.0
2020-06-01 21:46:48 INFO  ServerLogReader:114 - 
2020-06-01 21:46:48 INFO  ServerLogReader:114 - Creating balos
2020-06-01 21:46:48 INFO  ServerLogReader:114 - 	target/balo/EndpointReferenceProject-2019r3-java8-3.1.0.balo
2020-06-01 21:47:08 ERROR …
```

Fix a test failure

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
components/micro-gateway-cli/src/main/resources/templates/main.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/native/validator.bal
components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/Constants.java
components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/utils/CommonUtils.java
components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/validation/Validate.java
components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Utils.java
components/pom.xml
tests/pom.xml
tests/src/main/java/org/wso2/micro/gateway/tests/interceptor/OpenAPIReadInterceptor.java
tests/src/test/java/org/wso2/micro/gateway/tests/interceptor/JavaInterceptorTestCase.java
tests/src/test/resources/openAPIs/interceptor/interceptor.yaml

With this PR we have included public method in the micro gateway core module to get the open API definition. This method can be used from any native interop java classes or from microgateway interceptors.
```java
/**
* Provide a map of all open APIs exposed by the gateway.
*
* @return Returns open API definitions of all the APIs exposed via gateway as a {@link Map}.
*/
public static Map<String, String> getOpenAPIMap() {
return openAPIMap;
}
/**
* Provide open API definition as a json string for a particular API.
* @param apiName Name of the API.
* @param apiVersion Version of the API.
*
* @return Returns open API definition of the API as a json {@link String}.
*/
public static String getOpenAPI(String apiName, String apiVersion) {
String serviceName = getQualifiedServiceName(apiName, …
```

Fix #1217 - Provide a method to read open API definition

---

components/micro-gateway-cli/src/main/resources/templates/service.mustache
distribution/src/main/assembly/filter.properties
docker/alpine/Dockerfile
docker/ubuntu/Dockerfile
release-notes.html

Update docker files
update release notes.html
update filter.properties file
Fixes #
Not Tested
---

Prepare for alpha release

---

components/micro-gateway-cli/src/main/resources/policies/subscription_Gold.bal
components/micro-gateway-cli/src/main/resources/templates/jwtRevocation.mustache
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/api_data_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/key_mapping_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_data_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/subscription_data_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/gateway_pilot_endpoint.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/token_revocation_etcd_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

This PR includes data stores required to validation subscriptions using the pilot node. JWT validation is also partially implemented.
#1258
Not Tested
---

Add datastores for new subscription validation

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/CodegenUtils.java
components/micro-gateway-core/src/main/ballerina/Ballerina.toml
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/api_data_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/key_mapping_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_data_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/subscription_data_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/endpoints/gateway_pilot_endpoint.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/services/gateway_jms_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/services/throttle_event_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
distribution/resources/conf/default-micro-gw.conf.template
distribution/resources/conf/micro-gw.conf

This PR provides capability to retrieve subscription and application retrieval via jms messages real time. 
Fixes #1258 
Not Tested
---

Fix #1258 - Initial support for jms subcription data retrieval

---

components/micro-gateway-core/src/main/ballerina/src/gateway/apim/api_data_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/key_mapping_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_data_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/subscription_data_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/services/gateway_jms_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
distribution/resources/conf/default-micro-gw.conf.template

Remove tenant wise data storage.
Add jwks URL support. This support will come once we upgrade to ballerina version 1.2.5
Fixes #1258 
Not Tested
---

Fix #1258 - Remove tenentwise data and add jwks endpoint

---

components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal

Add new subscription states BLOCKED, ON_HOLD, and etc support
Fixes #1258 
Not Tested
---

Fix #1258 - add new subscription states

---

components/micro-gateway-core/assembly/balo.xml
distribution/resources/bin/micro-gw
distribution/resources/bin/micro-gw.bat

Enables to build microgateway projects without an internet connection using the toolkit.
Fixes #1316
Not Tested
---

Fix #1316 - Build microgateway projects without internet connection using toolkit

---

components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/api_key_utils.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
tests/src/test/resources/confs/default-test-config.conf

There can be inconsistencies when validating subscriptions when multiple jwt issuers are configured.
Fixes #1321 
Not Tested
---

Fix #1321 - Multiple jwt issuer subscription validation issue

---

components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/executiontime_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/faults_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/analytics/responsetime_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/micro_gw_conf_defaults.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/analytics_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/throttle_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/analytics_request_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/token_introspection_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/analytics_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal
distribution/resources/conf/default-micro-gw.conf.template

This PR adds support for using multiple analytics versions. (3.0.0, 3.1.0, 3.2.0)
Fixes https://github.com/wso2/product-microgateway/issues/1325
Not Tested
---

Support analytics versioning.

---

components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/token_introspection_handler.bal
tests/src/test/java/org/wso2/micro/gateway/tests/security/AuthenticationFailureTestCase.java
tests/src/test/java/org/wso2/micro/gateway/tests/util/TestConstant.java
tests/src/test/resources/introspection-response.json

Remove the additional check for the subscription validation
Fixes https://github.com/wso2/product-microgateway/issues/1332
Not Tested
---

Remove unnecessary subscription allowed check.

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/constants/RESTServiceConstants.java
components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_data_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/subscription_data_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/services/token_revocation_event_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
distribution/resources/cli-conf/toolkit-config.toml
distribution/resources/conf/default-micro-gw.conf.template
distribution/resources/conf/micro-gw.conf
tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java

Fix subscription validation issues
Update toolkit REST and DCR versions to work with APIM 3.2.0 by default
Fixes #1333 
Not Tested
---

Fix #1333 - Improvements for subscription validation logic

---

components/micro-gateway-cli/src/main/resources/templates/listeners.mustache
components/micro-gateway-core/src/main/ballerina/Ballerina.toml
distribution/resources/version.txt

This PR fixes issues when defining custom filters. 
Fixes #1294 
Not Tested
---

Fix #1294 - Array out of bound when custom filters are used

---

components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/mutualSSL_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

This PR will add the www-Authenticate header in the Error response when the authorization fails.
Fixes #1306
Not Tested
---

Add www-Authenticate header in the Error response

---

components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

Add method comments
Fixes  https://github.com/wso2/product-microgateway/issues/1336
Not Tested
---

Add method comments

---

components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
distribution/resources/conf/default-micro-gw.conf.template

Fix issue in application level throttling when used without a subcription
Fixes #1338 
Not Tested
---

Fix #1338 - Application level throttling issue

---

distribution/src/main/assembly/filter.properties
docker/alpine/Dockerfile
docker/ubuntu/Dockerfile

Prepare for 3.2.0-beta release

---

components/micro-gateway-cli/src/main/resources/cli-help/cli-import.help
components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/jwt_auth_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/jwt_util.bal
components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/AbstractMGWJWTGenerator.java
distribution/resources/conf/default-micro-gw.conf.template

remove unsupported import commands in help command.
fix claim mapping issue when aud is not provided. 
Remove debug log line with byte value.
Fixes https://github.com/wso2/product-microgateway/issues/1342
catalina
---

Fix custom claim and issues

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/codegen/CodeGenerator.java
tests/pom.xml

* Remove duplicate dependency
Fixes https://github.com/wso2/product-microgateway/issues/1292
Not Tested
---

Revert Code Generator Changes.

---

components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_dtos.bal
tests/src/test/resources/application-get-response.json

As $subject, this will fix the object type mismatch error of the APIM(3.2.0) application data response and microgateway application data store data object.
Fixes #1372
Not Tested
---

Fix apim application data response object type mismatch error

---

components/micro-gateway-core/src/main/ballerina/src/gateway/utils/throttle_util.bal

- If evaluated condition attribute is missing in the request, we shouldn't consider it as a throttled request.
#1343 
MacOs
---

Improve condition based throttling

---

components/micro-gateway-core/src/main/ballerina/src/gateway/apim/application_data_store.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/apim/pilot_utils.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/backend_jwt_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/dtos/gateway_dtos.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/token_introspection_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/jwt_generator/claim_retriever.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/jwt_generator/jwt_gen_util.bal
components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/MGWJWTGeneratorImpl.java

Fixes the backend JWT generation related issues mentioned in #1375.
Fixes #1375 
Fixes #1377 
MacOS Mojave
---

Fix JWT generation related issues.

---

distribution/resources/conf/default-micro-gw.conf.template
distribution/resources/conf/micro-gw.conf

Change the [apim.eventhub] service_url to serviceUrl.
Fixes https://github.com/wso2/product-microgateway/issues/1378
Not Tested
---

Rename the service_url config to serviceUrl

---

components/micro-gateway-cli/src/main/resources/templates/ballerinaToml.mustache

Fixes test case failures in the master
Fixes #1386
Not Tested
---

Remove templating the mgwVersion in ballerinaToml.mustache.

---

samples/sample-jwt-generator/pom.xml
samples/sample-jwt-generator/src/main/java/sample/jwt/generator/SampleClaimRetriever.java

Add a sample implementation to claim retriever. (For documentation purposes)
Fixes #1196 
MacOS Mojave
---

add sample claim retriever implementation

---

filter-chain/envoy.yaml
java-filter-chain/.gitignore
java-filter-chain/pom.xml
java-filter-chain/src/main/java/org/wso2/mgw/filterchain/gRPC/server/AuthServer.java
java-filter-chain/src/main/java/org/wso2/mgw/filterchain/gRPC/server/ExtAuthService.java

As $subject, this will initialize the gRPC server for the envoy external auth filter.
Here [controlplane dependency](https://mvnrepository.com/artifact/io.envoyproxy.controlplane/api) is used to implement the server functionalities
Fixes #1412 
Not Tested
---

[envoy-gw] init java filter chain & implelment ext auth grpc server

---

java-filter-chain/dockerfile
java-filter-chain/pom.xml
java-filter-chain/src/main/java/org/wso2/mgw/filterchain/JWTValidator/JWTValidator.java
java-filter-chain/src/main/java/org/wso2/mgw/filterchain/gRPC/server/ExtAuthService.java

As $subject, this will integrate jwt + cache feature with java gRPC server
Fixes #1412
Not Tested
---

[envoy-gw] Intergrate jwt feature with gRPC server

---

developer-guide.md

Provide a developer guide to run the microgateway
n/A
Not Tested
---

Add a developer guide

---

enforcer/pom.xml
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTAuthenticator.java

Validate subscriptions using `subscribedAPIs` claim in the jwt. This is to support tokens issued by APIM versions before 320
Fixes #1447
Mac
---

Validate with subscribedAPIs

---

adapter/pom.xml
developer-guide.md
distribution/pom.xml
enforcer/pom.xml
pom.xml
remove-containers.sh
resources/docker-compose.yaml
router/pom.xml

Prepare for 4.0.0-m2 dev cycle

---

components/micro-gateway-core/src/main/ballerina/src/gateway/api_gateway_cache.bal

Add getters for the following mgw caches 
-gatewayTokenCache
-gatewayKeyValidationCache
-invalidTokenCache
-jwtGeneratorExpTimeCache
Fixes #1499 
Not Tested
---

Add getters for caches

---

samples/petstore_v3.yaml

Need to modify the QSG with proper pet-store v3 endpoints
Fixes # Task
Not Tested
---

Add petstore v3 yaml for QSG

---

adapter/build.sh
adapter/go.mod
adapter/go.sum

Fix jenkins build failure golint command not found. 
Fixes #
Tested in Mac and Ubuntu
---

Fix jenkins golint command not found

---

enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/EventHubConfigurationDto.java

Fix issue in reading event hub config
Fixes #1545 
Not Tested
---

Fix #1545 - Evenhub config reading error

---

resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml

Fixes https://github.com/wso2/product-microgateway/issues/1544
[k8s artifacts] Update changes for Adapter config.toml
---

[k8s artifacts] Update changes for Adapter config.toml

---

resources/k8s-artifacts/mg-adapter/deployment.yaml
resources/k8s-artifacts/mg-enforcer/deployment.yaml
resources/k8s-artifacts/mg-router/deployment.yaml

Fix K8s Resources

---

adapter/pom.xml
developer-guide.md
distribution/pom.xml
enforcer/pom.xml
pom.xml
remove-containers.sh
resources/docker-compose.yaml
router/pom.xml
test/mock-backend-server/pom.xml
test/pom.xml
test/test-integration/pom.xml

Prepare for 4.0.0-m4 dev cycle

---

components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal

As $subject this will make the changes to apply custom throttling policies for unauthenticated api calls.
Fixes #1434 
Ubuntu 20.04
---

Modify implementtion to apply custom throttling policies for unauthenticated api calls

---

test/test-integration/src/test/java/org/wso2am/micro/gw/tests/security/CorsTestCase.java

fix the issue where containers are not shutting down after CORS testcase.
Fixes #
MacOS Mojave
---

fix the issue where containers are not shutting down after CORS testcase

---

adapter/pom.xml
distribution/pom.xml
enforcer/pom.xml
pom.xml
router/pom.xml
test/mock-backend-server/pom.xml
test/pom.xml
test/test-integration/pom.xml

Prepare for 4.0.0-m4 release.
Task
MacOS
---

[Do not merge]Prepare for 4.0.0-m4 release

---

adapter/pom.xml
developer-guide.md
distribution/pom.xml
enforcer/pom.xml
pom.xml
remove-containers.sh
resources/docker-compose.yaml
resources/k8s-artifacts/mg-adapter/deployment.yaml
resources/k8s-artifacts/mg-enforcer/deployment.yaml
resources/k8s-artifacts/mg-router/deployment.yaml
router/pom.xml
test/mock-backend-server/pom.xml
test/pom.xml
test/test-integration/pom.xml

Prepare for 4.0.0-m5 dev cycle

---

resources/docker-compose.yaml

Add Log rotation by default.
Task
Not Tested
---

Add log rotation

---

adapter/pkg/oasparser/envoyconf/routesWithClusters.go
adapter/pkg/xds/xds_server.go

too much info logging 
caused by adapter/pkg/xds/xds_server.go line no 429
Fixes #1586
Ubuntu 20.04
---

fixed-too much info logging

---

adapter/go.mod
adapter/go.sum
adapter/pkg/api/file_read_utils.go
adapter/pkg/api/restserver/config_restapi.go
adapter/pkg/messaging/notificationListener.go
adapter/pkg/mgw/mgw.go
adapter/pkg/synchronizer/apis_fetcher.go
adapter/pkg/xds/xds_server.go

Fixes: https://github.com/wso2/product-microgateway/issues/1594
Fixes #
- Integration tests added:  Pending because of APIM mocking
Not Tested
---

Publishing APIs through API Manager

---

adapter/pkg/subscription/subscription.go
adapter/pkg/xds/xds_server.go
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApiListDiscoveryClient.java
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationDiscoveryClient.java
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationKeyMappingDiscoveryClient.java
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/ApplicationPolicyDiscoveryClient.java
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/SubscriptionDiscoveryClient.java
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/discovery/SubscriptionPolicyDiscoveryClient.java
resources/conf/config.toml

- This PR removes the [enforcer.eventHub] configs from config.toml
- Additionally, adds more logs to track subscription handling from the control plane to enforcer
Fixes https://github.com/wso2/product-microgateway/issues/1602
Tested
OS - MacOS
JDK 11
---

Remove [enforcer.eventHub] configs from config.toml

---

adapter/config/mgwtypes.go
adapter/pkg/oasparser/model/mgwSwagger.go
adapter/pkg/svcdiscovery/watcher.go
adapter/pkg/xds/xds_server.go
resources/conf/config.toml

Add a config to start Consul service discovery to minimize API deployment time when the number of APIs are large
Fixes #1592 
Ubuntu 20.04
---

Add a config to start Consul service discovery

---

adapter/config/mgwtypes.go
adapter/pkg/mgw/mgw.go
adapter/pkg/subscription/subscription.go
adapter/pkg/synchronizer/apis_fetcher.go
adapter/pkg/synchronizer/synchronizer_dtos.go
resources/conf/config.toml

Fixes https://github.com/wso2/product-microgateway/issues/1601
Fixes https://github.com/wso2/product-microgateway/issues/1600
- Integration tests added: Pending
Not Tested
---

Refactor tlsEnabled config and avoid retrying for 4xx errors.

---

pom.xml

Fixes issues in the release build.
1. Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
2. Doclint issues
Catalina 
---

Fix issues in release build

---

pom.xml

Relates to #1610
Tested Catalina
---

fix javadoc issue

---

pom.xml

Fix version replacement using maven-antrun-plugin

---

tests/src/test/java/org/wso2/micro/gateway/tests/common/JMSPublisher.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/JMSPublisherConstants.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java

Fixes https://github.com/wso2/product-microgateway/pull/289#discussion_r556937361
Fixes https://github.com/wso2/product-microgateway/pull/289#discussion_r556937959

Fix reviewed comments

---

README.md
distribution/pom.xml
pom.xml
test/mock-backend-server/pom.xml

Push images to docker hub in release build
Avoid distribution zip uploading to nexus
Add build status badge
Fixes #
Tested
---

push to docker and skip zip upload to nexus

---

adapter/pkg/messaging/eventtypes.go
adapter/pkg/messaging/notificationListener.go
adapter/pkg/resourcetypes/dto.go
adapter/pkg/synchronizer/apis_fetcher.go

APIM endpoint has been changed to accept the environment in the base64 encoded format. This PR makes adapter compatible with that change.
This PR contains improvments related to the implementation in https://github.com/wso2/product-microgateway/issues/1594
Fixes https://github.com/wso2/product-microgateway/issues/1594
Not Tested
---

Encoding mgw labels to compatible with control plane.

---

components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal

This PR will introduce the feature of throttling api requests using custom throttling properties as key template
Fixes https://github.com/wso2/product-microgateway/issues/1455
Not Tested
---

Add changes to support custom throttling properties

---

resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml
resources/k8s-artifacts/mg-adapter/deployment.yaml
resources/k8s-artifacts/mg-enforcer/deployment.yaml
resources/k8s-artifacts/mg-router/deployment.yaml

$subject
```
$ apictl init petstore --oas https://petstore.swagger.io/v2/swagger.json
Initializing a new WSO2 API Manager project in /Users/renuka/git/product-microgateway/petstore
Project initialized
Open README file to learn more
$ apictl mg deploy --host https://localhost:30200 --file petstore  -u admin -p admin -k
Successfully imported API.
$ curl -X GET "https://localhost:30201/v2/pet/1" -H "accept: application/json" -H "Authorization:Bearer $TOKEN" -k
{"code":1,"type":"error","message":"Pet not found"}
$ k get po
NAME                          READY   STATUS    RESTARTS   AGE
mg-adapter-dfc54797f-v4gj4    1/1     Running   0          112s
mg-enforcer-f8f74d7f4-qhzx4   1/1     Running   0          111s
mg-router-7fb6d9d7cd-s7g98    1/1     Running   0          111s
```
Fixes #1642
- …

Update K8s configs for MG 4.0.0-m6

---

resources/conf/config.toml
resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml

$subject since this doesn't need to be enabled by default.
Fixes #1627 
Not Tested
---

Disable BE jwt generation by default

---

README.md
developer-guide.md
remove-containers.sh
resources/docker-compose.yaml

Prepare for 4.0.0-m6

---

components/micro-gateway-cli/src/main/resources/templates/useAPIProdEp.mustache
components/micro-gateway-cli/src/main/resources/templates/useApiSandEp.mustache

Fixes https://github.com/wso2/product-microgateway/issues/1485
Not Tested
---

Fixing API level sandbox and production endpoint confusion.

---

test/test-integration/src/test/java/org/wso2am/micro/gw/tests/jwtGenerator/JwtGeneratorTestCase.java
test/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/TestConstant.java
test/test-integration/src/test/resources/jwtGenerator/config.toml
test/test-integration/src/test/resources/testng.xml

JWT generator test needs the feature to be enabled. By default this is not enabled.
Fixes #1627
Mac
---

Fix a test failure in JWTGenerator

---

adapter/pom.xml
distribution/pom.xml
enforcer/pom.xml
pom.xml
remove-containers.sh
resources/docker-compose.yaml
router/pom.xml
test/mock-backend-server/pom.xml
test/pom.xml
test/test-integration/pom.xml

- Prepare repo for development after 4.0.0-m6
Task
Not Tested
---

Complete 4.0.0-m6 release

---

adapter/scripts/build.sh

Enable coverage for goland related code
Fixes # Task
Not Tested
---

Enable code coverage for golang unit tests

---

.github/workflows/coverage.yml

Upload test coverage reports to Codecov

Upload test coverage reports to Codecov

---

.github/workflows/coverage.yml

Install go

---

adapter/config/parser.go
enforcer/src/main/assembly/assembly.xml
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/Constants.java
resources/conf/config.toml
resources/docker-compose.yaml

Allow read string config values from env variables.
Fixes #1668 
- Integration tests added: Existing tests covered the scenarios
Not Tested
---

Fix #1668 - Resolve configs from environment variables

---

adapter/internal/api/apis_impl.go

$Subject
Fixes #
Not Tested
---

Accept api.json during deploy

---

README.md
adapter/pom.xml
enforcer/pom.xml
pom.xml
remove-containers.sh
resources/docker-compose.yaml
router/pom.xml
test/pom.xml

Changing the artifacts from SNAPSHOT to Release version.
Fixes #
Not Tested
---

Release preparation for M7

---

distribution/pom.xml
resources/apim/docker-compose.yaml
test/mock-backend-server/pom.xml
test/test-integration/pom.xml

Release preperation for M7

---

resources/k8s-artifacts/mg-adapter/config-toml-configmap.yaml

Adding missing configurations for k8s artifacts.
Fixes #
Not Tested
---

Adding configs for k8s artifacts.

---

adapter/pom.xml
distribution/pom.xml
enforcer/pom.xml
pom.xml
remove-containers.sh
resources/apim/docker-compose.yaml
resources/docker-compose.yaml
resources/k8s-artifacts/mg-adapter/deployment.yaml
resources/k8s-artifacts/mg-enforcer/deployment.yaml
resources/k8s-artifacts/mg-router/deployment.yaml
router/pom.xml
test/mock-backend-server/pom.xml
test/pom.xml
test/test-integration/pom.xml

Preparing for m8 development iteration.
Fixes #
Not Tested
---

M8 development iteration preparation.

---

enforcer/src/main/java/org/wso2/micro/gateway/enforcer/keymgt/KeyManagerHolder.java
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/validator/JWTValidator.java

This PR will fix the subscription validation issue in gateway
https://github.com/wso2/product-microgateway/issues/1706
Not Tested
---

Fixing subscription validation issue

---

enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/AuthServer.java

Fix the TokenServer initializing issue
Fixes related to https://github.com/wso2/product-microgateway/issues/1671
Not Tested
---

Fix TokenServer initializing issue

---

README.md
remove-containers.sh
resources/apim/docker-compose.yaml
resources/docker-compose.yaml
resources/k8s-artifacts/mg-adapter/deployment.yaml
resources/k8s-artifacts/mg-enforcer/deployment.yaml
resources/k8s-artifacts/mg-router/deployment.yaml

Release preparation for m8.

---

adapter/pom.xml
distribution/pom.xml
enforcer/pom.xml
pom.xml
router/pom.xml
test/mock-backend-server/pom.xml
test/pom.xml
test/test-integration/pom.xml

M8 release preperation.

---

pom.xml

Improving pom for the release.

---

remove-containers.sh
resources/apim/docker-compose.yaml
resources/docker-compose.yaml
resources/k8s-artifacts/mg-adapter/deployment.yaml
resources/k8s-artifacts/mg-enforcer/deployment.yaml
resources/k8s-artifacts/mg-router/deployment.yaml

M9 development preparation.

---

README.md
remove-containers.sh
resources/apim/docker-compose.yaml
resources/docker-compose.yaml
resources/k8s-artifacts/mg-adapter/deployment.yaml
resources/k8s-artifacts/mg-enforcer/deployment.yaml
resources/k8s-artifacts/mg-router/deployment.yaml

Release prep for m9

---

remove-containers.sh
resources/apim/docker-compose.yaml
resources/docker-compose.yaml
resources/k8s-artifacts/mg-adapter/deployment.yaml
resources/k8s-artifacts/mg-enforcer/deployment.yaml
resources/k8s-artifacts/mg-router/deployment.yaml

Development prep for next release.

---

components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/cmd/BuildCmd.java
components/micro-gateway-core/src/main/java/org/wso2/micro/gateway/core/callhome/Callhome.java

As $subject, this will reduce line spaces and document callhome methods
Not Tested
---

fix line space and document methods

---

components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/AbstractMGWJWTGenerator.java

This PR refactors AbstractMGWJWTGenerator in JWT generation process.

Refactor AbstractMGWJWTGenerator

---

components/micro-gateway-core/src/main/ballerina/src/gateway/constants/constants.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/jwt_generator/jwt_gen_util.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/native/jwtGenerator.bal
components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/AbstractMGWJWTGenerator.java
components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/MGWJWTGeneratorConstants.java
components/micro-gateway-jwt-generator/src/main/java/org/wso2/micro/gateway/jwt/generator/MGWJWTGeneratorImpl.java
samples/sample-jwt-generator/pom.xml
samples/sample-jwt-generator/src/main/java/sample/jwt/generator/SampleJWTGenerator.java
tests/src/main/java/org/wso2/micro/gateway/tests/jwtgenerator/TestJWTGenerator.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/JMSPublisher.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/JMSPublisherConstants.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/MockHttpServer.java
tests/src/test/java/org/wso2/micro/gateway/tests/common/ResponseConstants.java

This PR refactors JWT Generator code.

Refactor JWT Generator code

---

components/micro-gateway-core/src/main/ballerina/src/gateway/filters/authz_filter.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handler_providers/oauth2_key_validation_provider.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/api_key_handler.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/listeners/api_gateway_secure_listener.bal
components/micro-gateway-core/src/main/ballerina/src/gateway/utils/utils.bal

This PR will add correct scope details to the invocation context. 
Fixes https://github.com/wso2/product-microgateway/issues/1498
Not Tested
---

Fix scope details in the invocation context.

---

enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTAuthenticator.java
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/util/FilterUtils.java
pom.xml

This PR updated the carbon apimgt to the latest release version 9.0.70 and enforcer code changes as to be compatible with the updated carbon.apimgt version.
Fixes https://github.com/wso2/product-microgateway/issues/1743
Not Tested
---

Upgrading carbon.apimgt version to 9.0.70

---

enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/issuer/AbstractJWTIssuer.java

This PR fixes the issues in encoded test JWT
Fixes https://github.com/wso2/product-microgateway/issues/1765
Not Tested
---

Fix jwt encoding issue

---

integration/test-integration/pom.xml
integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/apim/APIMLifecycleBaseTest.java
integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/apim/APIMWithMgwBaseTest.java
integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/context/APIManagerWithMgwServerInstance.java
integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/context/MgwServerImpl.java
integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/context/MgwServerInstance.java
integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/mockbackend/MockBackendServer.java
integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/testCaseBefore/APIManagerInitializeTestCase.java
integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/testCases/subscription/SubscriptionValidationTestCase.java
integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/TestConstant.java
integration/test-integration/src/test/java/org/wso2am/micro/gw/tests/util/Utils.java
integration/test-integration/src/test/resources/apim/config.toml
integration/test-integration/src/test/resources/automation.xml
integration/test-integration/src/test/resources/testng.xml
resources/apim/docker-compose.yaml
resources/docker-compose.yaml

- Use API Manager as the Control Plane for Integration tests
- Add utility methods for Mgw test cases that use the APIM as the backend server
- Add Integration tests for Subscription validation
Fixes https://github.com/wso2/product-microgateway/issues/1755
Fixes https://github.com/wso2/product-microgateway/issues/1756
Not Tested
---

Add Integration tests for Subscription Validation

---

components/micro-gateway-core/src/main/ballerina/src/gateway/handlers/jwt_auth_handler.bal

As $subject this will fix the subscription validation issue when multiple jwt issuers are provided.
Fixes #1759 
MGW 3.2
---

Fix subscription validation when multiple issuers are provided

---

resources/conf/config.toml

This PR corrects the JWT issuer endpoint to testkey
Fixes https://github.com/wso2/product-microgateway/issues/1773
Not Tested
---

Modify config.toml for testkey endpoint

---

adapter/config/types.go
enforcer/pom.xml
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/dto/ThrottleConfigDto.java
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/constants/Constants.java
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/server/AuthServer.java
enforcer/src/main/java/org/wso2/micro/gateway/enforcer/throttle/ThrottleEventListener.java
pom.xml
resources/apim/docker-compose.yaml
resources/conf/config.toml
resources/docker-compose.yaml

Here we are reusing APIMs jms component to get all features included in APIM jms component. With this we expect to have jms reconnection retry, failover capabilities.
Fixes #1777
Mac, Docker
---

Advance jms connection support for Enforcer

---

enforcer/src/main/java/org/wso2/micro/gateway/enforcer/security/jwt/JWTAuthenticator.java
resources/conf/config.toml

This PR will remove the config from config.toml 
Related PR https://github.com/wso2/product-microgateway/pull/1785
Fixes #
Not Tested
---

Removing unwanted config

---

enforcer/src/main/java/org/wso2/micro/gateway/enforcer/config/ConfigHolder.java
resources/apim/docker-compose.yaml
resources/conf/config.toml

Fix issue of enforcer not properly resolving part string with environment variables.
Fixes #1790 
Not Tested
---

Fix #1790 - Enforcer env varaible resolving issue

---

integration/test-integration/src/test/resources/openAPIs/security_openAPI.yaml

This PR will remove the unwanted comment from yaml file
Related PR: https://github.com/wso2/product-microgateway/pull/1793
Fixes #
Not Tested
---

Removing unwanted comment

---

README.md
remove-containers.sh
resources/apim/docker-compose.yaml
resources/docker-compose.yaml

Release preparation for m10.
Fixes #
Not Tested
---

Release prep for m10.

---

resources/k8s-artifacts/mg-adapter/deployment.yaml
resources/k8s-artifacts/mg-deployment/deployment.yaml

Update k8s artifacts for m10

---

enforcer/pom.xml
integration/test-integration/pom.xml
pom.xml
resources/conf/log4j2.properties

Fix #1817 - Debug log printing issue

---

adapter/internal/oasparser/envoyconf/routes_with_clusters.go
integration/mock-backend-server/src/main/java/org.wso2am.micro.gw.mockbackend/MockBackEndServer.java

This PR will fix the issue in test case
Related PR: https://github.com/wso2/product-microgateway/pull/1793
Fixes #
Not Tested
---

Fixing invokeRemoveAuthHeaderSuccessTest issue

---

resources/k8s-artifacts/mg-adapter/log4j2-configmap.yaml

Adding log4j2 configs to k8s artifacts.

---

resources/apim/docker-compose.yaml
resources/k8s-artifacts/mg-deployment/deployment.yaml

Adding memory limit to APIM with MG docker-compose file

---

pom.xml
remove-containers.sh
resources/apim/conf/deployment.toml
resources/apim/docker-compose.yaml
resources/docker-compose.yaml
resources/k8s-artifacts/apim/apim-config.yaml
resources/k8s-artifacts/apim/apim-deployment.yaml
resources/k8s-artifacts/mg-adapter/deployment.yaml
resources/k8s-artifacts/mg-deployment/deployment.yaml

Adding APIM Beta images and bumping carbon-apimgt version accordingly.
Fixes https://github.com/wso2/product-microgateway/issues/1743
Not Tested
---

Adding APIM beta images and bump carbon-apimgt version.

---

pom.xml

Bumping ballerina version.
This fix is already in the master. Since we are moving bal (existing master) to 3.2.x branch, this fix should go to 3.2.x.
Fixes #
Not Tested
---

Bump ballerina version

---

CONTRIBUTING.md
README.md
integration/test-integration/pom.xml

Fixing redirecting issues, readmes after refactoring "envoy-gw" branch to "main".
Fixes #
Not Tested
---

Changes due to moving 'envoy-gw' to 'main'.

---

enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/issuer/HttpTokenServerHandler.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/issuer/HttpTokenServerInitializer.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/issuer/JWTIssuerImpl.java
integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/apiDeploy/QSGTestCase.java
integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
integration/test-integration/src/test/resources/testng.xml
pom.xml

This will allow /testkey to issue jwts with scopes
Fixes #1842 
Not Tested
---

Fix #1842 - issue scopes with test key

---

adapter/internal/discovery/xds/server.go
adapter/internal/messaging/notification_listener.go
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/server/RequestHandler.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java

- Push dynamic policy updates to enforcer
- Fix an issue in undeploying API
- Prioritize x-forwarded-for header as clientIp
Fixes #1802
Fixes #1803 
Fixes #1844
Mac
---

Fix minor issues in global throttling

---

enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APISecurityConstants.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTConstants.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/oauth/OAuthAuthenticator.java
integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/jwtValidator/JwtTestCase.java

Fixes https://github.com/wso2/product-microgateway/issues/1847
Not Tested
---

Fix token validation when Authorization header is malformed

---

adapter/internal/synchronizer/keymanagers_fetcher.go
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/SignedJWTInfo.java

This PR will fix the issue in api invocation with invalid JWT  
Fixes https://github.com/wso2/product-microgateway/issues/1835
Not Tested
---

Fixing issue in api invocation with invalid JWT  

---

adapter/internal/messaging/throttle_data_listener.go
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java

- Fix subscription unblocking
- Populate authcontext for self jwt
- Make endpoint security work for self jwt 
Fixes #1832
Fixes #1848
Mac
---

Bug fixes and improvements

---

enforcer/src/main/java/org/wso2/choreo/connect/enforcer/config/ConfigHolder.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/exception/DataLoadingException.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/exception/DiscoveryException.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/exception/EnforcerException.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/KeyValidator.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/InternalAPIKeyAuthenticator.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTUtil.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/validator/JWTValidator.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java

* Log JWT verification error
* Rename the MGWException class to EnforcerException
Fixes https://github.com/wso2/product-microgateway/issues/1855
Not Tested
---

Improve logging

---

LICENSE
adapter/go.mod
adapter/go.sum
distribution/src/main/assembly/assembly.xml
integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/APIManagerWithMgwServerInstance.java
integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/MgwServerImpl.java
integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/context/MgwServerInstance.java
integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/util/ApictlUtils.java
resources/conf/config-for-eventhub.toml
resources/docker-compose/apim/docker-compose.yaml
resources/docker-compose/docker-compose.yaml

Add missing license, modify distribution structure as follows.
```
choreo-connect-0.9.0-SNAPSHOT
├── docker-compose
│   ├── choreo-connect
│   │   ├── conf
│   │   │   ├── config.toml
│   │   │   ├── log4j2.properties
│   │   │   └── log_config.toml
│   │   └── docker-compose.yaml
│   ├── choreo-connect-with-apim
│   │   ├── conf
│   │   │   ├── config.toml
│   │   │   ├── deployment.toml
│   │   │   ├── log4j2.properties
│   │   │   └── log_config.toml
│   │   └── docker-compose.yaml
│   └── resources
│       ├── adapter
│       │   └── security
│       │       ├── keystore
│       │       │   ├── mg.key
│       │       │   └── mg.pem
│       │       └── truststore
│       │           ├── consul
│       │           │   ├── consul-agent-ca.pem
│       │           │   ├── …
```

Adding License, changing distribution structure.

---

adapter/internal/discovery/xds/server.go
adapter/internal/messaging/event_types.go
adapter/internal/messaging/notification_listener.go

Bug fixes:
Revision Undeploy operation not working.
Random number generator used for xds Version generator is not seeded properly.
Fixes #1798 
Choreo-connect-with-apim setup
---

Bug Fixes: Revision Undeployment is not working.

---

adapter/internal/messaging/connection.go

This Pr will add info logs for connection retry 
Fixes #1865 
Not Tested
---

Improving info logs for connection retry

---

distribution/src/main/assembly/assembly.xml

Adding README.md to the distribution.

---

remove-containers.sh
resources/docker-compose/apim/docker-compose.yaml
resources/docker-compose/docker-compose.yaml
resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
resources/k8s-artifacts/choreo-connect/mg-deployment.yaml

Preparation for next development iteration.
Fixes #
Not Tested
---

Dev iteration for beta.

---

distribution/src/main/assembly/assembly.xml
enforcer/LICENSE.txt
release-note.html
remove-containers.sh
resources/docker-compose/apim/docker-compose.yaml
resources/docker-compose/docker-compose.yaml
resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml

Release preparation for alpha2. This include docker images name renaming.
Fixes #
Not Tested
---

Release prep for alpha2.

---

remove-containers.sh
resources/docker-compose/apim/docker-compose.yaml
resources/docker-compose/docker-compose.yaml
resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml

Changing images names, and other relevant places for the next development iteration (0.9.0-beta-snapshot)/
Fixes # NO issue needed.
Not Tested
---

Prep for next development iteration.

---

enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTUtil.java
enforcer/src/main/resources/Dockerfile
integration/test-integration/src/main/resources/META-INF/services/org.wso2.carbon.apimgt.common.gateway.jwttransformer.JWTTransformer

$subject
Fixes #1885
- Integration tests added: Covered from existing tests
Not Tested
---

Bring in java SPI to resolve customJWTTransformer

---

adapter/internal/oasparser/envoyconf/envoyconf_internal_test.go
adapter/internal/oasparser/envoyconf/routes_with_clusters.go

$subject.
Fixes #1888 
Fixes #1887
Not Tested
---

Bug Fixes: Routes are not matched when wildcard / path with suffix prefix are used.

---

adapter/internal/oasparser/config_generator.go
adapter/internal/oasparser/model/api_operation.go
adapter/internal/oasparser/model/constants.go
adapter/internal/oasparser/model/mgw_swagger.go

Add support for `x-wso2-throttling-tier` extension. Currently we only support `x-throttling-tier`
Fixes #1917
Mac, choreo-connect
---

Add support for x-wso2-throttling-tier

---

adapter/internal/adapter/adapter.go
adapter/internal/discovery/xds/callbacks.go
adapter/internal/discovery/xds/consul.go
adapter/internal/discovery/xds/enforcer_callbacks.go
adapter/internal/discovery/xds/server.go
adapter/internal/discovery/xds/state_cache.go

Add enforcer xds error handling and fall back implementation.
Fixes https://github.com/wso2/product-microgateway/issues/1907
Not Tested
---

Add Enforcer error handling and fallback implementation

---

enforcer/src/main/java/org/wso2/choreo/connect/enforcer/exception/APISecurityException.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/jwt/JWTAuthenticator.java
enforcer/src/main/resources/Dockerfile
integration/test-integration/src/test/java/org/wso2/choreo/connect/tests/testCases/jwtValidator/JwtTestCase.java

$subject
Fixes #1913
Fixes #1894 
Docker compose
---

No proper error response when the provided JWT cannot be parsed.

---

adapter/src/main/resources/Dockerfile
enforcer/src/main/resources/Dockerfile

Fixes https://github.com/wso2/product-microgateway/issues/1907
Not Tested
---

Remove copying unnecessary config files in dockerfiles

---

enforcer/src/main/java/org/wso2/choreo/connect/enforcer/constants/APIConstants.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/security/AuthFilter.java
enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/FilterUtils.java
resources/conf/config-for-eventhub.toml

$ subject and
Analytics Publishing with Internal-Key
Fixes #1928 
Fixes #1929
Not Tested
---

add missing configs

---

resources/k8s-artifacts/apim/apim-service.yaml
resources/k8s-artifacts/choreo-connect/config-toml-configmap-for-eventhub.yaml
resources/k8s-artifacts/choreo-connect/config-toml-configmap.yaml

Updating k8s artifacts by adding missing configs and removing unwanted configs.
Not Tested
---

updating k8s artifacts.

---

enforcer/LICENSE.txt
remove-containers.sh
resources/docker-compose/apim/docker-compose.yaml
resources/docker-compose/docker-compose.yaml
resources/k8s-artifacts/choreo-connect/adapter-deployment.yaml
resources/k8s-artifacts/choreo-connect/choreo-connect-deployment.yaml

Preparing for beta release.
This PR includes image name changes and licence file updates.
Fixes #
Not Tested
---

Updating license and prepping for release.
